// Wikybook — Data historis: inggris
// File ini di-generate otomatis. Jangan edit manual.

if (typeof window.countryDataFiles === 'undefined') window.countryDataFiles = {};

window.countryDataFiles['inggris'] = {
    names: { id: 'Inggris', en: 'England/Britain', ja: 'イギリス', ko: '영국', zh: '英国' },
    flag: '🇬🇧',
    articles: [
      {
        id: 'inggris-norman-conquest-1066',
        langs: {
          id: { title: 'Norman Conquest 1066', desc: 'Peristiwa penting dalam sejarah Inggris yang membentuk peradaban kawasan.', content: '<p class="mb-4">Norman Conquest 1066 adalah salah satu momen paling berpengaruh dalam sejarah Inggris. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Norman Conquest 1066 masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Norman Conquest 1066 sebagai bagian tak terpisahkan dari identitas kolektif bangsa Inggris.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Norman Conquest 1066. | Encyclopaedia Britannica — Norman Conquest 1066. | National Geographic — Norman Conquest 1066.' },
          en: { title: 'Norman Conquest 1066', desc: 'A defining moment in the history of England/Britain that shaped its civilization.', content: '<p class="mb-4">Norman Conquest 1066 stands as one of the most consequential events in the long history of England/Britain. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Norman Conquest 1066 from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Norman Conquest 1066 endures in the cultural memory and national identity of the people of England/Britain, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Norman Conquest 1066. | Encyclopaedia Britannica — Norman Conquest 1066. | National Geographic — Norman Conquest 1066.' },
          ja: { title: 'Norman Conquest 1066', desc: 'イギリスの歴史を形成した重要な出来事。', content: '<p class="mb-4">Norman Conquest 1066はイギリスの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはNorman Conquest 1066を様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Norman Conquest 1066の遺産はイギリスの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Norman Conquest 1066. | Encyclopaedia Britannica — Norman Conquest 1066. | National Geographic — Norman Conquest 1066.' },
          ko: { title: 'Norman Conquest 1066', desc: '영국의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Norman Conquest 1066은(는) 영국의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Norman Conquest 1066을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Norman Conquest 1066의 유산은 영국 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Norman Conquest 1066. | Encyclopaedia Britannica — Norman Conquest 1066. | National Geographic — Norman Conquest 1066.' },
          zh: { title: 'Norman Conquest 1066', desc: '塑造英国历史的重要事件。', content: '<p class="mb-4">Norman Conquest 1066是英国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Norman Conquest 1066，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Norman Conquest 1066的遗产延续在英国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Norman Conquest 1066. | Encyclopaedia Britannica — Norman Conquest 1066. | National Geographic — Norman Conquest 1066.' },
        }
      },
      {
        id: 'inggris-magna-carta-1215',
        langs: {
          id: { title: 'Magna Carta 1215', desc: 'Peristiwa penting dalam sejarah Inggris yang membentuk peradaban kawasan.', content: '<p class="mb-4">Magna Carta 1215 adalah salah satu momen paling berpengaruh dalam sejarah Inggris. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Magna Carta 1215 masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Magna Carta 1215 sebagai bagian tak terpisahkan dari identitas kolektif bangsa Inggris.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Magna Carta 1215. | Encyclopaedia Britannica — Magna Carta 1215. | National Geographic — Magna Carta 1215.' },
          en: { title: 'Magna Carta 1215', desc: 'A defining moment in the history of England/Britain that shaped its civilization.', content: '<p class="mb-4">Magna Carta 1215 stands as one of the most consequential events in the long history of England/Britain. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Magna Carta 1215 from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Magna Carta 1215 endures in the cultural memory and national identity of the people of England/Britain, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Magna Carta 1215. | Encyclopaedia Britannica — Magna Carta 1215. | National Geographic — Magna Carta 1215.' },
          ja: { title: 'Magna Carta 1215', desc: 'イギリスの歴史を形成した重要な出来事。', content: '<p class="mb-4">Magna Carta 1215はイギリスの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはMagna Carta 1215を様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Magna Carta 1215の遺産はイギリスの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Magna Carta 1215. | Encyclopaedia Britannica — Magna Carta 1215. | National Geographic — Magna Carta 1215.' },
          ko: { title: 'Magna Carta 1215', desc: '영국의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Magna Carta 1215은(는) 영국의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Magna Carta 1215을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Magna Carta 1215의 유산은 영국 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Magna Carta 1215. | Encyclopaedia Britannica — Magna Carta 1215. | National Geographic — Magna Carta 1215.' },
          zh: { title: 'Magna Carta 1215', desc: '塑造英国历史的重要事件。', content: '<p class="mb-4">Magna Carta 1215是英国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Magna Carta 1215，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Magna Carta 1215的遗产延续在英国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Magna Carta 1215. | Encyclopaedia Britannica — Magna Carta 1215. | National Geographic — Magna Carta 1215.' },
        }
      },
      {
        id: 'inggris-british-empire',
        langs: {
          id: { title: 'British Empire', desc: 'Peristiwa penting dalam sejarah Inggris yang membentuk peradaban kawasan.', content: '<p class="mb-4">British Empire adalah salah satu momen paling berpengaruh dalam sejarah Inggris. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari British Empire masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari British Empire sebagai bagian tak terpisahkan dari identitas kolektif bangsa Inggris.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — British Empire. | Encyclopaedia Britannica — British Empire. | National Geographic — British Empire.' },
          en: { title: 'British Empire', desc: 'A defining moment in the history of England/Britain that shaped its civilization.', content: '<p class="mb-4">British Empire stands as one of the most consequential events in the long history of England/Britain. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined British Empire from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of British Empire endures in the cultural memory and national identity of the people of England/Britain, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — British Empire. | Encyclopaedia Britannica — British Empire. | National Geographic — British Empire.' },
          ja: { title: 'British Empire', desc: 'イギリスの歴史を形成した重要な出来事。', content: '<p class="mb-4">British Empireはイギリスの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはBritish Empireを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">British Empireの遺産はイギリスの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — British Empire. | Encyclopaedia Britannica — British Empire. | National Geographic — British Empire.' },
          ko: { title: 'British Empire', desc: '영국의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">British Empire은(는) 영국의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 British Empire을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">British Empire의 유산은 영국 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — British Empire. | Encyclopaedia Britannica — British Empire. | National Geographic — British Empire.' },
          zh: { title: 'British Empire', desc: '塑造英国历史的重要事件。', content: '<p class="mb-4">British Empire是英国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了British Empire，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">British Empire的遗产延续在英国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — British Empire. | Encyclopaedia Britannica — British Empire. | National Geographic — British Empire.' },
        }
      },
      {
        id: 'inggris-industrial-revolution',
        langs: {
          id: { title: 'Industrial Revolution', desc: 'Peristiwa penting dalam sejarah Inggris yang membentuk peradaban kawasan.', content: '<p class="mb-4">Industrial Revolution adalah salah satu momen paling berpengaruh dalam sejarah Inggris. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Industrial Revolution masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Industrial Revolution sebagai bagian tak terpisahkan dari identitas kolektif bangsa Inggris.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Industrial Revolution. | Encyclopaedia Britannica — Industrial Revolution. | National Geographic — Industrial Revolution.' },
          en: { title: 'Industrial Revolution', desc: 'A defining moment in the history of England/Britain that shaped its civilization.', content: '<p class="mb-4">Industrial Revolution stands as one of the most consequential events in the long history of England/Britain. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Industrial Revolution from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Industrial Revolution endures in the cultural memory and national identity of the people of England/Britain, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Industrial Revolution. | Encyclopaedia Britannica — Industrial Revolution. | National Geographic — Industrial Revolution.' },
          ja: { title: 'Industrial Revolution', desc: 'イギリスの歴史を形成した重要な出来事。', content: '<p class="mb-4">Industrial Revolutionはイギリスの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはIndustrial Revolutionを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Industrial Revolutionの遺産はイギリスの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Industrial Revolution. | Encyclopaedia Britannica — Industrial Revolution. | National Geographic — Industrial Revolution.' },
          ko: { title: 'Industrial Revolution', desc: '영국의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Industrial Revolution은(는) 영국의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Industrial Revolution을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Industrial Revolution의 유산은 영국 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Industrial Revolution. | Encyclopaedia Britannica — Industrial Revolution. | National Geographic — Industrial Revolution.' },
          zh: { title: 'Industrial Revolution', desc: '塑造英国历史的重要事件。', content: '<p class="mb-4">Industrial Revolution是英国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Industrial Revolution，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Industrial Revolution的遗产延续在英国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Industrial Revolution. | Encyclopaedia Britannica — Industrial Revolution. | National Geographic — Industrial Revolution.' },
        }
      },
      {
        id: 'inggris-world-war-ii-churchill',
        langs: {
          id: { title: 'World War II Churchill', desc: 'Peristiwa penting dalam sejarah Inggris yang membentuk peradaban kawasan.', content: '<p class="mb-4">World War II Churchill adalah salah satu momen paling berpengaruh dalam sejarah Inggris. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari World War II Churchill masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari World War II Churchill sebagai bagian tak terpisahkan dari identitas kolektif bangsa Inggris.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — World War II Churchill. | Encyclopaedia Britannica — World War II Churchill. | National Geographic — World War II Churchill.' },
          en: { title: 'World War II Churchill', desc: 'A defining moment in the history of England/Britain that shaped its civilization.', content: '<p class="mb-4">World War II Churchill stands as one of the most consequential events in the long history of England/Britain. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined World War II Churchill from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of World War II Churchill endures in the cultural memory and national identity of the people of England/Britain, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — World War II Churchill. | Encyclopaedia Britannica — World War II Churchill. | National Geographic — World War II Churchill.' },
          ja: { title: 'World War II Churchill', desc: 'イギリスの歴史を形成した重要な出来事。', content: '<p class="mb-4">World War II Churchillはイギリスの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはWorld War II Churchillを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">World War II Churchillの遺産はイギリスの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — World War II Churchill. | Encyclopaedia Britannica — World War II Churchill. | National Geographic — World War II Churchill.' },
          ko: { title: 'World War II Churchill', desc: '영국의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">World War II Churchill은(는) 영국의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 World War II Churchill을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">World War II Churchill의 유산은 영국 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — World War II Churchill. | Encyclopaedia Britannica — World War II Churchill. | National Geographic — World War II Churchill.' },
          zh: { title: 'World War II Churchill', desc: '塑造英国历史的重要事件。', content: '<p class="mb-4">World War II Churchill是英国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了World War II Churchill，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">World War II Churchill的遗产延续在英国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — World War II Churchill. | Encyclopaedia Britannica — World War II Churchill. | National Geographic — World War II Churchill.' },
        }
      },
      {
        id: 'global-apollo11',
        langs: {
          id: { title: 'Apollo 11 — Manusia Pertama di Bulan (1969)', desc: 'Misi luar angkasa paling bersejarah saat Neil Armstrong mendarat di Bulan pada 20 Juli 1969.', content: '<p class="mb-4">Pada 20 Juli 1969 pukul 20:17 UTC, wahana pendaratan <em>Eagle</em> misi Apollo 11 menyentuh permukaan Bulan di kawasan <strong>Sea of Tranquility</strong>. Neil Armstrong menjadi manusia pertama yang menginjakkan kaki di Bulan, diikuti Buzz Aldrin, sementara Michael Collins mengorbit di atas.</p><p class="mb-4">Armstrong mengucapkan kata-kata ikonik: <em>"That\'s one small step for man, one giant leap for mankind."</em> Momen ini disaksikan sekitar 600 juta orang di seluruh dunia — sepertiga populasi Bumi saat itu.</p><p class="mb-4">Program Apollo merespons <strong>Space Race</strong> antara AS dan Uni Soviet. Presiden Kennedy pada 1961 berjanji mengirim manusia ke Bulan sebelum akhir dekade — terpenuhi delapan tahun kemudian.</p><p class="mb-4">Selama 21 jam 36 menit di Bulan, astronot mengumpulkan 21,5 kg sampel batuan, memasang bendera, dan menempatkan retroreflektor laser yang hingga kini dipakai ilmuwan mengukur jarak Bumi-Bulan.</p><p class="mb-4">Apollo 11 adalah puncak upaya 400.000 insinyur selama 8 tahun dengan biaya USD 25,4 miliar — setara lebih dari USD 170 miliar saat ini.</p>', sourceDomain: 'nasa.gov', sourceSnippet: 'NASA — Apollo 11 Mission Overview. | Space.com — First Moon Landing, July 20, 1969. | Smithsonian National Air and Space Museum — Apollo 11. | History.com — Moon Landing.' },
          en: { title: 'Apollo 11 — First Humans on the Moon (1969)', desc: 'The most historic space mission when Neil Armstrong became the first human to walk on the Moon.', content: '<p class="mb-4">On July 20, 1969 at 20:17 UTC, Apollo 11\'s <em>Eagle</em> landed on the Moon\'s <strong>Sea of Tranquility</strong>. Neil Armstrong became the first human on the Moon, followed by Buzz Aldrin; Michael Collins orbited above.</p><p class="mb-4">Armstrong\'s iconic words: <em>"That\'s one small step for man, one giant leap for mankind"</em> were heard live by ~600 million people — one-third of Earth\'s population.</p><p class="mb-4">The Apollo program was America\'s answer to the <strong>Space Race</strong>. President Kennedy\'s 1961 pledge to reach the Moon before decade\'s end was fulfilled eight years later.</p><p class="mb-4">In 21 hours 36 minutes on the surface, the crew collected 21.5 kg of lunar samples and placed a laser retroreflector still used by scientists today.</p><p class="mb-4">Apollo 11 was the culmination of 400,000 engineers over 8 years, costing USD 25.4 billion — over USD 170 billion in today\'s money.</p>', sourceDomain: 'nasa.gov', sourceSnippet: 'NASA — Apollo 11 Mission Overview. | Space.com — First Moon Landing. | Smithsonian National Air and Space Museum. | History.com — Moon Landing.' },
          ja: { title: 'アポロ11号 — 月面に立った最初の人類（1969年）', desc: '1969年7月20日、ニール・アームストロングが月面を歩いた歴史的ミッション。', content: '<p class="mb-4">1969年7月20日20時17分UTC、アポロ11号着陸船<em>イーグル</em>が月の<strong>静かの海</strong>に着陸。ニール・アームストロングが最初の月面歩行者となりました。</p><p class="mb-4">名言「<em>これは一人の人間の小さな一歩、人類の偉大な飛躍だ</em>」は約6億人が生中継で目撃しました。</p><p class="mb-4">アポロ計画は米ソ宇宙開発競争への回答で、ケネディの1961年の誓いを8年後に実現しました。</p>', sourceDomain: 'nasa.gov', sourceSnippet: 'NASA — アポロ11号ミッション概要。| Space.com — 人類初の月面着陸。| Smithsonian National Air and Space Museum。. | History.com — アポロ11号ミッション概要。| Space.com — 人類初の月面着陸。| Smithsonian National Air and Space Museum。. | National Geographic — アポロ11号ミッション概要。| Space.com — 人類初の月面着陸。| Smithsonian National Air and Space Museum。.' },
          ko: { title: '아폴로 11호 — 달에 첫발을 내딛은 인류 (1969년)', desc: '1969년 7월 20일 닐 암스트롱이 달 표면을 걸은 역사적 임무.', content: '<p class="mb-4">1969년 7월 20일 20시 17분 UTC, 아폴로 11호 착륙선 <em>이글</em>이 달의 <strong>고요의 바다</strong>에 착륙. 닐 암스트롱이 최초의 달 표면 보행자가 되었습니다.</p><p class="mb-4">명언 "<em>한 인간에게는 작은 발걸음, 인류에게는 위대한 도약</em>"은 약 6억 명이 생방송으로 목격했습니다.</p><p class="mb-4">케네디의 1961년 약속이 8년 후 실현되었습니다. 총 비용 USD 254억, 현재 가치 1,700억 달러 이상.</p>', sourceDomain: 'nasa.gov', sourceSnippet: 'NASA — 아폴로 11호 임무 개요. | Space.com — 인류 첫 달 착륙. | Smithsonian National Air and Space Museum.' },
          zh: { title: '阿波罗11号 — 人类首次登月 (1969年)', desc: '1969年7月20日尼尔·阿姆斯特朗成为首位踏上月球的人类。', content: '<p class="mb-4">1969年7月20日20时17分UTC，阿波罗11号登月舱<em>鹰号</em>降落在月球<strong>静海</strong>。尼尔·阿姆斯特朗成为首位踏上月球的人。</p><p class="mb-4">名言"<em>这是个人的一小步，人类的一大步</em>"被约6亿人通过现场直播见证。</p><p class="mb-4">肯尼迪1961年的承诺8年后实现。总耗资254亿美元，相当于今天的1700亿美元以上。</p>', sourceDomain: 'nasa.gov', sourceSnippet: 'NASA — 阿波罗11号任务概述。| Space.com — 人类首次登月。| 史密森尼国家航空航天博物馆。. | Space.com — 阿波罗11号任务概述。| Space.com — 人类首次登月。| 史密森尼国家航空航天博物馆。. | Smithsonian National Air and Space Museum — 阿波罗11号任务概述。| Space.com — 人类首次登月。| 史密森尼国家航空航天博物馆。.' }
        }
      }
    ]
  };
