// Wikybook — Data historis: mesir
// File ini di-generate otomatis. Jangan edit manual.

if (typeof window.countryDataFiles === 'undefined') window.countryDataFiles = {};

window.countryDataFiles['mesir'] = {
    names: { id: 'Mesir Kuno', en: 'Ancient Egypt', ja: '古代エジプト', ko: '고대 이집트', zh: '古埃及' },
    flag: '🇪🇬',
    articles: [
      {
        id: 'mesir-piramida',
        langs: {
          id: { title: 'Piramida Agung Giza', desc: 'Satu-satunya dari Tujuh Keajaiban Dunia Kuno yang masih berdiri, dibangun sekitar 2560 SM.', content: '<p class="mb-4">Piramida Agung Giza dibangun sebagai makam Firaun Khufu sekitar 2560 SM. Terdiri dari sekitar 2,3 juta blok batu dengan berat rata-rata 2,5 ton setiap bloknya. Tanpa mesin modern, ribuan pekerja membangunnya selama 20 tahun.</p><p class="mb-4">Tingginya mencapai 146,5 meter saat dibangun — menjadikannya bangunan tertinggi di dunia selama 3.800 tahun hingga Katedral Lincoln selesai pada 1311 M.</p><p class="mb-4">Hingga kini, cara persis pembangunan piramida masih menjadi misteri dan diperdebatkan para arkeolog dunia.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Encyclopaedia Britannica — Piramida Agung Giza.' },
          en: { title: 'Great Pyramid of Giza', desc: 'The only surviving Wonder of the Ancient World, built around 2560 BC.', content: '<p class="mb-4">The Great Pyramid of Giza was built as Pharaoh Khufu\'s tomb around 2560 BC. It consists of approximately 2.3 million stone blocks averaging 2.5 tons each. Without modern machinery, thousands of workers built it over 20 years.</p><p class="mb-4">At 146.5 meters tall when built, it was the world\'s tallest structure for 3,800 years until Lincoln Cathedral was completed in 1311 CE.</p><p class="mb-4">The exact method of pyramid construction remains a mystery debated by archaeologists worldwide.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Great Pyramid of Giza.' },
          ja: { title: 'ギザの大ピラミッド', desc: '紀元前2560年頃に建設された、古代世界の七不思議のうち現存する唯一のもの。', content: '<p class="mb-4">ギザの大ピラミッドは紀元前2560年頃にファラオ・クフの墓として建設されました。平均2.5トンの石块约230万個で構成されています。近代的な機械なしに、数千人の労働者が20年かけて建設しました。</p><p class="mb-4">建設時の高さは146.5メートルで、1311年にリンカーン大聖堂が完成するまで3,800年間、世界最高の建造物でした。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — ギザの大ピラミッド。' },
          ko: { title: '기자의 대피라미드', desc: '기원전 2560년경에 건설된 고대 세계 7대 불가사의 중 유일하게 남아있는 것.', content: '<p class="mb-4">기자의 대피라미드는 기원전 2560년경 파라오 쿠푸의 무덤으로 건설되었습니다. 평균 2.5톤의 돌블록 약 230만 개로 구성되어 있습니다. 현대 기계 없이 수천 명의 노동자가 20년에 걸쳐 건설했습니다.</p>', sourceDomain: 'britannica.com', 고Snippet: 'Britannica — 기자의 대피라미드.' },
          zh: { title: '吉萨大金字塔', desc: '建于约公元前2560年，古代世界七大奇迹中唯一幸存的建筑。', content: '<p class="mb-4">吉萨大金字塔建于约公元前2560年，作为法老胡夫的陵墓。由约230万块平均重2.5吨的石块组成。没有现代机械，数千名工人花了20年建造。</p><p class="mb-4">建造时高146.5米，是世界最高建筑，直到1311年林肯大教堂完工，这一纪录保持了3800年。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 吉萨大金字塔。' }
        }
      },
      {
        id: 'mesir-firaun',
        langs: {
          id: { title: 'Para Firaun Legendaris', desc: 'Kisah Ramses II, Tutankhamun, dan Cleopatra — para penguasa Mesir yang namanya abadi dalam sejarah.', content: '<p class="mb-4"><strong>Ramses II</strong> (1279–1213 SM) adalah firaun terbesar Mesir, memerintah selama 66 tahun. Ia membangun lebih banyak monumen dari firaun manapun, termasuk kuil megah Abu Simbel. Dikenal sebagai "Ramses Agung."</p><p class="mb-4"><strong>Tutankhamun</strong> menjadi firaun usia 9 tahun dan meninggal usia 18. Namun penemuannya menjadi fenomenal — pada 1922, Howard Carter menemukan makamnya yang utuh dengan harta karun senilai miliaran dolar.</p><p class="mb-4"><strong>Cleopatra VII</strong> adalah firaun terakhir Mesir — cerdas, fasih 9 bahasa, dan punya hubungan romantis dengan Julius Caesar dan Mark Antony sebelum Mesir jatuh ke tangan Romawi.</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — Para Firaun Legendaris Mesir Kuno.' },
          en: { title: 'Legendary Pharaohs', desc: 'The stories of Ramses II, Tutankhamun, and Cleopatra — Egyptian rulers whose names are immortalized in history.', content: '<p class="mb-4"><strong>Ramses II</strong> (1279–1213 BC) was Egypt\'s greatest pharaoh, ruling for 66 years. He built more monuments than any other pharaoh, including the magnificent Abu Simbel temple.</p><p class="mb-4"><strong>Tutankhamun</strong> became pharaoh at age 9 and died at 18. But his discovery was phenomenal — in 1922, Howard Carter found his intact tomb with billions worth of treasures.</p><p class="mb-4"><strong>Cleopatra VII</strong> was Egypt\'s last pharaoh — brilliant, fluent in 9 languages, with romantic ties to Julius Caesar and Mark Antony before Egypt fell to Rome.</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — Legendary Pharaohs of Ancient Egypt.' },
          ja: { title: '伝説のファラオたち', desc: 'ラムセス2世、ツタンカーメン、クレオパトラ — 歴史に名を刻んだエジプトの支配者たち。', content: '<p class="mb-4"><strong>ラムセス2世</strong>（紀元前1279–1213年）は66年間統治したエジプト最大のファラオで、アブ・シンベル神殿を含む多くの記念碑を建設しました。</p><p class="mb-4"><strong>ツタンカーメン</strong>は9歳でファラオになり18歳で死亡しましたが、1922年のハワード・カーターによる彼の無傷の墓の発見は世界的な現象となりました。</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — 古代エジプトの伝説のファラオ。' },
          ko: { title: '전설적인 파라오들', desc: '람세스 2세, 투탕카멘, 클레오파트라 — 역사에 이름을 새긴 이집트의 통치자들.', content: '<p class="mb-4"><strong>람세스 2세</strong>(기원전 1279–1213년)는 66년간 통치한 이집트 최대의 파라오로, 아부 심벨 신전을 포함한 수많은 기념물을 건설했습니다.</p><p class="mb-4"><strong>투탕카멘</strong>은 9세에 파라오가 되어 18세에 사망했지만, 1922년 하워드 카터의 무덤 발견은 세계적인 현상이 되었습니다.</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — 고대 이집트의 전설적인 파라오들.' },
          zh: { title: '传奇法老们', desc: '拉美西斯二世、图坦卡蒙和克利奥帕特拉——在历史上留下永恒印记的埃及统治者。', content: '<p class="mb-4"><strong>拉美西斯二世</strong>（公元前1279–1213年）是统治了66年的埃及最伟大法老，建造了包括阿布辛拜勒神庙在内的众多纪念碑。</p><p class="mb-4"><strong>图坦卡蒙</strong>9岁登基，18岁去世，但1922年霍华德·卡特发现其完整陵墓成为世界现象。</p><p class="mb-4"><strong>克利奥帕特拉七世</strong>是埃及最后一位法老——才华横溢，精通9种语言，与凯撒和安东尼有过浪漫关系，直到埃及落入罗马人之手。</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — 古埃及传奇法老。' }
        }
      },
      {
        id: 'mesir-hieroglif',
        langs: {
          id: { title: 'Hieroglif — Tulisan Suci Mesir', desc: 'Sistem tulisan piktografis yang digunakan selama 3.500 tahun dan menjadi kunci memahami peradaban Mesir Kuno.', content: '<p class="mb-4">Hieroglif (dari bahasa Yunani: "tulisan suci") adalah sistem tulisan bergambar yang dikembangkan Mesir sekitar 3200 SM. Terdiri dari lebih dari 700 tanda yang mewakili suara, kata, atau konsep.</p><p class="mb-4">Selama berabad-abad hieroglif menjadi misteri yang tak terpecahkan — hingga penemuan <strong>Batu Rosetta</strong> pada 1799. Batu ini memuat teks yang sama dalam tiga bahasa: hieroglif, demotik, dan Yunani kuno.</p><p class="mb-4">Thomas Young dan Jean-François Champollion berhasil menguraikan hieroglif pada 1822, membuka kembali jendela menuju peradaban Mesir kuno yang kaya.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Hieroglif Mesir Kuno dan Batu Rosetta.' },
          en: { title: 'Hieroglyphs — Sacred Egyptian Writing', desc: 'The pictographic writing system used for 3,500 years that became the key to understanding Ancient Egyptian civilization.', content: '<p class="mb-4">Hieroglyphs (from Greek: "sacred writing") are Egypt\'s pictographic writing system developed around 3200 BC. They consist of over 700 signs representing sounds, words, or concepts.</p><p class="mb-4">For centuries, hieroglyphs remained an unsolved mystery — until the discovery of the <strong>Rosetta Stone</strong> in 1799. This stone contains the same text in three scripts: hieroglyphic, demotic, and ancient Greek.</p><p class="mb-4">Thomas Young and Jean-François Champollion successfully deciphered hieroglyphs in 1822, reopening the window to rich ancient Egyptian civilization.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Egyptian Hieroglyphs and Rosetta Stone.' },
          ja: { title: 'ヒエログリフ — エジプトの神聖文字', desc: '3500年間使用され、古代エジプト文明を理解する鍵となった象形文字体系。', content: '<p class="mb-4">ヒエログリフ（ギリシャ語で「神聖な文字」）は紀元前3200年頃に発展したエジプトの象形文字体系です。音、言葉、概念を表す700以上の記号で構成されています。</p><p class="mb-4">1799年のロゼッタ・ストーンの発見まで、ヒエログリフは解読不能な謎でした。1822年にシャンポリオンが解読に成功しました。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — エジプトのヒエログリフ。' },
          ko: { title: '상형문자 — 이집트의 신성한 글자', desc: '3500년간 사용되어 고대 이집트 문명 이해의 열쇠가 된 상형 문자 체계.', content: '<p class="mb-4">상형문자(그리스어로 "신성한 글자")는 기원전 3200년경에 발전한 이집트의 그림문자 체계입니다. 소리, 단어, 개념을 나타내는 700개 이상의 기호로 구성됩니다.</p><p class="mb-4">1799년 로제타석 발견까지 상형문자는 풀리지 않는 수수께끼였습니다. 1822년 샹폴리옹이 해독에 성공했습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 이집트 상형문자.' },
          zh: { title: '象形文字——埃及神圣的书写', desc: '使用了3500年，成为理解古埃及文明关键的象形文字体系。', content: '<p class="mb-4">象形文字（希腊语意为"神圣的书写"）是约公元前3200年发展起来的埃及图形文字体系，由700多个代表声音、词语或概念的符号组成。</p><p class="mb-4">几个世纪来，象形文字是个未解之谜，直到1799年发现罗塞塔石碑。1822年商博良成功解读了象形文字。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 埃及象形文字。' }
        }
      }
    ]
  };
