// Wikybook — Data historis: jepang
// File ini di-generate otomatis. Jangan edit manual.

if (typeof window.countryDataFiles === 'undefined') window.countryDataFiles = {};

window.countryDataFiles['jepang'] = {
    names: { id: 'Jepang', en: 'Japan', ja: '日本', ko: '일본', zh: '日本' },
    flag: '🇯🇵',
    articles: [
      {
        id: 'jepang-samurai',
        langs: {
          id: { title: 'Era Samurai dan Keshogunan', desc: 'Masa kejayaan para ksatria samurai yang mendominasi politik dan budaya Jepang selama berabad-abad.', content: '<p class="mb-4">Samurai adalah kelas prajurit bangsawan yang mendominasi Jepang dari abad ke-12 hingga ke-19. Dipandu oleh kode etik <strong>Bushido</strong> (Jalan Ksatria), samurai menjunjung tinggi kesetiaan, kehormatan, dan kesiapan mati untuk tuan mereka.</p><p class="mb-4">Keshogunan Tokugawa (1603–1868) adalah puncak era samurai. Selama 265 tahun, Jepang ditutup dari dunia luar dalam kebijakan <em>Sakoku</em>. Negeri ini stabil namun terisolasi.</p><p class="mb-4">Era samurai berakhir dengan Restorasi Meiji 1868 ketika modernisasi Barat menggeser sistem feodal lama.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Samurai dan Keshogunan Jepang.' },
          en: { title: 'Samurai Era & Shogunate', desc: 'The golden age of samurai warriors who dominated Japanese politics and culture for centuries.', content: '<p class="mb-4">Samurai were the noble warrior class dominating Japan from the 12th to 19th centuries. Guided by <strong>Bushido</strong> (The Way of the Warrior), samurai upheld loyalty, honor, and readiness to die for their lord.</p><p class="mb-4">The Tokugawa Shogunate (1603–1868) was the peak of the samurai era. For 265 years, Japan was closed to the outside world under the <em>Sakoku</em> policy.</p><p class="mb-4">The samurai era ended with the 1868 Meiji Restoration when Western modernization replaced the old feudal system.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Japanese Samurai Era.' },
          ja: { title: '武士の時代と江戸幕府', desc: '何世紀にもわたって日本の政治と文化を支配した武士の黄金時代。', content: '<p class="mb-4">武士は12世紀から19世紀にかけて日本を支配した武士貴族階級でした。<strong>武士道</strong>（武士の道）に導かれ、忠誠心、名誉、主君のために死ぬ覚悟を重んじました。</p><p class="mb-4">徳川幕府（1603–1868）は武士の時代の頂点でした。265年間、<em>鎖国</em>政策により日本は外界から閉ざされていました。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia — 武士の時代。' },
          ko: { title: '사무라이 시대와 막부', desc: '수세기 동안 일본의 정치와 문화를 지배한 사무라이 전사들의 황금기.', content: '<p class="mb-4">사무라이는 12세기부터 19세기까지 일본을 지배한 귀족 전사 계급이었습니다. <strong>무사도</strong>(무사의 길)에 따라 충성, 명예, 주군을 위한 죽음의 준비를 중시했습니다.</p><p class="mb-4">도쿠가와 막부(1603–1868)는 사무라이 시대의 정점이었습니다. 265년 동안 <em>쇄국</em> 정책으로 일본은 외부 세계와 단절되었습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia — 사무라이 시대.' },
          zh: { title: '武士时代与幕府', desc: '武士战士主导日本政治和文化数百年的黄金时代。', content: '<p class="mb-4">武士是从12世纪到19世纪主导日本的贵族战士阶级。以<strong>武士道</strong>（武士之路）为指引，武士重视忠诚、荣誉和为主君牺牲的准备。</p><p class="mb-4">德川幕府（1603–1868）是武士时代的顶峰。265年间，日本在<em>锁国</em>政策下与外界隔绝。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia — 武士时代。' }
        }
      },
      {
        id: 'jepang-meiji',
        langs: {
          id: { title: 'Restorasi Meiji', desc: 'Transformasi revolusioner Jepang dari negara feodal menjadi kekuatan industri modern dalam waktu singkat.', content: '<p class="mb-4">Restorasi Meiji (1868) adalah revolusi dari atas yang mengubah Jepang dalam waktu luar biasa singkat. Ketika Komodor Perry dari Amerika membuka paksa pelabuhan Jepang (1853), Jepang sadar ketinggalan zaman.</p><p class="mb-4">Dalam 40 tahun, Jepang membangun angkatan laut modern, sistem perkeretaapian, universitas, industri baja, dan konstitusi bergaya Barat. Slogan <em>"Wakon Yosai"</em> (Semangat Jepang, Keahlian Barat) menjadi panduan modernisasi.</p><p class="mb-4">Hasilnya mengejutkan dunia: Jepang mengalahkan Tiongkok (1895) dan Rusia (1905) — pertama kalinya bangsa Asia mengalahkan kekuatan Eropa.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Encyclopaedia Britannica — Restorasi Meiji Jepang.' },
          en: { title: 'Meiji Restoration', desc: 'Japan\'s revolutionary transformation from a feudal state to a modern industrial power in a remarkably short time.', content: '<p class="mb-4">The Meiji Restoration (1868) was a revolution from above that transformed Japan in a remarkably short time. When Commodore Perry forced open Japanese ports (1853), Japan realized it was falling behind.</p><p class="mb-4">Within 40 years, Japan built a modern navy, railway system, universities, steel industry, and Western-style constitution. The slogan <em>"Wakon Yosai"</em> (Japanese Spirit, Western Skills) guided modernization.</p><p class="mb-4">The results shocked the world: Japan defeated China (1895) and Russia (1905) — the first time an Asian nation defeated a European power.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Meiji Restoration.' },
          ja: { title: '明治維新', desc: '封建国家から近代工業大国への日本の革命的変革。', content: '<p class="mb-4">明治維新（1868年）は、日本を驚くほど短期間で変革した上からの革命でした。ペリー提督が日本の港を強制開港（1853年）した時、日本は遅れを取っていることに気づきました。</p><p class="mb-4">40年以内に、日本は近代的な海軍、鉄道網、大学、鉄鋼産業、西洋式憲法を構築しました。<em>「和魂洋才」</em>というスローガンが近代化を導きました。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 明治維新。' },
          ko: { title: '메이지 유신', desc: '봉건 국가에서 근대 산업 강국으로의 일본의 혁명적 변혁.', content: '<p class="mb-4">메이지 유신(1868년)은 일본을 놀랍도록 짧은 시간에 변혁시킨 위로부터의 혁명이었습니다. 페리 제독이 일본 항구를 강제 개항(1853년)했을 때, 일본은 뒤처지고 있음을 깨달았습니다.</p><p class="mb-4">40년 만에 일본은 근대 해군, 철도망, 대학, 철강 산업, 서양식 헌법을 구축했습니다. <em>"화혼양재"</em> 슬로건이 근대화를 이끌었습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 메이지 유신.' },
          zh: { title: '明治维新', desc: '日本从封建国家到现代工业强国的革命性转变。', content: '<p class="mb-4">明治维新（1868年）是一场自上而下的革命，在极短时间内改变了日本。当佩里准将强行打开日本港口（1853年）时，日本意识到自己落后了。</p><p class="mb-4">40年内，日本建立了现代海军、铁路系统、大学、钢铁工业和西式宪法。<em>"和魂洋才"</em>的口号引导了现代化进程。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 明治维新。' }
        }
      },
      {
        id: 'jepang-hiroshima',
        langs: {
          id: { title: 'Bom Atom Hiroshima & Nagasaki', desc: 'Tragedi kemanusiaan terbesar dalam sejarah peperangan modern yang mengakhiri Perang Dunia II.', content: '<p class="mb-4">Pada 6 Agustus 1945, Amerika Serikat menjatuhkan bom atom pertama di Hiroshima, diikuti Nagasaki pada 9 Agustus 1945. Dalam sekejap, dua kota hancur lebur. Diperkirakan 129.000–226.000 jiwa meninggal.</p><p class="mb-4">Bom atom "Little Boy" (Hiroshima) dan "Fat Man" (Nagasaki) adalah senjata nuklir pertama yang digunakan dalam peperangan. Radiasi yang ditimbulkan terus membunuh selama bertahun-tahun setelahnya.</p><p class="mb-4">Jepang menyerah pada 15 Agustus 1945. Hiroshima kini menjadi simbol perdamaian dunia dengan Museum Perdamaian dan monumen Kubah Bom yang diakui UNESCO.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Pengeboman Atom Hiroshima dan Nagasaki.' },
          en: { title: 'Hiroshima & Nagasaki Atomic Bombs', desc: 'The greatest humanitarian tragedy in modern warfare history that ended World War II.', content: '<p class="mb-4">On August 6, 1945, the US dropped the first atomic bomb on Hiroshima, followed by Nagasaki on August 9. Two cities were instantly destroyed. An estimated 129,000–226,000 people died.</p><p class="mb-4">The "Little Boy" (Hiroshima) and "Fat Man" (Nagasaki) were the first nuclear weapons used in warfare. Radiation continued killing for years afterward.</p><p class="mb-4">Japan surrendered on August 15, 1945. Hiroshima is now a symbol of world peace with its Peace Museum and UNESCO-recognized A-Bomb Dome.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Hiroshima and Nagasaki Bombings.' },
          ja: { title: '広島・長崎への原爆投下', desc: '第二次世界大戦を終結させた現代戦争史上最大の人道的悲劇。', content: '<p class="mb-4">1945年8月6日、アメリカは広島に最初の原子爆弾を投下し、8月9日に長崎に続きました。2つの都市が瞬時に破壊され、推定12万9千〜22万6千人が死亡しました。</p><p class="mb-4">広島は今や、平和記念博物館とユネスコ認定の原爆ドームを持つ世界平和の象徴となっています。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 広島・長崎原爆。' },
          ko: { title: '히로시마 & 나가사키 원자폭탄', desc: '제2차 세계대전을 종식시킨 현대 전쟁사 최대의 인도주의적 비극.', content: '<p class="mb-4">1945년 8월 6일 미국이 히로시마에 첫 원자폭탄을 투하했고, 8월 9일 나가사키에 이어졌습니다. 두 도시가 순식간에 파괴되었고, 약 12만 9천~22만 6천 명이 사망했습니다.</p><p class="mb-4">히로시마는 이제 평화 기념관과 유네스코가 인정한 원폭 돔을 갖춘 세계 평화의 상징이 되었습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 히로시마 나가사키 원자폭탄.' },
          zh: { title: '广岛与长崎原子弹', desc: '结束第二次世界大战的现代战争史上最大的人道主义悲剧。', content: '<p class="mb-4">1945年8月6日，美国向广岛投下第一颗原子弹，8月9日又轰炸了长崎。两座城市瞬间被摧毁，估计有12.9万至22.6万人死亡。</p><p class="mb-4">广岛现在已成为世界和平的象征，拥有和平纪念馆和联合国教科文组织认定的原爆穹顶。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 广岛长崎原子弹。' }
        }
      }
    ]
  };
