// Wikybook — Data historis: romawi
// File ini di-generate otomatis. Jangan edit manual.

if (typeof window.countryDataFiles === 'undefined') window.countryDataFiles = {};

window.countryDataFiles['romawi'] = {
    names: { id: 'Romawi Kuno', en: 'Ancient Rome', ja: '古代ローマ', ko: '고대 로마', zh: '古罗马' },
    flag: '🏛️',
    articles: [
      {
        id: 'romawi-julius-caesar',
        langs: {
          id: { title: 'Julius Caesar', desc: 'Jenderal dan diktator Roma yang mengubah Republik menjadi cikal bakal Kekaisaran dan namanya abadi sepanjang masa.', content: '<p class="mb-4">Gaius Julius Caesar (100–44 SM) adalah sosok paling berpengaruh dalam sejarah Roma. Jenderal brilian yang menaklukkan Galia (Prancis modern) dalam 8 tahun, ia juga penulis, orator, dan politisi kelas dunia.</p><p class="mb-4">Ketika Caesar menyeberangi Sungai Rubicon (49 SM) dengan pasukannya — melanggar hukum Roma — ia memulai perang saudara melawan Pompey dan Senat. Ia menang dan menjadi diktator Roma.</p><p class="mb-4">Pada 15 Maret 44 SM (Ides of March), Caesar dibunuh oleh 23 tusukan dari sekelompok senator yang dipimpin Brutus dan Cassius. Kematiannya justru mengakhiri Republik dan melahirkan Kekaisaran Romawi.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Encyclopaedia Britannica — Julius Caesar.' },
          en: { title: 'Julius Caesar', desc: 'Rome\'s general and dictator who transformed the Republic into the precursor of the Empire — his name immortalized forever.', content: '<p class="mb-4">Gaius Julius Caesar (100–44 BC) was the most influential figure in Roman history. A brilliant general who conquered Gaul (modern France) in 8 years, he was also a world-class writer, orator, and politician.</p><p class="mb-4">When Caesar crossed the Rubicon River (49 BC) with his army — violating Roman law — he started a civil war against Pompey and the Senate. He won and became Rome\'s dictator.</p><p class="mb-4">On March 15, 44 BC (the Ides of March), Caesar was assassinated with 23 stab wounds by a group of senators led by Brutus and Cassius. His death paradoxically ended the Republic and birthed the Roman Empire.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Julius Caesar.' },
          ja: { title: 'ユリウス・カエサル', desc: '共和国を帝国の前身に変えたローマの将軍と独裁者。', content: '<p class="mb-4">ガイウス・ユリウス・カエサル（紀元前100–44年）はローマ史上最も影響力のある人物でした。8年でガリア（現代のフランス）を征服した天才的な将軍であり、世界クラスの作家、雄弁家、政治家でもありました。</p><p class="mb-4">紀元前44年3月15日（イードゥス・マルティアエ）、ブルートゥスとカッシウスが率いる元老院議員グループによって23カ所を刺されて暗殺されました。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — ユリウス・カエサル。' },
          ko: { title: '율리우스 카이사르', desc: '공화국을 제국의 전신으로 변모시킨 로마의 장군이자 독재자.', content: '<p class="mb-4">가이우스 율리우스 카이사르(기원전 100–44년)는 로마 역사에서 가장 영향력 있는 인물이었습니다. 8년 만에 갈리아(현대 프랑스)를 정복한 천재적인 장군이자 세계적인 작가, 연설가, 정치가였습니다.</p><p class="mb-4">기원전 44년 3월 15일(이두스 마르티아이), 브루투스와 카시우스가 이끄는 원로원 의원 그룹에 의해 23번 찔려 암살되었습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 율리우스 카이사르.' },
          zh: { title: '尤利乌斯·凯撒', desc: '将共和国转变为帝国前身的罗马将军和独裁者。', content: '<p class="mb-4">盖乌斯·尤利乌斯·凯撒（公元前100–44年）是罗马历史上最具影响力的人物。他是一位天才将军，在8年内征服了高卢（现代法国），同时也是世界级的作家、演说家和政治家。</p><p class="mb-4">公元前44年3月15日（三月望日），凯撒被布鲁图斯和卡西乌斯领导的元老院议员群体刺以23刀后遇刺身亡。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 尤利乌斯·凯撒。' }
        }
      },
      {
        id: 'romawi-colosseum',
        langs: {
          id: { title: 'Colosseum — Arena Raksasa Roma', desc: 'Amfiteater terbesar sepanjang masa yang menampung 80.000 penonton untuk pertarungan gladiator yang legendaris.', content: '<p class="mb-4">Colosseum (Flavian Amphitheatre) adalah amfiteater terbesar dalam sejarah manusia, dibangun antara 70–80 M di Roma. Mampu menampung 50.000–80.000 penonton, bangunan oval raksasa ini adalah puncak teknik konstruksi Romawi.</p><p class="mb-4">Di sini digelar pertarungan gladiator (munera), perburuan binatang buas (venationes), dan bahkan pertempuran laut buatan (naumachiae) dengan mengisi arena dengan air. Diperkirakan lebih dari 400.000 orang dan jutaan hewan mati di arena ini selama berabad-abad.</p><p class="mb-4">Meski rusak akibat gempa dan penjarahan, 2/3 bangunan asli masih berdiri. Colosseum kini menjadi monumen paling ikonik di dunia, dikunjungi 7 juta wisatawan per tahun.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Colosseum Roma.' },
          en: { title: 'The Colosseum — Rome\'s Giant Arena', desc: 'The largest amphitheater ever built, seating 80,000 spectators for legendary gladiatorial combat.', content: '<p class="mb-4">The Colosseum (Flavian Amphitheatre) is the largest amphitheater in human history, built between 70–80 CE in Rome. Capable of seating 50,000–80,000 spectators, this giant oval structure is the pinnacle of Roman construction engineering.</p><p class="mb-4">Here took place gladiatorial fights (munera), wild beast hunts (venationes), and even mock naval battles (naumachiae) by flooding the arena. Over 400,000 people and millions of animals are estimated to have died here over the centuries.</p><p class="mb-4">Though damaged by earthquakes and looting, 2/3 of the original structure still stands. The Colosseum is now the world\'s most iconic monument, visited by 7 million tourists per year.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Roman Colosseum.' },
          ja: { title: 'コロッセオ — ローマの巨大闘技場', desc: '伝説の剣闘士の戦いのために8万人の観客を収容した、史上最大の円形闘技場。', content: '<p class="mb-4">コロッセオ（フラウィウス円形闘技場）は70〜80年頃にローマに建設された人類史上最大の円形闘技場です。5万〜8万人の観客を収容でき、ローマ建設工学の粋を集めた建物です。</p><p class="mb-4">現在も元の構造の3分の2が残っており、年間700万人の観光客が訪れる世界最も象徴的な記念碑となっています。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — ローマのコロッセオ。' },
          ko: { title: '콜로세움 — 로마의 거대한 경기장', desc: '전설적인 검투사 싸움을 위해 8만 명의 관중을 수용한 역사상 가장 큰 원형 경기장.', content: '<p class="mb-4">콜로세움(플라비우스 원형 경기장)은 70~80년경 로마에 건설된 인류 역사상 가장 큰 원형 경기장입니다. 5만~8만 명의 관중을 수용할 수 있으며, 로마 건설 공학의 정점입니다.</p><p class="mb-4">원래 구조물의 2/3가 여전히 남아 있으며, 연간 700만 명의 관광객이 방문하는 세계에서 가장 상징적인 기념물이 되었습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 로마 콜로세움.' },
          zh: { title: '罗马斗兽场 — 罗马的巨型竞技场', desc: '有史以来最大的圆形剧场，可容纳8万名观众观看传奇的角斗士战斗。', content: '<p class="mb-4">斗兽场（弗拉维安圆形剧场）是人类历史上最大的圆形剧场，建于公元70-80年间。可容纳5-8万名观众，是罗马建筑工程的顶峰。</p><p class="mb-4">尽管因地震和掠夺受损，原始结构的2/3仍然矗立。斗兽场现在是世界上最具标志性的纪念碑，每年有700万游客参观。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 罗马斗兽场。' }
        }
      }
    ]
  };
