const countries = {
  'indonesia': {
    names: { id: 'Indonesia', en: 'Indonesia', ja: 'インドネシア', ko: '인도네시아', zh: '印度尼西亚' },
    flag: '🇮🇩',
    articles: [
      {
        id: 'indonesia-majapahit',
        langs: {
          id: { title: 'Kerajaan Majapahit', desc: 'Kerajaan Hindu-Buddha terbesar di Nusantara yang menyatukan hampir seluruh Asia Tenggara di bawah satu panji.', content: '<p class="mb-4">Majapahit (1293–1527 M) adalah puncak kejayaan peradaban Nusantara. Di bawah Raja Hayam Wuruk dan Mahapatih Gajah Mada, kerajaan ini menguasai wilayah dari Jawa, Sumatera, Kalimantan, Sulawesi, Bali, hingga sebagian Semenanjung Malaya dan Filipina.</p><p class="mb-4">Gajah Mada bersumpah lewat <strong>Sumpah Palapa</strong> untuk tidak menikmati rempah sebelum menyatukan Nusantara. Sumpah ini terbukti — hampir seluruh Nusantara berhasil dipersatukan.</p><p class="mb-4">Warisan terbesar Majapahit adalah semboyan <em>"Bhinneka Tunggal Ika"</em> dari Kitab Sutasoma yang kini menjadi semboyan resmi Negara Indonesia.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Kerajaan Majapahit.' },
          en: { title: 'Majapahit Empire', desc: 'The greatest Hindu-Buddhist kingdom in the archipelago that united almost all of Southeast Asia.', content: '<p class="mb-4">Majapahit (1293–1527 CE) was the pinnacle of Nusantara civilization. Under King Hayam Wuruk and Mahapatih Gajah Mada, it controlled Java, Sumatra, Borneo, Sulawesi, Bali, and parts of the Malay Peninsula.</p><p class="mb-4">Gajah Mada swore the <strong>Palapa Oath</strong> — vowing not to enjoy spices until the archipelago was united. He succeeded.</p><p class="mb-4">The greatest legacy is the motto <em>"Bhinneka Tunggal Ika"</em> (Unity in Diversity) which is now Indonesia\'s official state motto.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Majapahit Empire.' },
          ja: { title: 'マジャパヒト王国', desc: '東南アジアのほぼ全域を統一した、群島最大のヒンドゥー・仏教王国。', content: '<p class="mb-4">マジャパヒト（1293–1527年）はヌサンタラ文明の頂点でした。ハヤム・ウルク王とガジャ・マダ宰相の下、ジャワ、スマトラ、ボルネオ、スラウェシ、バリ、マレー半島の一部を支配しました。</p><p class="mb-4">国家標語「ビネカ・トゥンガル・イカ」（多様性の中の統一）はマジャパヒト時代のスタソマ書から生まれました。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — マジャパヒト王国。' },
          ko: { title: '마자파힛 제국', desc: '동남아시아 거의 전역을 통일한 군도 최대의 힌두-불교 왕국.', content: '<p class="mb-4">마자파힛(1293–1527년)은 누산타라 문명의 정점이었습니다. 하얌 우룩 왕과 가자 마다 재상 하에 자바, 수마트라, 보르네오, 술라웨시, 발리 및 말레이 반도 일부를 지배했습니다.</p><p class="mb-4">국가 표어 "비네카 퉁갈 이카"(다양성 속의 통일)는 마자파힛 시대에서 유래했습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — 마자파힛 제국.' },
          zh: { title: '满者伯夷帝国', desc: '统一了几乎整个东南亚的群岛最大的印度教-佛教王国。', content: '<p class="mb-4">满者伯夷（1293–1527年）是努山塔拉文明的顶峰。在哈雅姆·乌鲁克国王和加贾·马达宰相领导下，帝国控制了爪哇、苏门答腊、婆罗洲、苏拉威西、巴厘岛及马来半岛部分地区。</p><p class="mb-4">国家格言"比内卡·通加尔·伊卡"（多样性中的统一）来自满者伯夷时代。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — 满者伯夷帝国。' }
        }
      },
      {
        id: 'indonesia-proklamasi',
        langs: {
          id: { title: 'Proklamasi Kemerdekaan 1945', desc: 'Detik-detik bersejarah ketika Soekarno-Hatta memproklamasikan kemerdekaan Indonesia pada 17 Agustus 1945.', content: '<p class="mb-4">Pada Jumat, 17 Agustus 1945 pukul 10.00 WIB, Ir. Soekarno membacakan teks Proklamasi Kemerdekaan Indonesia di Jalan Pegangsaan Timur 56, Jakarta. Peristiwa ini menandai berakhirnya penjajahan 350 tahun Belanda dan 3,5 tahun Jepang.</p><p class="mb-4">Naskah proklamasi disusun semalam sebelumnya di rumah Laksamana Maeda setelah peristiwa Rengasdengklok. Teks singkat namun dahsyat ini diketik oleh Sayuti Melik.</p><p class="mb-4">Proklamasi ini kemudian disebarkan ke seluruh penjuru negeri melalui radio dan kurir, meski Belanda berusaha keras memblokir informasinya.</p>', sourceDomain: 'anri.go.id', sourceSnippet: 'Arsip Nasional RI — Proklamasi Kemerdekaan 1945.' },
          en: { title: 'Independence Proclamation 1945', desc: 'The historic moment when Sukarno-Hatta proclaimed Indonesian independence on August 17, 1945.', content: '<p class="mb-4">On Friday, August 17, 1945 at 10:00 AM local time, Ir. Sukarno read the Indonesian Independence Proclamation at Jalan Pegangsaan Timur 56, Jakarta. This event marked the end of 350 years of Dutch colonialism and 3.5 years of Japanese occupation.</p><p class="mb-4">The proclamation text was drafted the night before at Admiral Maeda\'s house after the Rengasdengklok Incident. The brief but powerful text was typed by Sayuti Melik.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Indonesian Independence Proclamation.' },
          ja: { title: '1945年独立宣言', desc: '1945年8月17日にスカルノ・ハッタがインドネシア独立を宣言した歴史的瞬間。', content: '<p class="mb-4">1945年8月17日金曜日午前10時、スカルノがジャカルタのプガンサアン・ティムル通り56番地でインドネシア独立宣言文を読み上げました。これにより350年のオランダ植民地支配と3.5年の日本占領が終わりを告げました。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia — インドネシア独立宣言。' },
          ko: { title: '1945년 독립 선언', desc: '1945년 8월 17일 수카르노-하타가 인도네시아 독립을 선언한 역사적 순간.', content: '<p class="mb-4">1945년 8월 17일 금요일 오전 10시, 수카르노가 자카르타 프강사안 티무르 56번지에서 독립 선언문을 낭독했습니다. 이로써 350년의 네덜란드 식민 지배와 3.5년의 일본 점령이 끝났습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia — 인도네시아 독립 선언.' },
          zh: { title: '1945年独立宣言', desc: '1945年8月17日苏加诺-哈达宣布印度尼西亚独立的历史性时刻。', content: '<p class="mb-4">1945年8月17日星期五上午10时，苏加诺在雅加达普甘萨安帝穆尔56号宣读了印度尼西亚独立宣言。这标志着350年荷兰殖民统治和3.5年日本占领的结束。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia — 印度尼西亚独立宣言。' }
        }
      },
      {
        id: 'indonesia-sriwijaya',
        langs: {
          id: { title: 'Kerajaan Sriwijaya', desc: 'Kerajaan maritim terbesar Asia Tenggara yang menguasai jalur perdagangan Selat Malaka selama 7 abad.', content: '<p class="mb-4">Sriwijaya (abad ke-7 hingga ke-13 M) adalah kekaisaran maritim yang berpusat di Palembang, Sumatera Selatan. Kerajaan ini menguasai Selat Malaka — jalur perdagangan tersibuk di Asia — dan memungut bea dari setiap kapal yang lewat.</p><p class="mb-4">Sriwijaya juga menjadi pusat pembelajaran agama Buddha terkemuka. Biksu Tiongkok I Tsing mencatat lebih dari 1.000 biksu belajar di sini pada abad ke-7.</p><p class="mb-4">Kerajaan ini melemah setelah serangan Kerajaan Chola dari India Selatan pada 1025 M dan akhirnya runtuh ditelan Majapahit.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Kerajaan Sriwijaya.' },
          en: { title: 'Srivijaya Empire', desc: 'The greatest maritime empire of Southeast Asia that controlled the Strait of Malacca trade routes for 7 centuries.', content: '<p class="mb-4">Srivijaya (7th–13th century CE) was a maritime empire centered in Palembang, South Sumatra. It controlled the Strait of Malacca — Asia\'s busiest trade route — collecting tolls from every passing ship.</p><p class="mb-4">Srivijaya was also a leading center of Buddhist learning. Chinese monk I Tsing recorded over 1,000 monks studying here in the 7th century.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Srivijaya Empire.' },
          ja: { title: 'スリヴィジャヤ帝国', desc: '7世紀にわたりマラッカ海峡の交易路を支配した東南アジア最大の海洋帝国。', content: '<p class="mb-4">スリヴィジャヤ（7世紀〜13世紀）は南スマトラのパレンバンを中心とした海洋帝国でした。アジア最大の貿易ルートであるマラッカ海峡を支配し、通過する船から通行料を徴収しました。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia — スリヴィジャヤ帝国。' },
          ko: { title: '스리비자야 제국', desc: '7세기 동안 말라카 해협 무역로를 지배한 동남아시아 최대의 해양 제국.', content: '<p class="mb-4">스리비자야(7세기~13세기)는 남부 수마트라 팔렘방을 중심으로 한 해양 제국이었습니다. 아시아에서 가장 바쁜 무역 루트인 말라카 해협을 지배하며 통과하는 모든 선박에서 통행료를 징수했습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia — 스리비자야 제국.' },
          zh: { title: '室利佛逝帝国', desc: '控制马六甲海峡贸易路线长达7个世纪的东南亚最大海洋帝国。', content: '<p class="mb-4">室利佛逝（7世纪至13世纪）是以南苏门答腊巨港为中心的海洋帝国。它控制着亚洲最繁忙的贸易路线——马六甲海峡，向每艘过往船只收取通行费。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia — 室利佛逝帝国。' }
        }
      }
    ]
  },

  'jepang': {
    names: { id: 'Jepang', en: 'Japan', ja: '日本', ko: '일본', zh: '日本' },
    flag: '🇯🇵',
    articles: [
      {
        id: 'jepang-samurai',
        langs: {
          id: { title: 'Era Samurai dan Keshogunan', desc: 'Masa kejayaan para ksatria samurai yang mendominasi politik dan budaya Jepang selama berabad-abad.', content: '<p class="mb-4">Samurai adalah kelas prajurit bangsawan yang mendominasi Jepang dari abad ke-12 hingga ke-19. Dipandu oleh kode etik <strong>Bushido</strong> (Jalan Ksatria), samurai menjunjung tinggi kesetiaan, kehormatan, dan kesiapan mati untuk tuan mereka.</p><p class="mb-4">Keshogunan Tokugawa (1603–1868) adalah puncak era samurai. Selama 265 tahun, Jepang ditutup dari dunia luar dalam kebijakan <em>Sakoku</em>. Negeri ini stabil namun terisolasi.</p><p class="mb-4">Era samurai berakhir dengan Restorasi Meiji 1868 ketika modernisasi Barat menggeser sistem feodal lama.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Samurai dan Keshogunan Jepang.' },
          en: { title: 'Samurai Era & Shogunate', desc: 'The golden age of samurai warriors who dominated Japanese politics and culture for centuries.', content: '<p class="mb-4">Samurai were the noble warrior class dominating Japan from the 12th to 19th centuries. Guided by <strong>Bushido</strong> (The Way of the Warrior), samurai upheld loyalty, honor, and readiness to die for their lord.</p><p class="mb-4">The Tokugawa Shogunate (1603–1868) was the peak of the samurai era. For 265 years, Japan was closed to the outside world under the <em>Sakoku</em> policy.</p><p class="mb-4">The samurai era ended with the 1868 Meiji Restoration when Western modernization replaced the old feudal system.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Japanese Samurai Era.' },
          ja: { title: '武士の時代と江戸幕府', desc: '何世紀にもわたって日本の政治と文化を支配した武士の黄金時代。', content: '<p class="mb-4">武士は12世紀から19世紀にかけて日本を支配した武士貴族階級でした。<strong>武士道</strong>（武士の道）に導かれ、忠誠心、名誉、主君のために死ぬ覚悟を重んじました。</p><p class="mb-4">徳川幕府（1603–1868）は武士の時代の頂点でした。265年間、<em>鎖国</em>政策により日本は外界から閉ざされていました。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia — 武士の時代。' },
          ko: { title: '사무라이 시대와 막부', desc: '수세기 동안 일본의 정치와 문화를 지배한 사무라이 전사들의 황금기.', content: '<p class="mb-4">사무라이는 12세기부터 19세기까지 일본을 지배한 귀족 전사 계급이었습니다. <strong>무사도</strong>(무사의 길)에 따라 충성, 명예, 주군을 위한 죽음의 준비를 중시했습니다.</p><p class="mb-4">도쿠가와 막부(1603–1868)는 사무라이 시대의 정점이었습니다. 265년 동안 <em>쇄국</em> 정책으로 일본은 외부 세계와 단절되었습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia — 사무라이 시대.' },
          zh: { title: '武士时代与幕府', desc: '武士战士主导日本政治和文化数百年的黄金时代。', content: '<p class="mb-4">武士是从12世纪到19世纪主导日本的贵族战士阶级。以<strong>武士道</strong>（武士之路）为指引，武士重视忠诚、荣誉和为主君牺牲的准备。</p><p class="mb-4">德川幕府（1603–1868）是武士时代的顶峰。265年间，日本在<em>锁国</em>政策下与外界隔绝。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia — 武士时代。' }
        }
      },
      {
        id: 'jepang-meiji',
        langs: {
          id: { title: 'Restorasi Meiji', desc: 'Transformasi revolusioner Jepang dari negara feodal menjadi kekuatan industri modern dalam waktu singkat.', content: '<p class="mb-4">Restorasi Meiji (1868) adalah revolusi dari atas yang mengubah Jepang dalam waktu luar biasa singkat. Ketika Komodor Perry dari Amerika membuka paksa pelabuhan Jepang (1853), Jepang sadar ketinggalan zaman.</p><p class="mb-4">Dalam 40 tahun, Jepang membangun angkatan laut modern, sistem perkeretaapian, universitas, industri baja, dan konstitusi bergaya Barat. Slogan <em>"Wakon Yosai"</em> (Semangat Jepang, Keahlian Barat) menjadi panduan modernisasi.</p><p class="mb-4">Hasilnya mengejutkan dunia: Jepang mengalahkan Tiongkok (1895) dan Rusia (1905) — pertama kalinya bangsa Asia mengalahkan kekuatan Eropa.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Encyclopaedia Britannica — Restorasi Meiji Jepang.' },
          en: { title: 'Meiji Restoration', desc: 'Japan\'s revolutionary transformation from a feudal state to a modern industrial power in a remarkably short time.', content: '<p class="mb-4">The Meiji Restoration (1868) was a revolution from above that transformed Japan in a remarkably short time. When Commodore Perry forced open Japanese ports (1853), Japan realized it was falling behind.</p><p class="mb-4">Within 40 years, Japan built a modern navy, railway system, universities, steel industry, and Western-style constitution. The slogan <em>"Wakon Yosai"</em> (Japanese Spirit, Western Skills) guided modernization.</p><p class="mb-4">The results shocked the world: Japan defeated China (1895) and Russia (1905) — the first time an Asian nation defeated a European power.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Meiji Restoration.' },
          ja: { title: '明治維新', desc: '封建国家から近代工業大国への日本の革命的変革。', content: '<p class="mb-4">明治維新（1868年）は、日本を驚くほど短期間で変革した上からの革命でした。ペリー提督が日本の港を強制開港（1853年）した時、日本は遅れを取っていることに気づきました。</p><p class="mb-4">40年以内に、日本は近代的な海軍、鉄道網、大学、鉄鋼産業、西洋式憲法を構築しました。<em>「和魂洋才」</em>というスローガンが近代化を導きました。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 明治維新。' },
          ko: { title: '메이지 유신', desc: '봉건 국가에서 근대 산업 강국으로의 일본의 혁명적 변혁.', content: '<p class="mb-4">메이지 유신(1868년)은 일본을 놀랍도록 짧은 시간에 변혁시킨 위로부터의 혁명이었습니다. 페리 제독이 일본 항구를 강제 개항(1853년)했을 때, 일본은 뒤처지고 있음을 깨달았습니다.</p><p class="mb-4">40년 만에 일본은 근대 해군, 철도망, 대학, 철강 산업, 서양식 헌법을 구축했습니다. <em>"화혼양재"</em> 슬로건이 근대화를 이끌었습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 메이지 유신.' },
          zh: { title: '明治维新', desc: '日本从封建国家到现代工业强国的革命性转变。', content: '<p class="mb-4">明治维新（1868年）是一场自上而下的革命，在极短时间内改变了日本。当佩里准将强行打开日本港口（1853年）时，日本意识到自己落后了。</p><p class="mb-4">40年内，日本建立了现代海军、铁路系统、大学、钢铁工业和西式宪法。<em>"和魂洋才"</em>的口号引导了现代化进程。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 明治维新。' }
        }
      },
      {
        id: 'jepang-hiroshima',
        langs: {
          id: { title: 'Bom Atom Hiroshima & Nagasaki', desc: 'Tragedi kemanusiaan terbesar dalam sejarah peperangan modern yang mengakhiri Perang Dunia II.', content: '<p class="mb-4">Pada 6 Agustus 1945, Amerika Serikat menjatuhkan bom atom pertama di Hiroshima, diikuti Nagasaki pada 9 Agustus 1945. Dalam sekejap, dua kota hancur lebur. Diperkirakan 129.000–226.000 jiwa meninggal.</p><p class="mb-4">Bom atom "Little Boy" (Hiroshima) dan "Fat Man" (Nagasaki) adalah senjata nuklir pertama yang digunakan dalam peperangan. Radiasi yang ditimbulkan terus membunuh selama bertahun-tahun setelahnya.</p><p class="mb-4">Jepang menyerah pada 15 Agustus 1945. Hiroshima kini menjadi simbol perdamaian dunia dengan Museum Perdamaian dan monumen Kubah Bom yang diakui UNESCO.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Pengeboman Atom Hiroshima dan Nagasaki.' },
          en: { title: 'Hiroshima & Nagasaki Atomic Bombs', desc: 'The greatest humanitarian tragedy in modern warfare history that ended World War II.', content: '<p class="mb-4">On August 6, 1945, the US dropped the first atomic bomb on Hiroshima, followed by Nagasaki on August 9. Two cities were instantly destroyed. An estimated 129,000–226,000 people died.</p><p class="mb-4">The "Little Boy" (Hiroshima) and "Fat Man" (Nagasaki) were the first nuclear weapons used in warfare. Radiation continued killing for years afterward.</p><p class="mb-4">Japan surrendered on August 15, 1945. Hiroshima is now a symbol of world peace with its Peace Museum and UNESCO-recognized A-Bomb Dome.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Hiroshima and Nagasaki Bombings.' },
          ja: { title: '広島・長崎への原爆投下', desc: '第二次世界大戦を終結させた現代戦争史上最大の人道的悲劇。', content: '<p class="mb-4">1945年8月6日、アメリカは広島に最初の原子爆弾を投下し、8月9日に長崎に続きました。2つの都市が瞬時に破壊され、推定12万9千〜22万6千人が死亡しました。</p><p class="mb-4">広島は今や、平和記念博物館とユネスコ認定の原爆ドームを持つ世界平和の象徴となっています。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 広島・長崎原爆。' },
          ko: { title: '히로시마 & 나가사키 원자폭탄', desc: '제2차 세계대전을 종식시킨 현대 전쟁사 최대의 인도주의적 비극.', content: '<p class="mb-4">1945년 8월 6일 미국이 히로시마에 첫 원자폭탄을 투하했고, 8월 9일 나가사키에 이어졌습니다. 두 도시가 순식간에 파괴되었고, 약 12만 9천~22만 6천 명이 사망했습니다.</p><p class="mb-4">히로시마는 이제 평화 기념관과 유네스코가 인정한 원폭 돔을 갖춘 세계 평화의 상징이 되었습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 히로시마 나가사키 원자폭탄.' },
          zh: { title: '广岛与长崎原子弹', desc: '结束第二次世界大战的现代战争史上最大的人道主义悲剧。', content: '<p class="mb-4">1945年8月6日，美国向广岛投下第一颗原子弹，8月9日又轰炸了长崎。两座城市瞬间被摧毁，估计有12.9万至22.6万人死亡。</p><p class="mb-4">广岛现在已成为世界和平的象征，拥有和平纪念馆和联合国教科文组织认定的原爆穹顶。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 广岛长崎原子弹。' }
        }
      }
    ]
  },

  'mesir': {
    names: { id: 'Mesir Kuno', en: 'Ancient Egypt', ja: '古代エジプト', ko: '고대 이집트', zh: '古埃及' },
    flag: '🇪🇬',
    articles: [
      {
        id: 'mesir-piramida',
        langs: {
          id: { title: 'Piramida Agung Giza', desc: 'Satu-satunya dari Tujuh Keajaiban Dunia Kuno yang masih berdiri, dibangun sekitar 2560 SM.', content: '<p class="mb-4">Piramida Agung Giza dibangun sebagai makam Firaun Khufu sekitar 2560 SM. Terdiri dari sekitar 2,3 juta blok batu dengan berat rata-rata 2,5 ton setiap bloknya. Tanpa mesin modern, ribuan pekerja membangunnya selama 20 tahun.</p><p class="mb-4">Tingginya mencapai 146,5 meter saat dibangun — menjadikannya bangunan tertinggi di dunia selama 3.800 tahun hingga Katedral Lincoln selesai pada 1311 M.</p><p class="mb-4">Hingga kini, cara persis pembangunan piramida masih menjadi misteri dan diperdebatkan para arkeolog dunia.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Encyclopaedia Britannica — Piramida Agung Giza.' },
          en: { title: 'Great Pyramid of Giza', desc: 'The only surviving Wonder of the Ancient World, built around 2560 BC.', content: '<p class="mb-4">The Great Pyramid of Giza was built as Pharaoh Khufu\'s tomb around 2560 BC. It consists of approximately 2.3 million stone blocks averaging 2.5 tons each. Without modern machinery, thousands of workers built it over 20 years.</p><p class="mb-4">At 146.5 meters tall when built, it was the world\'s tallest structure for 3,800 years until Lincoln Cathedral was completed in 1311 CE.</p><p class="mb-4">The exact method of pyramid construction remains a mystery debated by archaeologists worldwide.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Great Pyramid of Giza.' },
          ja: { title: 'ギザの大ピラミッド', desc: '紀元前2560年頃に建設された、古代世界の七不思議のうち現存する唯一のもの。', content: '<p class="mb-4">ギザの大ピラミッドは紀元前2560年頃にファラオ・クフの墓として建設されました。平均2.5トンの石块约230万個で構成されています。近代的な機械なしに、数千人の労働者が20年かけて建設しました。</p><p class="mb-4">建設時の高さは146.5メートルで、1311年にリンカーン大聖堂が完成するまで3,800年間、世界最高の建造物でした。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — ギザの大ピラミッド。' },
          ko: { title: '기자의 대피라미드', desc: '기원전 2560년경에 건설된 고대 세계 7대 불가사의 중 유일하게 남아있는 것.', content: '<p class="mb-4">기자의 대피라미드는 기원전 2560년경 파라오 쿠푸의 무덤으로 건설되었습니다. 평균 2.5톤의 돌블록 약 230만 개로 구성되어 있습니다. 현대 기계 없이 수천 명의 노동자가 20년에 걸쳐 건설했습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 기자의 대피라미드.' },
          zh: { title: '吉萨大金字塔', desc: '建于约公元前2560年，古代世界七大奇迹中唯一幸存的建筑。', content: '<p class="mb-4">吉萨大金字塔建于约公元前2560年，作为法老胡夫的陵墓。由约230万块平均重2.5吨的石块组成。没有现代机械，数千名工人花了20年建造。</p><p class="mb-4">建造时高146.5米，是世界最高建筑，直到1311年林肯大教堂完工，这一纪录保持了3800年。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 吉萨大金字塔。' }
        }
      },
      {
        id: 'mesir-firaun',
        langs: {
          id: { title: 'Para Firaun Legendaris', desc: 'Kisah Ramses II, Tutankhamun, dan Cleopatra — para penguasa Mesir yang namanya abadi dalam sejarah.', content: '<p class="mb-4"><strong>Ramses II</strong> (1279–1213 SM) adalah firaun terbesar Mesir, memerintah selama 66 tahun. Ia membangun lebih banyak monumen dari firaun manapun, termasuk kuil megah Abu Simbel. Dikenal sebagai "Ramses Agung."</p><p class="mb-4"><strong>Tutankhamun</strong> menjadi firaun usia 9 tahun dan meninggal usia 18. Namun penemuannya menjadi fenomenal — pada 1922, Howard Carter menemukan makamnya yang utuh dengan harta karun senilai miliaran dolar.</p><p class="mb-4"><strong>Cleopatra VII</strong> adalah firaun terakhir Mesir — cerdas, fasih 9 bahasa, dan punya hubungan romantis dengan Julius Caesar dan Mark Antony sebelum Mesir jatuh ke tangan Romawi.</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — Para Firaun Legendaris Mesir Kuno.' },
          en: { title: 'Legendary Pharaohs', desc: 'The stories of Ramses II, Tutankhamun, and Cleopatra — Egyptian rulers whose names are immortalized in history.', content: '<p class="mb-4"><strong>Ramses II</strong> (1279–1213 BC) was Egypt\'s greatest pharaoh, ruling for 66 years. He built more monuments than any other pharaoh, including the magnificent Abu Simbel temple.</p><p class="mb-4"><strong>Tutankhamun</strong> became pharaoh at age 9 and died at 18. But his discovery was phenomenal — in 1922, Howard Carter found his intact tomb with billions worth of treasures.</p><p class="mb-4"><strong>Cleopatra VII</strong> was Egypt\'s last pharaoh — brilliant, fluent in 9 languages, with romantic ties to Julius Caesar and Mark Antony before Egypt fell to Rome.</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — Legendary Pharaohs of Ancient Egypt.' },
          ja: { title: '伝説のファラオたち', desc: 'ラムセス2世、ツタンカーメン、クレオパトラ — 歴史に名を刻んだエジプトの支配者たち。', content: '<p class="mb-4"><strong>ラムセス2世</strong>（紀元前1279–1213年）は66年間統治したエジプト最大のファラオで、アブ・シンベル神殿を含む多くの記念碑を建設しました。</p><p class="mb-4"><strong>ツタンカーメン</strong>は9歳でファラオになり18歳で死亡しましたが、1922年のハワード・カーターによる彼の無傷の墓の発見は世界的な現象となりました。</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — 古代エジプトの伝説のファラオ。' },
          ko: { title: '전설적인 파라오들', desc: '람세스 2세, 투탕카멘, 클레오파트라 — 역사에 이름을 새긴 이집트의 통치자들.', content: '<p class="mb-4"><strong>람세스 2세</strong>(기원전 1279–1213년)는 66년간 통치한 이집트 최대의 파라오로, 아부 심벨 신전을 포함한 수많은 기념물을 건설했습니다.</p><p class="mb-4"><strong>투탕카멘</strong>은 9세에 파라오가 되어 18세에 사망했지만, 1922년 하워드 카터의 무덤 발견은 세계적인 현상이 되었습니다.</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — 고대 이집트의 전설적인 파라오들.' },
          zh: { title: '传奇法老们', desc: '拉美西斯二世、图坦卡蒙和克利奥帕特拉——在历史上留下永恒印记的埃及统治者。', content: '<p class="mb-4"><strong>拉美西斯二世</strong>（公元前1279–1213年）是统治了66年的埃及最伟大法老，建造了包括阿布辛拜勒神庙在内的众多纪念碑。</p><p class="mb-4"><strong>图坦卡蒙</strong>9岁登基，18岁去世，但1922年霍华德·卡特发现其完整陵墓成为世界现象。</p><p class="mb-4"><strong>克利奥帕特拉七世</strong>是埃及最后一位法老——才华横溢，精通9种语言，与凯撒和安东尼有过浪漫关系，直到埃及落入罗马人之手。</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — 古埃及传奇法老。' }
        }
      },
      {
        id: 'mesir-hieroglif',
        langs: {
          id: { title: 'Hieroglif — Tulisan Suci Mesir', desc: 'Sistem tulisan piktografis yang digunakan selama 3.500 tahun dan menjadi kunci memahami peradaban Mesir Kuno.', content: '<p class="mb-4">Hieroglif (dari bahasa Yunani: "tulisan suci") adalah sistem tulisan bergambar yang dikembangkan Mesir sekitar 3200 SM. Terdiri dari lebih dari 700 tanda yang mewakili suara, kata, atau konsep.</p><p class="mb-4">Selama berabad-abad hieroglif menjadi misteri yang tak terpecahkan — hingga penemuan <strong>Batu Rosetta</strong> pada 1799. Batu ini memuat teks yang sama dalam tiga bahasa: hieroglif, demotik, dan Yunani kuno.</p><p class="mb-4">Thomas Young dan Jean-François Champollion berhasil menguraikan hieroglif pada 1822, membuka kembali jendela menuju peradaban Mesir kuno yang kaya.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Hieroglif Mesir Kuno dan Batu Rosetta.' },
          en: { title: 'Hieroglyphs — Sacred Egyptian Writing', desc: 'The pictographic writing system used for 3,500 years that became the key to understanding Ancient Egyptian civilization.', content: '<p class="mb-4">Hieroglyphs (from Greek: "sacred writing") are Egypt\'s pictographic writing system developed around 3200 BC. They consist of over 700 signs representing sounds, words, or concepts.</p><p class="mb-4">For centuries, hieroglyphs remained an unsolved mystery — until the discovery of the <strong>Rosetta Stone</strong> in 1799. This stone contains the same text in three scripts: hieroglyphic, demotic, and ancient Greek.</p><p class="mb-4">Thomas Young and Jean-François Champollion successfully deciphered hieroglyphs in 1822, reopening the window to rich ancient Egyptian civilization.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Egyptian Hieroglyphs and Rosetta Stone.' },
          ja: { title: 'ヒエログリフ — エジプトの神聖文字', desc: '3500年間使用され、古代エジプト文明を理解する鍵となった象形文字体系。', content: '<p class="mb-4">ヒエログリフ（ギリシャ語で「神聖な文字」）は紀元前3200年頃に発展したエジプトの象形文字体系です。音、言葉、概念を表す700以上の記号で構成されています。</p><p class="mb-4">1799年のロゼッタ・ストーンの発見まで、ヒエログリフは解読不能な謎でした。1822年にシャンポリオンが解読に成功しました。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — エジプトのヒエログリフ。' },
          ko: { title: '상형문자 — 이집트의 신성한 글자', desc: '3500년간 사용되어 고대 이집트 문명 이해의 열쇠가 된 상형 문자 체계.', content: '<p class="mb-4">상형문자(그리스어로 "신성한 글자")는 기원전 3200년경에 발전한 이집트의 그림문자 체계입니다. 소리, 단어, 개념을 나타내는 700개 이상의 기호로 구성됩니다.</p><p class="mb-4">1799년 로제타석 발견까지 상형문자는 풀리지 않는 수수께끼였습니다. 1822년 샹폴리옹이 해독에 성공했습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 이집트 상형문자.' },
          zh: { title: '象形文字——埃及神圣的书写', desc: '使用了3500年，成为理解古埃及文明关键的象形文字体系。', content: '<p class="mb-4">象形文字（希腊语意为"神圣的书写"）是约公元前3200年发展起来的埃及图形文字体系，由700多个代表声音、词语或概念的符号组成。</p><p class="mb-4">几个世纪来，象形文字是个未解之谜，直到1799年发现罗塞塔石碑。1822年商博良成功解读了象形文字。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 埃及象形文字。' }
        }
      }
    ]
  },

  'romawi': {
    names: { id: 'Romawi Kuno', en: 'Ancient Rome', ja: '古代ローマ', ko: '고대 로마', zh: '古罗马' },
    flag: '🏛️',
    articles: [
      {
        id: 'romawi-julius-caesar',
        langs: {
          id: { title: 'Julius Caesar', desc: 'Jenderal dan diktator Roma yang mengubah Republik menjadi cikal bakal Kekaisaran dan namanya abadi sepanjang masa.', content: '<p class="mb-4">Gaius Julius Caesar (100–44 SM) adalah sosok paling berpengaruh dalam sejarah Roma. Jenderal brilian yang menaklukkan Galia (Prancis modern) dalam 8 tahun, ia juga penulis, orator, dan politisi kelas dunia.</p><p class="mb-4">Ketika Caesar menyeberangi Sungai Rubicon (49 SM) dengan pasukannya — melanggar hukum Roma — ia memulai perang saudara melawan Pompey dan Senat. Ia menang dan menjadi diktator Roma.</p><p class="mb-4">Pada 15 Maret 44 SM (Ides of March), Caesar dibunuh oleh 23 tusukan dari sekelompok senator yang dipimpin Brutus dan Cassius. Kematiannya justru mengakhiri Republik dan melahirkan Kekaisaran Romawi.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Encyclopaedia Britannica — Julius Caesar.' },
          en: { title: 'Julius Caesar', desc: 'Rome\'s general and dictator who transformed the Republic into the precursor of the Empire — his name immortalized forever.', content: '<p class="mb-4">Gaius Julius Caesar (100–44 BC) was the most influential figure in Roman history. A brilliant general who conquered Gaul (modern France) in 8 years, he was also a world-class writer, orator, and politician.</p><p class="mb-4">When Caesar crossed the Rubicon River (49 BC) with his army — violating Roman law — he started a civil war against Pompey and the Senate. He won and became Rome\'s dictator.</p><p class="mb-4">On March 15, 44 BC (the Ides of March), Caesar was assassinated with 23 stab wounds by a group of senators led by Brutus and Cassius. His death paradoxically ended the Republic and birthed the Roman Empire.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Julius Caesar.' },
          ja: { title: 'ユリウス・カエサル', desc: '共和国を帝国の前身に変えたローマの将軍と独裁者。', content: '<p class="mb-4">ガイウス・ユリウス・カエサル（紀元前100–44年）はローマ史上最も影響力のある人物でした。8年でガリア（現代のフランス）を征服した天才的な将軍であり、世界クラスの作家、雄弁家、政治家でもありました。</p><p class="mb-4">紀元前44年3月15日（イードゥス・マルティアエ）、ブルートゥスとカッシウスが率いる元老院議員グループによって23カ所を刺されて暗殺されました。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — ユリウス・カエサル。' },
          ko: { title: '율리우스 카이사르', desc: '공화국을 제국의 전신으로 변모시킨 로마의 장군이자 독재자.', content: '<p class="mb-4">가이우스 율리우스 카이사르(기원전 100–44년)는 로마 역사에서 가장 영향력 있는 인물이었습니다. 8년 만에 갈리아(현대 프랑스)를 정복한 천재적인 장군이자 세계적인 작가, 연설가, 정치가였습니다.</p><p class="mb-4">기원전 44년 3월 15일(이두스 마르티아이), 브루투스와 카시우스가 이끄는 원로원 의원 그룹에 의해 23번 찔려 암살되었습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 율리우스 카이사르.' },
          zh: { title: '尤利乌斯·凯撒', desc: '将共和国转变为帝国前身的罗马将军和独裁者。', content: '<p class="mb-4">盖乌斯·尤利乌斯·凯撒（公元前100–44年）是罗马历史上最具影响力的人物。他是一位天才将军，在8年内征服了高卢（现代法国），同时也是世界级的作家、演说家和政治家。</p><p class="mb-4">公元前44年3月15日（三月望日），凯撒被布鲁图斯和卡西乌斯领导的元老院议员群体刺以23刀后遇刺身亡。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 尤利乌斯·凯撒。' }
        }
      },
      {
        id: 'romawi-colosseum',
        langs: {
          id: { title: 'Colosseum — Arena Raksasa Roma', desc: 'Amfiteater terbesar sepanjang masa yang menampung 80.000 penonton untuk pertarungan gladiator yang legendaris.', content: '<p class="mb-4">Colosseum (Flavian Amphitheatre) adalah amfiteater terbesar dalam sejarah manusia, dibangun antara 70–80 M di Roma. Mampu menampung 50.000–80.000 penonton, bangunan oval raksasa ini adalah puncak teknik konstruksi Romawi.</p><p class="mb-4">Di sini digelar pertarungan gladiator (munera), perburuan binatang buas (venationes), dan bahkan pertempuran laut buatan (naumachiae) dengan mengisi arena dengan air. Diperkirakan lebih dari 400.000 orang dan jutaan hewan mati di arena ini selama berabad-abad.</p><p class="mb-4">Meski rusak akibat gempa dan penjarahan, 2/3 bangunan asli masih berdiri. Colosseum kini menjadi monumen paling ikonik di dunia, dikunjungi 7 juta wisatawan per tahun.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Colosseum Roma.' },
          en: { title: 'The Colosseum — Rome\'s Giant Arena', desc: 'The largest amphitheater ever built, seating 80,000 spectators for legendary gladiatorial combat.', content: '<p class="mb-4">The Colosseum (Flavian Amphitheatre) is the largest amphitheater in human history, built between 70–80 CE in Rome. Capable of seating 50,000–80,000 spectators, this giant oval structure is the pinnacle of Roman construction engineering.</p><p class="mb-4">Here took place gladiatorial fights (munera), wild beast hunts (venationes), and even mock naval battles (naumachiae) by flooding the arena. Over 400,000 people and millions of animals are estimated to have died here over the centuries.</p><p class="mb-4">Though damaged by earthquakes and looting, 2/3 of the original structure still stands. The Colosseum is now the world\'s most iconic monument, visited by 7 million tourists per year.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Roman Colosseum.' },
          ja: { title: 'コロッセオ — ローマの巨大闘技場', desc: '伝説の剣闘士の戦いのために8万人の観客を収容した、史上最大の円形闘技場。', content: '<p class="mb-4">コロッセオ（フラウィウス円形闘技場）は70〜80年頃にローマに建設された人類史上最大の円形闘技場です。5万〜8万人の観客を収容でき、ローマ建設工学の粋を集めた建物です。</p><p class="mb-4">現在も元の構造の3分の2が残っており、年間700万人の観光客が訪れる世界最も象徴的な記念碑となっています。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — ローマのコロッセオ。' },
          ko: { title: '콜로세움 — 로마의 거대한 경기장', desc: '전설적인 검투사 싸움을 위해 8만 명의 관중을 수용한 역사상 가장 큰 원형 경기장.', content: '<p class="mb-4">콜로세움(플라비우스 원형 경기장)은 70~80년경 로마에 건설된 인류 역사상 가장 큰 원형 경기장입니다. 5만~8만 명의 관중을 수용할 수 있으며, 로마 건설 공학의 정점입니다.</p><p class="mb-4">원래 구조물의 2/3가 여전히 남아 있으며, 연간 700만 명의 관광객이 방문하는 세계에서 가장 상징적인 기념물이 되었습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 로마 콜로세움.' },
          zh: { title: '罗马斗兽场 — 罗马的巨型竞技场', desc: '有史以来最大的圆形剧场，可容纳8万名观众观看传奇的角斗士战斗。', content: '<p class="mb-4">斗兽场（弗拉维安圆形剧场）是人类历史上最大的圆形剧场，建于公元70-80年间。可容纳5-8万名观众，是罗马建筑工程的顶峰。</p><p class="mb-4">尽管因地震和掠夺受损，原始结构的2/3仍然矗立。斗兽场现在是世界上最具标志性的纪念碑，每年有700万游客参观。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 罗马斗兽场。' }
        }
      }
    ]
  },

  'tiongkok': {
    names: { id: 'Tiongkok', en: 'China', ja: '中国', ko: '중국', zh: '中国' },
    flag: '🇨🇳',
    articles: [
      {
        id: 'tiongkok-tembok',
        langs: {
          id: { title: 'Tembok Besar Tiongkok', desc: 'Salah satu proyek konstruksi terbesar dalam sejarah manusia, dibangun selama lebih dari 2.000 tahun untuk melindungi dari invasi utara.', content: '<p class="mb-4">Tembok Besar Tiongkok adalah serangkaian tembok dan benteng yang dibangun di seluruh wilayah utara Tiongkok. Pembangunan dimulai sejak abad ke-7 SM dan berlanjut hingga Dinasti Ming (1368–1644 M).</p><p class="mb-4">Panjang totalnya mencapai lebih dari 21.000 km — cukup untuk mengelilingi Bumi setengah kali. Dibangun oleh jutaan pekerja paksa, termasuk tentara, petani, dan tahanan. Diperkirakan ratusan ribu pekerja meninggal saat pembangunan dan dimakamkan di dalam tembok.</p><p class="mb-4">UNESCO menetapkan Tembok Besar sebagai Warisan Dunia pada 1987. Meski mitos "terlihat dari luar angkasa" tidak benar, Tembok Besar tetap menjadi simbol ketekunan dan kekuatan peradaban Tiongkok.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Tembok Besar Tiongkok.' },
          en: { title: 'Great Wall of China', desc: 'One of the largest construction projects in human history, built over 2,000 years to protect against northern invasions.', content: '<p class="mb-4">The Great Wall of China is a series of walls and fortifications built across northern China. Construction started in the 7th century BC and continued through the Ming Dynasty (1368–1644 CE).</p><p class="mb-4">Its total length exceeds 21,000 km — enough to wrap around Earth half a time. Built by millions of forced laborers including soldiers, farmers, and prisoners. Hundreds of thousands are estimated to have died and been buried within the wall.</p><p class="mb-4">UNESCO designated the Great Wall a World Heritage Site in 1987. Though the myth of seeing it from space is untrue, it remains a symbol of Chinese civilization\'s perseverance and strength.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Great Wall of China.' },
          ja: { title: '万里の長城', desc: '北方からの侵略を防ぐために2000年以上かけて建設された、人類史上最大の建設プロジェクトの一つ。', content: '<p class="mb-4">万里の長城は中国北部に建設された一連の城壁と要塞です。建設は紀元前7世紀に始まり、明朝（1368–1644年）まで続きました。</p><p class="mb-4">総延長は21,000km以上に及び、地球を半周できる長さです。ユネスコは1987年に世界遺産に指定しました。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 万里の長城。' },
          ko: { title: '만리장성', desc: '북방 침략으로부터 보호하기 위해 2000년 이상에 걸쳐 건설된 인류 역사상 가장 큰 건설 프로젝트 중 하나.', content: '<p class="mb-4">만리장성은 중국 북부에 건설된 일련의 성벽과 요새입니다. 건설은 기원전 7세기에 시작되어 명나라(1368–1644년)까지 계속되었습니다.</p><p class="mb-4">총 길이는 21,000km를 초과하며, 지구를 반 바퀴 돌 수 있는 길이입니다. 유네스코는 1987년 세계문화유산으로 지정했습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 만리장성.' },
          zh: { title: '万里长城', desc: '为抵御北方入侵而历时2000多年建造的人类历史上最大的建设工程之一。', content: '<p class="mb-4">万里长城是建于中国北部的一系列城墙和要塞。建设从公元前7世纪开始，一直持续到明朝（1368–1644年）。</p><p class="mb-4">其总长度超过21,000公里，足以绕地球半圈。联合国教科文组织于1987年将其列为世界遗产。尽管从太空看见长城的说法是神话，但它仍然是中华文明坚韧与力量的象征。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 万里长城。' }
        }
      },
      {
        id: 'tiongkok-dinasti-tang',
        langs: {
          id: { title: 'Dinasti Tang — Zaman Keemasan', desc: 'Era paling gemilang Tiongkok dalam seni, sastra, teknologi, dan perdagangan internasional (618–907 M).', content: '<p class="mb-4">Dinasti Tang (618–907 M) dianggap sebagai zaman keemasan peradaban Tiongkok. Ibu kotanya, Chang\'an (kini Xi\'an), adalah kota terbesar dan paling kosmopolit di dunia dengan populasi lebih dari 1 juta jiwa — pusat Jalur Sutra yang ramai.</p><p class="mb-4">Di era Tang, puisi Tiongkok mencapai puncaknya. Li Bai dan Du Fu adalah dua penyair terbesar yang karya-karyanya masih dipelajari hingga kini. Percetakan blok kayu juga pertama kali berkembang di era ini.</p><p class="mb-4">Tang juga dikenal toleran secara agama — Islam, Kristen Nestorian, Zoroastrianisme, dan Buddha berkembang berdampingan di Chang\'an. Wanita di era Tang menikmati kebebasan yang luar biasa untuk zamannya.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Dinasti Tang Tiongkok.' },
          en: { title: 'Tang Dynasty — The Golden Age', desc: 'China\'s most glorious era in arts, literature, technology, and international trade (618–907 CE).', content: '<p class="mb-4">The Tang Dynasty (618–907 CE) is considered the golden age of Chinese civilization. Its capital Chang\'an (now Xi\'an) was the world\'s largest and most cosmopolitan city with a population over 1 million — the bustling center of the Silk Road.</p><p class="mb-4">In the Tang era, Chinese poetry reached its peak. Li Bai and Du Fu are the two greatest poets whose works are still studied today. Block printing also first developed in this era.</p><p class="mb-4">Tang was also religiously tolerant — Islam, Nestorian Christianity, Zoroastrianism, and Buddhism flourished together in Chang\'an.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Tang Dynasty China.' },
          ja: { title: '唐朝 — 黄金時代', desc: '芸術、文学、技術、国際貿易における中国最も輝かしい時代（618–907年）。', content: '<p class="mb-4">唐朝（618–907年）は中国文明の黄金時代とされています。首都の長安（現在の西安）は人口100万人以上を擁する世界最大かつ最も国際色豊かな都市で、シルクロードの中心でした。</p><p class="mb-4">唐代には中国詩が頂点に達しました。李白と杜甫は現在も学ばれる最大の詩人です。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 唐朝。' },
          ko: { title: '당나라 — 황금 시대', desc: '예술, 문학, 기술 및 국제 무역에서 중국의 가장 찬란한 시대(618–907년).', content: '<p class="mb-4">당나라(618–907년)는 중국 문명의 황금시대로 여겨집니다. 수도 장안(현재의 시안)은 인구 100만 명 이상의 세계 최대의 국제적인 도시로 실크로드의 중심지였습니다.</p><p class="mb-4">당나라 시대에 중국 시가 정점에 달했습니다. 이백과 두보는 오늘날까지 연구되는 최대의 시인입니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 당나라.' },
          zh: { title: '唐朝 — 黄金时代', desc: '中国在艺术、文学、技术和国际贸易方面最辉煌的时代（618–907年）。', content: '<p class="mb-4">唐朝（618–907年）被认为是中华文明的黄金时代。其首都长安（今西安）是世界上最大、最具国际性的城市，人口超过100万，是丝绸之路的繁荣中心。</p><p class="mb-4">唐代中国诗歌达到顶峰。李白和杜甫是至今仍被研究的两位最伟大的诗人。雕版印刷也在这一时代首次发展起来。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 唐朝。' }
        }
      }
    ]
  },
  'india': {
    names: { id: 'India', en: 'India', ja: 'インド', ko: '인도', zh: '印度' },
    flag: '🇮🇳',
    articles: [
      {
        id: 'india-maurya',
        langs: {
          id: { title: 'Kekaisaran Maurya', desc: 'Kekaisaran pertama yang menyatukan hampir seluruh anak benua India, dipimpin Chandragupta Maurya pada 321 SM.', content: '<p class="mb-4">Kekaisaran Maurya (321-185 SM) didirikan oleh Chandragupta Maurya dengan bantuan penasihat Chanakya. Kaisar Ashoka (268-232 SM) memeluk Buddhisme setelah Pertempuran Kalinga yang menewaskan 100.000 orang. Ia menyebarkan ajaran Buddha ke seluruh Asia. Singa pada pilar Ashoka kini menjadi lambang negara India modern.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Maurya Empire.' },
          en: { title: 'Maurya Empire', desc: 'The first empire to unify most of the Indian subcontinent, founded by Chandragupta Maurya in 321 BCE.', content: '<p class="mb-4">The Maurya Empire (321-185 BCE) was founded by Chandragupta Maurya with advisor Chanakya, stretching from Afghanistan to Bengal. Emperor Ashoka (268-232 BCE) converted to Buddhism after the bloody Battle of Kalinga and spread it across Asia through diplomatic missions. The Ashoka lion capital is now India's national emblem.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Maurya Empire.' },
          ja: { title: 'マウリヤ朝', desc: '紀元前321年創設のインド亜大陸をほぼ統一した最初の帝国。', content: '<p class="mb-4">マウリヤ朝（紀元前321-185年）はチャンドラグプタ・マウリヤが創設。アショーカ王（紀元前268-232年）がカリンガの戦い後に仏教へ改宗しアジア全土に仏教を広めました。アショーカの獅子柱頭は現在のインドの国章です。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Maurya Empire.' },
          ko: { title: '마우리아 제국', desc: '기원전 321년 찬드라굽타 마우리아가 창건한 인도 아대륙을 거의 통일한 최초의 제국.', content: '<p class="mb-4">마우리아 제국(기원전 321-185년)은 찬드라굽타 마우리아가 창건했습니다. 아소카 왕(기원전 268-232년)이 칼링가 전투 후 불교로 개종하고 아시아 전역에 불교를 전파했습니다. 아소카의 사자 주두는 현재 인도의 국장입니다.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Maurya Empire.' },
          zh: { title: '孔雀帝国', desc: '公元前321年创建的统一印度次大陆的第一个帝国。', content: '<p class="mb-4">孔雀帝国（公元前321-185年）由旃陀罗笈多·孔雀创建。阿育王（公元前268-232年）在卡林伽战役后皈依佛教，向全亚洲传播佛教。阿育王的狮子柱头成为现代印度的国徽。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Maurya Empire.' }
        }
      },
      {
        id: 'india-taj-mahal',
        langs: {
          id: { title: 'Taj Mahal — Monumen Cinta Agung', desc: 'Mahakarya arsitektur Mughal yang dibangun Shah Jahan untuk mengenang istrinya Mumtaz Mahal, kini Keajaiban Dunia.', content: '<p class="mb-4">Taj Mahal dibangun 1632-1653 oleh Kaisar Mughal Shah Jahan sebagai makam istrinya Mumtaz Mahal yang meninggal saat melahirkan. Lebih dari 20.000 pekerja menghabiskan 21 tahun membangunnya dari marmer putih murni. UNESCO World Heritage 1983 dan Keajaiban Dunia Baru 2007. Dikunjungi 7-8 juta wisatawan per tahun.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Taj Mahal.' },
          en: { title: 'Taj Mahal — Monument of Supreme Love', desc: 'The Mughal masterpiece built by Shah Jahan for his wife Mumtaz Mahal, now a Wonder of the World.', content: '<p class="mb-4">The Taj Mahal was built 1632-1653 by Emperor Shah Jahan as a mausoleum for his beloved wife Mumtaz Mahal, who died in childbirth. Over 20,000 workers labored 21 years using pure white marble inlaid with semi-precious stones worldwide. UNESCO World Heritage since 1983 and New Seven Wonders of the World since 2007. Visited by 7-8 million tourists annually.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Taj Mahal.' },
          ja: { title: 'タージ・マハル', desc: 'シャー・ジャハーンが妻のために建てたムガル建築の傑作。世界七不思議の一つ。', content: '<p class="mb-4">タージ・マハルは1632-1653年に皇帝シャー・ジャハーンが出産で亡くなった愛妻ムムターズ・マハルの廟として建設。2万人以上の職人が21年かけ純白の大理石で完成させました。1983年ユネスコ世界遺産、2007年世界七不思議に選定。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Taj Mahal.' },
          ko: { title: '타지마할', desc: '샤 자한이 아내를 위해 건설한 무굴 건축의 걸작. 세계 7대 불가사의 중 하나.', content: '<p class="mb-4">타지마할은 1632-1653년 황제 샤 자한이 출산 중 사망한 사랑하는 아내 뭄타즈 마할의 영묘로 건설했습니다. 2만여 명의 장인이 21년에 걸쳐 순백의 대리석으로 완성했습니다. 1983년 유네스코 세계문화유산, 2007년 세계 7대 불가사의로 선정되었습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Taj Mahal.' },
          zh: { title: '泰姬陵', desc: '沙贾汗为妻子建造的莫卧儿建筑杰作，世界七大奇迹之一。', content: '<p class="mb-4">泰姬陵建于1632-1653年，是沙贾汗为生育中去世的爱妻穆姆塔兹·马哈尔所建的陵墓。超过2万名工匠耗时21年用纯白大理石完成。1983年列为联合国教科文组织世界遗产，2007年入选世界新七大奇迹。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Taj Mahal.' }
        }
      },
      {
        id: 'india-gandhi',
        langs: {
          id: { title: 'Mahatma Gandhi dan Kemerdekaan India', desc: 'Gandhi memimpin perlawanan tanpa kekerasan yang mengakhiri 200 tahun penjajahan Inggris di India.', content: '<p class="mb-4">Mahatma Gandhi (1869-1948) mengembangkan Satyagraha — perlawanan tanpa kekerasan. Maret Garam 1930 (berjalan 388 km ke pantai) menjadi aksi paling ikonik melawan pajak garam kolonial Inggris. India merdeka 15 Agustus 1947. Gandhi dibunuh 30 Januari 1948. Metodenya menginspirasi Martin Luther King Jr. dan Nelson Mandela.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Mahatma Gandhi.' },
          en: { title: 'Mahatma Gandhi and Indian Independence', desc: 'Gandhi led nonviolent resistance that ended 200 years of British colonial rule in India.', content: '<p class="mb-4">Mahatma Gandhi (1869-1948) developed Satyagraha — nonviolent resistance. The 1930 Salt March (388 km walk to the sea) was his most iconic act against British colonial salt tax, triggering mass civil disobedience. India gained independence on August 15, 1947. Gandhi was assassinated on January 30, 1948. His methods inspired Martin Luther King Jr. and Nelson Mandela.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Gandhi.' },
          ja: { title: 'マハトマ・ガンジーとインド独立', desc: 'ガンジーが非暴力抵抗でインドの200年の植民地支配を終わらせた。', content: '<p class="mb-4">マハトマ・ガンジー（1869-1948）はサティヤーグラハ（非暴力抵抗）を開発。1930年の塩の行進（388km徒歩）で世界的注目を集めました。インドは1947年8月15日に独立。ガンジーは1948年1月30日に暗殺。キング牧師やマンデラに影響を与えました。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Gandhi.' },
          ko: { title: '마하트마 간디와 인도 독립', desc: '간디가 비폭력 저항으로 200년의 영국 식민지 지배를 종식시켰다.', content: '<p class="mb-4">마하트마 간디(1869-1948)는 사티아그라하(비폭력 저항)를 개발했습니다. 1930년 소금 행진(388km 도보)이 세계적 주목을 받았습니다. 인도는 1947년 8월 15일 독립했습니다. 간디는 1948년 1월 30일 암살되었으며 마틴 루서 킹과 만델라에게 영향을 주었습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Gandhi.' },
          zh: { title: '圣雄甘地与印度独立', desc: '甘地通过非暴力抵抗结束了200年英国殖民统治。', content: '<p class="mb-4">圣雄甘地（1869-1948年）发展了"坚持真理"非暴力抵抗方法。1930年食盐长征（步行388公里）引发全球关注。印度于1947年8月15日独立。甘地于1948年1月30日遇刺。他的方法影响了马丁·路德·金和曼德拉。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Gandhi.' }
        }
      }
    ]
  },
  'yunani': {
    names: { id: 'Yunani Kuno', en: 'Ancient Greece', ja: '古代ギリシャ', ko: '고대 그리스', zh: '古希腊' },
    flag: '🇬🇷',
    articles: [
      {
        id: 'yunani-alexander',
        langs: {
          id: { title: 'Alexander Agung — Penakluk Dunia', desc: 'Pemimpin militer terbesar sepanjang masa yang membangun kekaisaran terbesar sebelum usia 33 tahun.', content: '<p class="mb-4">Alexander III dari Makedonia (356-323 SM) tidak pernah kalah dalam pertempuran sepanjang 15 tahun karir militernya. Murid Aristoteles ini naik takhta usia 20 tahun dan menaklukkan Persia, Mesir, Asia Tengah hingga India. Ia mendirikan 20+ kota Alexandria menyebarkan budaya Yunani (Helenisme). Alexander meninggal misterius di Babilonia usia 32 tahun.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Alexander the Great.' },
          en: { title: 'Alexander the Great — Conqueror of the World', desc: 'The greatest military leader of all time who built the largest empire before age 33.', content: '<p class="mb-4">Alexander III of Macedon (356-323 BCE) was never defeated in 15 years of military campaigns. A student of Aristotle, he conquered Persia, Egypt, Central Asia, and northwestern India, founding 20+ cities named Alexandria that spread Greek culture (Hellenism). He died mysteriously in Babylon at age 32.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Alexander the Great.' },
          ja: { title: 'アレクサンドロス大王', desc: '33歳以前に史上最大の帝国を築いた史上最大の軍事指導者。', content: '<p class="mb-4">マケドニアのアレクサンドロス3世（紀元前356-323年）は15年間無敗。アリストテレスの弟子として20歳で即位しペルシャ・エジプト・中央アジア・インド北西部を征服。20以上のアレクサンドリアを建設。32歳でバビロンにて謎の死を遂げました。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Alexander.' },
          ko: { title: '알렉산더 대왕', desc: '33세 이전에 역사상 최대 제국을 건설한 역사상 최고의 군사 지도자.', content: '<p class="mb-4">마케도니아의 알렉산더 3세(기원전 356-323년)는 15년간 무패. 아리스토텔레스의 제자로 20세에 즉위하여 페르시아, 이집트, 중앙아시아, 인도 북서부를 정복했습니다. 20개 이상의 알렉산드리아를 건설했으며 32세에 바빌론에서 의문사했습니다.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Alexander.' },
          zh: { title: '亚历山大大帝', desc: '在33岁之前建立历史上最大帝国的最伟大军事领袖。', content: '<p class="mb-4">马其顿的亚历山大三世（公元前356-323年）15年军事生涯从未战败。师从亚里士多德，20岁登基，征服波斯、埃及、中亚和印度西北部，建立了20多座亚历山大城。32岁在巴比伦神秘去世。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Alexander.' }
        }
      },
      {
        id: 'yunani-olimpiade',
        langs: {
          id: { title: 'Olimpiade Kuno Yunani', desc: 'Festival olahraga terbesar dunia kuno yang digelar setiap 4 tahun di Olympia sejak 776 SM selama 1.200 tahun.', content: '<p class="mb-4">Olimpiade Kuno diadakan di Olympia setiap 4 tahun sejak 776 SM, didedikasikan untuk Zeus. Selama berlangsung, semua perang dihentikan (Ekecheiria). Cabang olahraga: lari, gulat, tinju, pacuan kuda, pentathlon. Pemenang mendapat karangan daun zaitun. Dilarang Kaisar Theodosius I tahun 393 M. Olimpiade modern dihidupkan Baron Pierre de Coubertin di Athena 1896.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Ancient Olympics.' },
          en: { title: 'Ancient Greek Olympics', desc: 'The greatest sporting festival of the ancient world held every 4 years at Olympia from 776 BCE for 1,200 years.', content: '<p class="mb-4">The Ancient Olympics were held at Olympia every 4 years from 776 BCE, dedicated to Zeus. All wars were suspended during the games (Ekecheiria). Sports included sprint, wrestling, boxing, chariot racing, and pentathlon. Winners received olive leaf crowns. Banned by Emperor Theodosius I in 393 CE. Modern Olympics revived by Baron Pierre de Coubertin in Athens in 1896.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Ancient Olympics.' },
          ja: { title: '古代ギリシャのオリンピック', desc: '紀元前776年から1,200年間4年ごとにオリンピアで開催された古代世界最大のスポーツ祭典。', content: '<p class="mb-4">古代オリンピックは紀元前776年からゼウスに捧ける祭典として4年ごとにオリンピアで開催。期間中は全戦争が停止（エケケイリア）。競技は短距離走・レスリング・ボクシング・戦車競争・五種競技。393年テオドシウス1世に禁止。1896年アテネで近代オリンピックとして復活。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Ancient Olympics.' },
          ko: { title: '고대 그리스 올림픽', desc: '기원전 776년부터 1,200년간 4년마다 올림피아에서 개최된 고대 세계 최대 스포츠 축제.', content: '<p class="mb-4">고대 올림픽은 기원전 776년부터 제우스를 위한 축제로 4년마다 올림피아에서 개최되었습니다. 기간 중 모든 전쟁 중단(에케케이리아). 단거리 달리기, 레슬링, 복싱, 전차 경주, 5종 경기가 있었습니다. 393년 테오도시우스 1세에 의해 금지되었으며 1896년 아테네에서 근대 올림픽으로 부활했습니다.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Ancient Olympics.' },
          zh: { title: '古代希腊奥林匹克运动会', desc: '公元前776年起每4年在奥林匹亚举办的古代世界最大体育盛会，持续1,200年。', content: '<p class="mb-4">古代奥运会自公元前776年起以4年为周期在奥林匹亚举办，献给宙斯神。期间所有战争停止（神圣休战）。项目包括短跑、摔跤、拳击、战车赛、五项全能。优胜者获颁橄榄叶冠。393年被狄奥多西一世禁止。1896年在雅典以现代奥运会形式复活。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Ancient Olympics.' }
        }
      },
      {
        id: 'yunani-sparta',
        langs: {
          id: { title: 'Sparta — Kota Prajurit Terkuat', desc: 'Polis Yunani kuno yang membangun militer paling ditakuti dunia kuno melalui sistem Agoge yang keras.', content: '<p class="mb-4">Sparta membangun masyarakat seluruhnya berpusat pada kekuatan militer. Setiap anak laki-laki menjalani Agoge — pelatihan militer ketat dari usia 7 tahun. Wanita Sparta punya hak lebih luas dari wanita Yunani lainnya. Pertempuran Thermopylae (480 SM): 300 prajurit Sparta Raja Leonidas menahan ratusan ribu tentara Persia selama 3 hari — simbol keberanian abadi.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Sparta.' },
          en: { title: 'Sparta — City of the Mightiest Warriors', desc: 'The ancient Greek polis that built the most feared military through the brutal Agoge training system.', content: '<p class="mb-4">Sparta built a society entirely centered on military strength. Every boy underwent the Agoge — strict military training from age 7. Spartan women had far more rights than other Greek women. The Battle of Thermopylae (480 BCE): 300 Spartans under King Leonidas held off hundreds of thousands of Persian troops for 3 days — an eternal symbol of courage and sacrifice.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Sparta.' },
          ja: { title: 'スパルタ — 最強の戦士の都市', desc: 'アゴーゲーで古代世界最強の軍を築いた古代ギリシャのポリス。', content: '<p class="mb-4">スパルタは軍事力を中心に社会が構成されたポリスです。7歳からのアゴーゲー訓練が全少年に課されました。スパルタの女性は他のギリシャ女性より権利が豊かでした。テルモピュライの戦い（紀元前480年）：レオニダス王率いる300人が3日間ペルシャ軍数十万を食い止めた伝説は永遠の勇気の象徴です。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Sparta.' },
          ko: { title: '스파르타 — 가장 강한 전사의 도시', desc: '아고게 훈련 제도로 고대 세계 최강의 군대를 구축한 고대 그리스 폴리스.', content: '<p class="mb-4">스파르타는 군사력 중심으로 사회가 구성된 폴리스입니다. 7세부터 아고게 훈련이 모든 소년에게 부과되었습니다. 스파르타 여성은 다른 그리스 여성보다 권리가 많았습니다. 테르모필레 전투(기원전 480년): 레오니다스 왕의 300명이 3일간 수십만 페르시아군을 저지한 전설은 영원한 용기의 상징입니다.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Sparta.' },
          zh: { title: '斯巴达 — 最强战士之城', desc: '通过阿哥吉训练制度建立古代世界最强军队的古希腊城邦。', content: '<p class="mb-4">斯巴达以军事实力为中心组织社会。所有男孩从7岁开始接受阿哥吉军事训练。斯巴达女性拥有比其他希腊女性更多的权利。温泉关战役（公元前480年）：莱奥尼达斯王率300名战士阻挡波斯数十万大军3天——成为永恒的勇气象征。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Sparta.' }
        }
      },
      {
        id: 'yunani-demokrasi',
        langs: {
          id: { title: 'Lahirnya Demokrasi di Athena', desc: 'Bagaimana Athena kuno menciptakan demokrasi pada abad ke-5 SM — sistem pemerintahan yang kini menjadi fondasi dunia modern.', content: '<p class="mb-4">Demokrasi (demos=rakyat, kratos=kekuasaan) lahir di Athena pada abad ke-5 SM di bawah reformasi Cleisthenes (508 SM) dan Pericles. Setiap warga laki-laki Athena memiliki hak suara dalam majelis (Ekklesia) yang membuat keputusan hukum dan kebijakan negara.</p><p class="mb-4">Athena juga melahirkan filsafat Barat melalui Socrates, Plato, dan Aristoteles — tiga tokoh yang pemikirannya masih mendominasi ilmu pengetahuan, etika, dan politik hingga hari ini.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Athenian democracy.' },
          en: { title: 'Birth of Democracy in Athens', desc: 'How ancient Athens created democracy in the 5th century BCE — the governing system that now forms the foundation of the modern world.', content: '<p class="mb-4">Democracy (demos=people, kratos=power) was born in Athens in the 5th century BCE under reforms by Cleisthenes (508 BCE) and Pericles. Every male Athenian citizen had a vote in the assembly (Ekklesia) that made laws and state decisions. Athens also birthed Western philosophy through Socrates, Plato, and Aristotle — three thinkers whose ideas still dominate science, ethics, and politics today.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Athenian democracy.' },
          ja: { title: 'アテネにおける民主主義の誕生', desc: '紀元前5世紀の古代アテネが民主主義を創出した経緯。現代世界の基盤となる統治制度。', content: '<p class="mb-4">民主主義（デモス＝人民、クラトス＝権力）は紀元前5世紀のアテネでクレイステネス（紀元前508年）とペリクレスの改革により誕生しました。成人男性市民全員が法律・政策を決定する民会（エクレシア）で投票権を持ちました。アテネはソクラテス・プラトン・アリストテレスを通じて西洋哲学も生み出しました。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Athenian democracy.' },
          ko: { title: '아테네에서의 민주주의 탄생', desc: '기원전 5세기 고대 아테네가 민주주의를 창출한 과정. 현대 세계의 기반이 된 통치 제도.', content: '<p class="mb-4">민주주의(데모스=인민, 크라토스=권력)는 기원전 5세기 아테네에서 클레이스테네스(기원전 508년)와 페리클레스의 개혁으로 탄생했습니다. 성인 남성 시민 모두가 법률과 정책을 결정하는 민회(에클레시아)에서 투표권을 가졌습니다. 아테네는 소크라테스, 플라톤, 아리스토텔레스를 통해 서양 철학도 탄생시켰습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Athenian democracy.' },
          zh: { title: '雅典民主的诞生', desc: '古代雅典如何在公元前5世纪创造民主——如今构成现代世界基础的治理制度。', content: '<p class="mb-4">民主（demos=人民，kratos=权力）在公元前5世纪的雅典，在克里斯提尼（公元前508年）和伯里克利的改革下诞生。每位成年男性公民在决定法律和国家政策的公民大会（民众大会）中都有投票权。雅典还通过苏格拉底、柏拉图和亚里士多德孕育了西方哲学。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Athenian democracy.' }
        }
      }
    ]
  },
  'mongolia': {
    names: { id: 'Mongolia', en: 'Mongolia', ja: 'モンゴル', ko: '몽골', zh: '蒙古' },
    flag: '🇲🇳',
    articles: [
      {
        id: 'mongolia-genghis',
        langs: {
          id: { title: 'Genghis Khan — Pembangun Kekaisaran Terbesar', desc: 'Temujin yang menyatukan suku-suku Mongolia dan membangun kekaisaran daratan terbesar dalam sejarah manusia.', content: '<p class="mb-4">Temujin (1162-1227) bangkit dari masa kecil penuh penderitaan menjadi Genghis Khan pada 1206. Dalam 20 tahun pasukannya menaklukkan dari Tiongkok hingga Eropa Timur — 24 juta km² dan 100 juta penduduk. Taktik: kavaleri cepat, intelijen superior, psikologi terror. Diperkirakan 40 juta tewas dalam penaklukannya. Meninggal 1227 secara misterius, lokasi kuburannya tetap rahasia.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Genghis Khan.' },
          en: { title: 'Genghis Khan — Builder of the Greatest Empire', desc: 'Temujin who united Mongolian tribes and built the largest contiguous land empire in human history.', content: '<p class="mb-4">Temujin (1162-1227) rose from a painful childhood to become Genghis Khan in 1206. In 20 years his forces conquered from China to Eastern Europe — 24 million km² and 100 million people. Tactics: fast cavalry, superior intelligence, psychological terror. An estimated 40 million died in his conquests. He died mysteriously in 1227, his grave location still unknown to this day.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Genghis Khan.' },
          ja: { title: 'チンギス・ハン — 最大帝国の建設者', desc: 'モンゴルの部族を統一し、人類史上最大の陸上帝国を築いたテムジン。', content: '<p class="mb-4">テムジン（1162-1227年）は苦しい幼少期を乗り越え1206年にチンギス・ハンとなりました。20年で中国から東ヨーロッパまで2,400万平方キロ・1億人を支配。高速騎兵・優秀な情報収集・心理的恐怖を武器に推定4,000万人が犠牲になりました。1227年に謎の死を遂げ、墓の場所は今も秘密です。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Genghis Khan.' },
          ko: { title: '칭기즈 칸 — 가장 큰 제국의 건설자', desc: '몽골 부족을 통일하고 인류 역사상 가장 큰 연속 육상 제국을 건설한 테무진.', content: '<p class="mb-4">테무진(1162-1227년)은 힘든 어린 시절을 극복하고 1206년 칭기즈 칸이 되었습니다. 20년 만에 중국에서 동유럽까지 2,400만 km²와 1억 명을 지배했습니다. 고속 기병, 우수한 정보력, 심리적 공포를 무기로 추정 4,000만 명이 희생되었습니다. 1227년 의문사하여 무덤 위치는 아직도 비밀입니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Genghis Khan.' },
          zh: { title: '成吉思汗 — 最大帝国的建造者', desc: '统一蒙古各部落、建立人类历史上最大连续陆地帝国的铁木真。', content: '<p class="mb-4">铁木真（1162-1227年）克服艰难童年，1206年成为成吉思汗。20年内从中国到东欧征服2,400万平方公里和1亿人口。以快速骑兵、出色情报和心理恐惧为武器，估计造成4,000万人死亡。1227年神秘去世，墓穴位置至今仍是秘密。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Genghis Khan.' }
        }
      }
    ]
  },
  'ottoman': {
    names: { id: 'Kesultanan Ottoman', en: 'Ottoman Empire', ja: 'オスマン帝国', ko: '오스만 제국', zh: '奥斯曼帝国' },
    flag: '🕌',
    articles: [
      {
        id: 'ottoman-suleiman',
        langs: {
          id: { title: 'Sultan Suleiman Agung', desc: 'Pemerintahan Sultan Suleiman I (1520-1566) yang membawa Kekaisaran Ottoman ke puncak kekuasaan dan peradaban.', content: '<p class="mb-4">Suleiman I (1494-1566), dijuluki Al-Qanuni (Pembuat Hukum) dan Suleiman Agung, memerintah 46 tahun. Ottoman membentang dari Hungaria hingga Persia, Krimea hingga Somalia. Ia reformator hukum besar, penyair, dan patron seni. Arsitek Mimar Sinan membangun Masjid Suleiman di Istanbul atas perintahnya. Meninggal saat pengepungan Szigetvár 1566.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Suleiman the Magnificent.' },
          en: { title: 'Sultan Suleiman the Magnificent', desc: 'The reign of Sultan Suleiman I (1520-1566) that brought the Ottoman Empire to the peak of power and civilization.', content: '<p class="mb-4">Suleiman I (1494-1566), called Al-Qanuni (The Lawgiver) and Suleiman the Magnificent, ruled 46 years. The Ottoman Empire stretched from Hungary to Persia, Crimea to Somalia. He was a major legal reformer, poet, and art patron. Architect Mimar Sinan built the Suleiman Mosque in Istanbul under his command. He died during the Siege of Szigetvár in 1566.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Suleiman the Magnificent.' },
          ja: { title: 'スレイマン大帝', desc: 'オスマン帝国を権力・文明の頂点に導いたスレイマン1世の治世（1520-1566年）。', content: '<p class="mb-4">スレイマン1世（1494-1566年）は「立法者」・「壮麗帝」と呼ばれ46年間統治。帝国はハンガリーからペルシャ、クリミアからソマリアまで広がりました。法改革者・詩人・芸術のパトロンでもあり、建築家ミマール・スィナンがスレイマニエ・モスクを建設。1566年ジゲトバール包囲中に死去しました。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Suleiman.' },
          ko: { title: '술레이만 대제', desc: '오스만 제국을 권력과 문명의 정점으로 이끈 술레이만 1세의 치세(1520-1566년).', content: '<p class="mb-4">술레이만 1세(1494-1566년)는 "입법자"·"장엄한 술레이만"으로 불리며 46년 통치했습니다. 제국은 헝가리에서 페르시아, 크림에서 소말리아까지 뻗어 있었습니다. 법 개혁자, 시인, 예술 후원자이기도 했으며 건축가 미마르 시난이 술레이마니예 모스크를 건설했습니다. 1566년 시게트바르 포위전 중 사망했습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Suleiman.' },
          zh: { title: '苏莱曼大帝', desc: '将奥斯曼帝国带至权力与文明顶峰的苏莱曼一世统治时期（1520-1566年）。', content: '<p class="mb-4">苏莱曼一世（1494-1566年）被称为"立法者"和"大帝"，统治46年。帝国从匈牙利延伸至波斯，从克里米亚到索马里。他是重要的法律改革者、诗人和艺术赞助人，建筑师米马尔·锡南奉命建造苏莱曼尼耶清真寺。1566年在锡格特堡围攻战中去世。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Suleiman.' }
        }
      },
      {
        id: 'ottoman-konstantinopel',
        langs: {
          id: { title: 'Jatuhnya Konstantinopel 1453', desc: 'Penaklukan Konstantinopel oleh Sultan Mehmed II yang mengakhiri Kekaisaran Romawi Timur dan mengubah sejarah dunia.', content: '<p class="mb-4">Pada 29 Mei 1453, Sultan Mehmed II (22 tahun) menembus tembok Konstantinopel setelah 53 hari pengepungan menggunakan meriam raksasa Basilica. Kekaisaran Romawi Timur (Byzantium) yang 1.100 tahun berakhir. Dampak global: sarjana Yunani melarikan diri ke Eropa memicu Renaisans; jalur darat ke Asia terputus mendorong Eropa cari jalur laut — Columbus menemukan Amerika 1492.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Fall of Constantinople.' },
          en: { title: 'Fall of Constantinople 1453', desc: 'Ottoman conquest of Constantinople ended the Eastern Roman Empire and changed world history forever.', content: '<p class="mb-4">On May 29, 1453, Sultan Mehmed II (age 22) breached Constantinople after 53 days using the massive Basilica cannon. The 1,100-year Eastern Roman Empire (Byzantium) ended. Global impact: Greek scholars fled to Europe with manuscripts, triggering the Renaissance; the blocking of land routes to Asia pushed Europe to find sea routes — Columbus discovered America in 1492.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Fall of Constantinople.' },
          ja: { title: 'コンスタンティノープルの陥落 1453年', desc: 'メフメト2世のコンスタンティノープル征服が東ローマ帝国を終わらせ世界史を変えた。', content: '<p class="mb-4">1453年5月29日、22歳のメフメト2世が巨大砲バジリカで53日間の包囲の末コンスタンティノープルを陥落。1,100年続いた東ローマ帝国が終焉しました。世界への影響：ギリシャ学者が古典を持ちヨーロッパに逃れルネサンスを促進；陸路遮断がヨーロッパに海路を求めさせ1492年コロンブスのアメリカ発見につながりました。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Constantinople.' },
          ko: { title: '콘스탄티노폴리스의 함락 1453년', desc: '메흐메트 2세의 콘스탄티노폴리스 정복이 동로마 제국을 종식시키고 세계사를 영원히 바꾸었다.', content: '<p class="mb-4">1453년 5월 29일 22세의 메흐메트 2세가 거대 대포 바실리카로 53일 만에 콘스탄티노폴리스를 함락했습니다. 1,100년 동로마 제국이 종막을 고했습니다. 세계적 영향: 그리스 학자들이 고전 필사본을 들고 유럽으로 도피해 르네상스를 촉진; 육로 차단이 유럽을 해로 개척으로 이끌어 1492년 콜럼버스의 아메리카 발견으로 이어졌습니다.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Constantinople.' },
          zh: { title: '君士坦丁堡的陷落 1453年', desc: '穆罕默德二世征服君士坦丁堡，终结东罗马帝国并永久改变世界历史。', content: '<p class="mb-4">1453年5月29日，22岁的穆罕默德二世用巨炮巴西利卡经53天围攻攻克君士坦丁堡。延续1,100年的东罗马帝国终结。世界影响：希腊学者携古籍手稿逃往欧洲，促进了文艺复兴；陆路贸易受阻迫使欧洲开辟海路，导致1492年哥伦布发现美洲大陆。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Constantinople.' }
        }
      }
    ]
  },
  'maya': {
    names: { id: 'Peradaban Maya', en: 'Maya Civilization', ja: 'マヤ文明', ko: '마야 문명', zh: '玛雅文明' },
    flag: '🏛️',
    articles: [
      {
        id: 'maya-peradaban',
        langs: {
          id: { title: 'Peradaban Maya — Ilmuwan Mesoamerika', desc: 'Maya mengembangkan sistem tulisan, kalender, astronomi, dan matematika paling maju di dunia kuno Amerika.', content: '<p class="mb-4">Peradaban Maya berkembang di Mesoamerika dari sekitar 2000 SM hingga kedatangan Spanyol abad ke-16. Populasi puncak 10-20 juta jiwa. Maya mengembangkan tulisan hiroglif paling kompleks di Amerika, kalender lebih akurat dari Eropa saat itu, dan sistem angka berbasis-20 dengan konsep nol. Kota besar: Tikal, Chichen Itza, Palenque. Runtuh sekitar 900 M akibat kekeringan dan perang.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Maya civilization.' },
          en: { title: 'Maya Civilization — Mesoamerica's Scientists', desc: 'The Maya developed the most advanced writing, calendar, astronomy, and mathematics in ancient America.', content: '<p class="mb-4">Maya civilization flourished in Mesoamerica from around 2000 BCE until the 16th-century Spanish arrival. Peak population: 10-20 million. They developed the most complex writing in the Americas, a more accurate calendar than contemporary Europe, and a base-20 number system with zero. Great cities included Tikal, Chichen Itza, and Palenque. Classic Maya collapsed around 900 CE due to drought and warfare.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Maya civilization.' },
          ja: { title: 'マヤ文明 — 中米の科学者', desc: 'マヤは古代アメリカで最も進んだ文字・暦・天文・数学を発展させた。', content: '<p class="mb-4">マヤ文明は紀元前2000年頃から16世紀まで中米で栄えました。最盛期人口1,000-2,000万人。アメリカ最複雑な文字、当時のヨーロッパより正確な暦、ゼロを含む20進法を開発。ティカル・チチェン・イツァ・パレンケなどの大都市が繁栄。古典マヤは900年頃に干ばつと戦争で崩壊しました。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Maya civilization.' },
          ko: { title: '마야 문명 — 메소아메리카의 과학자들', desc: '마야는 고대 아메리카에서 가장 발전된 문자, 달력, 천문학, 수학을 발전시켰다.', content: '<p class="mb-4">마야 문명은 기원전 2000년경부터 16세기 스페인 도래까지 중미에서 번성했습니다. 최성기 인구 1,000-2,000만 명. 아메리카에서 가장 복잡한 문자, 당시 유럽보다 정확한 달력, 영을 포함한 20진법을 개발했습니다. 티칼, 치첸이트사, 팔렌케 등 대도시가 번성했습니다. 고전 마야는 900년경 가뭄과 전쟁으로 붕괴했습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Maya civilization.' },
          zh: { title: '玛雅文明 — 中美洲的科学家', desc: '玛雅人发展出古代美洲最先进的文字、历法、天文学和数学。', content: '<p class="mb-4">玛雅文明从约公元前2000年繁荣至16世纪西班牙人到来。鼎盛时期人口1,000-2,000万。他们开发了美洲最复杂的文字体系、比当时欧洲更精确的历法，以及包含零的20进制数字系统。蒂卡尔、奇琴伊察、帕伦克等大城市兴旺。古典玛雅约于900年因干旱和战争崩溃。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Maya civilization.' }
        }
      }
    ]
  },
  'viking': {
    names: { id: 'Viking', en: 'Vikings', ja: 'ヴァイキング', ko: '바이킹', zh: '维京人' },
    flag: '⚔️',
    articles: [
      {
        id: 'viking-ekspedisi',
        langs: {
          id: { title: 'Viking — Penjelajah Lautan Dunia', desc: 'Bangsa Norse dari Skandinavia yang menjelajahi dari Amerika Utara hingga Asia Tengah antara 793-1066 M.', content: '<p class="mb-4">Viking dari Skandinavia aktif 793-1066 M berkat kapal Longship revolusioner. Leif Erikson sekitar 1000 M mendarat di Amerika Utara (Vinland) — 400 tahun sebelum Columbus. Mereka juga mendirikan koloni di Islandia (874 M) dan Greenland (985 M), berdagang hingga Byzantium dan Baghdad, serta mendirikan Kerajaan Kiev di Eropa Timur. Ekspansi berakhir seiring kristenisasi Skandinavia.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Vikings.' },
          en: { title: 'Vikings — World Ocean Explorers', desc: 'Norse people from Scandinavia who explored from North America to Central Asia between 793-1066 CE.', content: '<p class="mb-4">Vikings from Scandinavia were active 793-1066 CE, famous for revolutionary Longships. Leif Erikson around 1000 CE landed in North America (Vinland) — over 400 years before Columbus. They also settled Iceland (874 CE) and Greenland (985 CE), traded as far as Byzantium and Baghdad, and founded Kievan Rus in Eastern Europe. Viking expansion ended as Scandinavia Christianized.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Vikings.' },
          ja: { title: 'ヴァイキング — 世界の海の探検家', desc: '793-1066年にスカンジナビアから北米から中央アジアまで探検したノルセ人。', content: '<p class="mb-4">スカンジナビアのヴァイキングは793-1066年に革命的なロングシップで活動。レイフ・エリクソンは1000年頃北米（ヴィンランド）に上陸し、コロンブスより400年以上先んじました。アイスランド（874年）・グリーンランド（985年）に植民し、ビザンツ・バグダードまで交易し、東欧にキエフ・ルーシを建国。スカンジナビアのキリスト教化とともに拡張は終焉しました。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Vikings.' },
          ko: { title: '바이킹 — 세계 바다의 탐험가', desc: '793-1066년 스칸디나비아에서 북아메리카부터 중앙아시아까지 탐험한 노르스인.', content: '<p class="mb-4">스칸디나비아 바이킹은 793-1066년 혁명적인 롱십으로 활동했습니다. 레이프 에릭손은 약 1000년경 북아메리카(빈란드)에 상륙했는데 콜럼버스보다 400년 이상 앞섰습니다. 아이슬란드(874년)·그린란드(985년)에 식민지를 건설하고 비잔티움·바그다드까지 교역하며 동유럽에 키예프 루스를 건국했습니다. 스칸디나비아의 기독교화와 함께 확장이 끝났습니다.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Vikings.' },
          zh: { title: '维京人 — 世界海洋探险家', desc: '793-1066年从斯堪的纳维亚探险于北美至中亚的诺斯人。', content: '<p class="mb-4">斯堪的纳维亚维京人活跃于793-1066年，以革命性的长船著称。莱夫·埃里克森约于1000年登陆北美（文兰）——比哥伦布早400多年。他们在冰岛（874年）和格陵兰（985年）建立殖民地，交易远达拜占庭和巴格达，并在东欧建立了基辅罗斯。随着斯堪的纳维亚基督教化，扩张走向终结。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Vikings.' }
        }
      }
    ]
  },
  'persia': {
    names: { id: 'Persia Kuno', en: 'Ancient Persia', ja: '古代ペルシャ', ko: '고대 페르시아', zh: '古代波斯' },
    flag: '🇮🇷',
    articles: [
      {
        id: 'persia-achaemenid',
        langs: {
          id: { title: 'Kekaisaran Achaemenid — Kekaisaran Pertama Dunia', desc: 'Kekaisaran Persia Achaemenid (550-330 SM) menjadi kekaisaran multinasional pertama dan terbesar dalam sejarah kuno.', content: '<p class="mb-4">Kekaisaran Achaemenid (550-330 SM) didirikan Cyrus Agung mencakup 8 juta km² dan 44% populasi dunia — dari Lembah Indus hingga Libya dan Thrace. Cyrus membebaskan bangsa Yahudi dari perbudakan Babilon — dicatat Alkitab sebagai pembebas. Silinder Cyrus (539 SM) dianggap piagam hak asasi manusia pertama. Darius I membangun Royal Road 2.700 km dan Persepolis. Ditaklukkan Alexander 334-330 SM.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Achaemenid Empire.' },
          en: { title: 'Achaemenid Empire — World's First Empire', desc: 'The Persian Achaemenid Empire (550-330 BCE) became the world's first multinational and largest empire in ancient history.', content: '<p class="mb-4">The Achaemenid Empire (550-330 BCE) founded by Cyrus the Great covered 8 million km² and 44% of the world's population — from the Indus Valley to Libya and Thrace. Cyrus freed the Jews from Babylonian captivity, recorded in the Bible as a liberator. The Cyrus Cylinder (539 BCE) is considered the first human rights charter. Darius I built the 2,700 km Royal Road and Persepolis. Conquered by Alexander 334-330 BCE.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Achaemenid Empire.' },
          ja: { title: 'アケメネス朝 — 世界初の帝国', desc: '紀元前550-330年のペルシャ・アケメネス朝が世界初の多民族帝国となった。', content: '<p class="mb-4">アケメネス朝（紀元前550-330年）はキュロス大王が創建し、800万平方キロ・世界人口44%を支配。インダス川流域からリビア・トラキアまで広がりました。キュロスはバビロン捕囚のユダヤ人を解放し聖書に記されました。キュロスの円筒は史上初の人権宣言。ダレイオス1世が2,700kmの王の道とペルセポリスを建設。アレクサンドロスに紀元前334-330年に征服されました。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Achaemenid Empire.' },
          ko: { title: '아케메네스 왕조 — 세계 최초의 제국', desc: '기원전 550-330년의 페르시아 아케메네스 제국이 세계 최초의 다민족 제국이 되었다.', content: '<p class="mb-4">아케메네스 제국(기원전 550-330년)은 키루스 대왕이 창건하여 800만 km²와 세계 인구 44%를 지배했습니다. 인더스 계곡에서 리비아·트라키아까지 뻗어 있었습니다. 키루스는 바빌론 포로 유대인을 해방하여 성경에 기록되었습니다. 키루스 실린더는 최초의 인권 선언으로 여겨집니다. 다리우스 1세가 2,700km 왕의 도로와 페르세폴리스를 건설했습니다. 기원전 334-330년 알렉산더에게 정복되었습니다.</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Achaemenid Empire.' },
          zh: { title: '阿契美尼德帝国 — 世界上第一个帝国', desc: '公元前550-330年的波斯阿契美尼德帝国成为世界第一个多民族帝国。', content: '<p class="mb-4">阿契美尼德帝国（公元前550-330年）由居鲁士大帝创建，覆盖800万平方公里和世界人口的44%，从印度河流域延伸至利比亚和色雷斯。居鲁士释放了被巴比伦囚禁的犹太人，被圣经记载。居鲁士圆筒是最早的人权宣言。大流士一世建造了2,700公里御道和波斯波利斯。公元前334-330年被亚历山大征服。</p>', sourceDomain: 'worldhistory.org', sourceSnippet: 'World History Encyclopedia — Achaemenid Empire.' }
        }
      }
    ]
  }

}
