// Wikybook — Data historis: prancis
// File ini di-generate otomatis. Jangan edit manual.

if (typeof window.countryDataFiles === 'undefined') window.countryDataFiles = {};

window.countryDataFiles['prancis'] = {
    names: { id: 'Prancis', en: 'France', ja: 'フランス', ko: '프랑스', zh: '法国' },
    flag: '🇫🇷',
    articles: [
      {
        id: 'prancis-french-revolution',
        langs: {
          id: { title: 'French Revolution', desc: 'Peristiwa penting dalam sejarah Prancis yang membentuk peradaban kawasan.', content: '<p class="mb-4">French Revolution adalah salah satu momen paling berpengaruh dalam sejarah Prancis. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari French Revolution masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari French Revolution sebagai bagian tak terpisahkan dari identitas kolektif bangsa Prancis.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — French Revolution.' },
          en: { title: 'French Revolution', desc: 'A defining moment in the history of France that shaped its civilization.', content: '<p class="mb-4">French Revolution stands as one of the most consequential events in the long history of France. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined French Revolution from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of French Revolution endures in the cultural memory and national identity of the people of France, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — French Revolution.' },
          ja: { title: 'French Revolution', desc: 'フランスの歴史を形成した重要な出来事。', content: '<p class="mb-4">French Revolutionはフランスの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはFrench Revolutionを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">French Revolutionの遺産はフランスの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — French Revolution.' },
          ko: { title: 'French Revolution', desc: '프랑스의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">French Revolution은(는) 프랑스의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 French Revolution을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">French Revolution의 유산은 프랑스 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — French Revolution.' },
          zh: { title: 'French Revolution', desc: '塑造法国历史的重要事件。', content: '<p class="mb-4">French Revolution是法国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了French Revolution，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">French Revolution的遗产延续在法国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — French Revolution.' },
        }
      },
      {
        id: 'prancis-napoleon-bonaparte',
        langs: {
          id: { title: 'Napoleon Bonaparte', desc: 'Peristiwa penting dalam sejarah Prancis yang membentuk peradaban kawasan.', content: '<p class="mb-4">Napoleon Bonaparte adalah salah satu momen paling berpengaruh dalam sejarah Prancis. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Napoleon Bonaparte masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Napoleon Bonaparte sebagai bagian tak terpisahkan dari identitas kolektif bangsa Prancis.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Napoleon Bonaparte.' },
          en: { title: 'Napoleon Bonaparte', desc: 'A defining moment in the history of France that shaped its civilization.', content: '<p class="mb-4">Napoleon Bonaparte stands as one of the most consequential events in the long history of France. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Napoleon Bonaparte from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Napoleon Bonaparte endures in the cultural memory and national identity of the people of France, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Napoleon Bonaparte.' },
          ja: { title: 'Napoleon Bonaparte', desc: 'フランスの歴史を形成した重要な出来事。', content: '<p class="mb-4">Napoleon Bonaparteはフランスの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはNapoleon Bonaparteを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Napoleon Bonaparteの遺産はフランスの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Napoleon Bonaparte.' },
          ko: { title: 'Napoleon Bonaparte', desc: '프랑스의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Napoleon Bonaparte은(는) 프랑스의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Napoleon Bonaparte을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Napoleon Bonaparte의 유산은 프랑스 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Napoleon Bonaparte.' },
          zh: { title: 'Napoleon Bonaparte', desc: '塑造法国历史的重要事件。', content: '<p class="mb-4">Napoleon Bonaparte是法国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Napoleon Bonaparte，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Napoleon Bonaparte的遗产延续在法国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Napoleon Bonaparte.' },
        }
      },
      {
        id: 'prancis-charlemagne',
        langs: {
          id: { title: 'Charlemagne', desc: 'Peristiwa penting dalam sejarah Prancis yang membentuk peradaban kawasan.', content: '<p class="mb-4">Charlemagne adalah salah satu momen paling berpengaruh dalam sejarah Prancis. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Charlemagne masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Charlemagne sebagai bagian tak terpisahkan dari identitas kolektif bangsa Prancis.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Charlemagne.' },
          en: { title: 'Charlemagne', desc: 'A defining moment in the history of France that shaped its civilization.', content: '<p class="mb-4">Charlemagne stands as one of the most consequential events in the long history of France. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Charlemagne from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Charlemagne endures in the cultural memory and national identity of the people of France, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Charlemagne.' },
          ja: { title: 'Charlemagne', desc: 'フランスの歴史を形成した重要な出来事。', content: '<p class="mb-4">Charlemagneはフランスの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはCharlemagneを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Charlemagneの遺産はフランスの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Charlemagne.' },
          ko: { title: 'Charlemagne', desc: '프랑스의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Charlemagne은(는) 프랑스의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Charlemagne을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Charlemagne의 유산은 프랑스 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Charlemagne.' },
          zh: { title: 'Charlemagne', desc: '塑造法国历史的重要事件。', content: '<p class="mb-4">Charlemagne是法国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Charlemagne，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Charlemagne的遗产延续在法国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Charlemagne.' },
        }
      },
      {
        id: 'prancis-hundred-years-war',
        langs: {
          id: { title: 'Hundred Years War', desc: 'Peristiwa penting dalam sejarah Prancis yang membentuk peradaban kawasan.', content: '<p class="mb-4">Hundred Years War adalah salah satu momen paling berpengaruh dalam sejarah Prancis. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Hundred Years War masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Hundred Years War sebagai bagian tak terpisahkan dari identitas kolektif bangsa Prancis.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Hundred Years War.' },
          en: { title: 'Hundred Years War', desc: 'A defining moment in the history of France that shaped its civilization.', content: '<p class="mb-4">Hundred Years War stands as one of the most consequential events in the long history of France. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Hundred Years War from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Hundred Years War endures in the cultural memory and national identity of the people of France, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Hundred Years War.' },
          ja: { title: 'Hundred Years War', desc: 'フランスの歴史を形成した重要な出来事。', content: '<p class="mb-4">Hundred Years Warはフランスの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはHundred Years Warを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Hundred Years Warの遺産はフランスの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Hundred Years War.' },
          ko: { title: 'Hundred Years War', desc: '프랑스의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Hundred Years War은(는) 프랑스의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Hundred Years War을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Hundred Years War의 유산은 프랑스 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Hundred Years War.' },
          zh: { title: 'Hundred Years War', desc: '塑造法国历史的重要事件。', content: '<p class="mb-4">Hundred Years War是法国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Hundred Years War，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Hundred Years War的遗产延续在法国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Hundred Years War.' },
        }
      },
      {
        id: 'prancis-louis-xiv-versailles',
        langs: {
          id: { title: 'Louis XIV Versailles', desc: 'Peristiwa penting dalam sejarah Prancis yang membentuk peradaban kawasan.', content: '<p class="mb-4">Louis XIV Versailles adalah salah satu momen paling berpengaruh dalam sejarah Prancis. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Louis XIV Versailles masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Louis XIV Versailles sebagai bagian tak terpisahkan dari identitas kolektif bangsa Prancis.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Louis XIV Versailles.' },
          en: { title: 'Louis XIV Versailles', desc: 'A defining moment in the history of France that shaped its civilization.', content: '<p class="mb-4">Louis XIV Versailles stands as one of the most consequential events in the long history of France. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Louis XIV Versailles from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Louis XIV Versailles endures in the cultural memory and national identity of the people of France, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Louis XIV Versailles.' },
          ja: { title: 'Louis XIV Versailles', desc: 'フランスの歴史を形成した重要な出来事。', content: '<p class="mb-4">Louis XIV Versaillesはフランスの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはLouis XIV Versaillesを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Louis XIV Versaillesの遺産はフランスの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Louis XIV Versailles.' },
          ko: { title: 'Louis XIV Versailles', desc: '프랑스의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Louis XIV Versailles은(는) 프랑스의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Louis XIV Versailles을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Louis XIV Versailles의 유산은 프랑스 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Louis XIV Versailles.' },
          zh: { title: 'Louis XIV Versailles', desc: '塑造法国历史的重要事件。', content: '<p class="mb-4">Louis XIV Versailles是法国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Louis XIV Versailles，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Louis XIV Versailles的遗产延续在法国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Louis XIV Versailles.' },
        }
      }
    ]
  };
