// Wikybook — Data historis: romawi
// File ini di-generate otomatis. Jangan edit manual.

if (typeof window.countryDataFiles === 'undefined') window.countryDataFiles = {};

window.countryDataFiles['romawi'] = {
    names: { id: 'Romawi Kuno', en: 'Ancient Rome', ja: '古代ローマ', ko: '고대 로마', zh: '古罗马' },
    flag: '🏛️',
    articles: [
      {
        id: 'romawi-julius-caesar',
        langs: {
          id: { title: 'Julius Caesar', desc: 'Jenderal dan diktator Roma yang mengubah Republik menjadi cikal bakal Kekaisaran dan namanya abadi sepanjang masa.', content: '<p class="mb-4">Gaius Julius Caesar (100–44 SM) adalah sosok paling berpengaruh dalam sejarah Roma. Jenderal brilian yang menaklukkan Galia (Prancis modern) dalam 8 tahun, ia juga penulis, orator, dan politisi kelas dunia.</p><p class="mb-4">Ketika Caesar menyeberangi Sungai Rubicon (49 SM) dengan pasukannya — melanggar hukum Roma — ia memulai perang saudara melawan Pompey dan Senat. Ia menang dan menjadi diktator Roma.</p><p class="mb-4">Pada 15 Maret 44 SM (Ides of March), Caesar dibunuh oleh 23 tusukan dari sekelompok senator yang dipimpin Brutus dan Cassius. Kematiannya justru mengakhiri Republik dan melahirkan Kekaisaran Romawi.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Encyclopaedia Britannica — Julius Caesar.' },
          en: { title: 'Julius Caesar', desc: 'Rome\'s general and dictator who transformed the Republic into the precursor of the Empire — his name immortalized forever.', content: '<p class="mb-4">Gaius Julius Caesar (100–44 BC) was the most influential figure in Roman history. A brilliant general who conquered Gaul (modern France) in 8 years, he was also a world-class writer, orator, and politician.</p><p class="mb-4">When Caesar crossed the Rubicon River (49 BC) with his army — violating Roman law — he started a civil war against Pompey and the Senate. He won and became Rome\'s dictator.</p><p class="mb-4">On March 15, 44 BC (the Ides of March), Caesar was assassinated with 23 stab wounds by a group of senators led by Brutus and Cassius. His death paradoxically ended the Republic and birthed the Roman Empire.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Julius Caesar.' },
          ja: { title: 'ユリウス・カエサル', desc: '共和国を帝国の前身に変えたローマの将軍と独裁者。', content: '<p class="mb-4">ガイウス・ユリウス・カエサル（紀元前100–44年）はローマ史上最も影響力のある人物でした。8年でガリア（現代のフランス）を征服した天才的な将軍であり、世界クラスの作家、雄弁家、政治家でもありました。</p><p class="mb-4">紀元前44年3月15日（イードゥス・マルティアエ）、ブルートゥスとカッシウスが率いる元老院議員グループによって23カ所を刺されて暗殺されました。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — ユリウス・カエサル。' },
          ko: { title: '율리우스 카이사르', desc: '공화국을 제국의 전신으로 변모시킨 로마의 장군이자 독재자.', content: '<p class="mb-4">가이우스 율리우스 카이사르(기원전 100–44년)는 로마 역사에서 가장 영향력 있는 인물이었습니다. 8년 만에 갈리아(현대 프랑스)를 정복한 천재적인 장군이자 세계적인 작가, 연설가, 정치가였습니다.</p><p class="mb-4">기원전 44년 3월 15일(이두스 마르티아이), 브루투스와 카시우스가 이끄는 원로원 의원 그룹에 의해 23번 찔려 암살되었습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 율리우스 카이사르.' },
          zh: { title: '尤利乌斯·凯撒', desc: '将共和国转变为帝国前身的罗马将军和独裁者。', content: '<p class="mb-4">盖乌斯·尤利乌斯·凯撒（公元前100–44年）是罗马历史上最具影响力的人物。他是一位天才将军，在8年内征服了高卢（现代法国），同时也是世界级的作家、演说家和政治家。</p><p class="mb-4">公元前44年3月15日（三月望日），凯撒被布鲁图斯和卡西乌斯领导的元老院议员群体刺以23刀后遇刺身亡。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 尤利乌斯·凯撒。' }
        }
      },
      {
        id: 'romawi-colosseum',
        langs: {
          id: { title: 'Colosseum — Arena Raksasa Roma', desc: 'Amfiteater terbesar sepanjang masa yang menampung 80.000 penonton untuk pertarungan gladiator yang legendaris.', content: '<p class="mb-4">Colosseum (Flavian Amphitheatre) adalah amfiteater terbesar dalam sejarah manusia, dibangun antara 70–80 M di Roma. Mampu menampung 50.000–80.000 penonton, bangunan oval raksasa ini adalah puncak teknik konstruksi Romawi.</p><p class="mb-4">Di sini digelar pertarungan gladiator (munera), perburuan binatang buas (venationes), dan bahkan pertempuran laut buatan (naumachiae) dengan mengisi arena dengan air. Diperkirakan lebih dari 400.000 orang dan jutaan hewan mati di arena ini selama berabad-abad.</p><p class="mb-4">Meski rusak akibat gempa dan penjarahan, 2/3 bangunan asli masih berdiri. Colosseum kini menjadi monumen paling ikonik di dunia, dikunjungi 7 juta wisatawan per tahun.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Colosseum Roma.' },
          en: { title: 'The Colosseum — Rome\'s Giant Arena', desc: 'The largest amphitheater ever built, seating 80,000 spectators for legendary gladiatorial combat.', content: '<p class="mb-4">The Colosseum (Flavian Amphitheatre) is the largest amphitheater in human history, built between 70–80 CE in Rome. Capable of seating 50,000–80,000 spectators, this giant oval structure is the pinnacle of Roman construction engineering.</p><p class="mb-4">Here took place gladiatorial fights (munera), wild beast hunts (venationes), and even mock naval battles (naumachiae) by flooding the arena. Over 400,000 people and millions of animals are estimated to have died here over the centuries.</p><p class="mb-4">Though damaged by earthquakes and looting, 2/3 of the original structure still stands. The Colosseum is now the world\'s most iconic monument, visited by 7 million tourists per year.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — Roman Colosseum.' },
          ja: { title: 'コロッセオ — ローマの巨大闘技場', desc: '伝説の剣闘士の戦いのために8万人の観客を収容した、史上最大の円形闘技場。', content: '<p class="mb-4">コロッセオ（フラウィウス円形闘技場）は70〜80年頃にローマに建設された人類史上最大の円形闘技場です。5万〜8万人の観客を収容でき、ローマ建設工学の粋を集めた建物です。</p><p class="mb-4">現在も元の構造の3分の2が残っており、年間700万人の観光客が訪れる世界最も象徴的な記念碑となっています。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — ローマのコロッセオ。' },
          ko: { title: '콜로세움 — 로마의 거대한 경기장', desc: '전설적인 검투사 싸움을 위해 8만 명의 관중을 수용한 역사상 가장 큰 원형 경기장.', content: '<p class="mb-4">콜로세움(플라비우스 원형 경기장)은 70~80년경 로마에 건설된 인류 역사상 가장 큰 원형 경기장입니다. 5만~8만 명의 관중을 수용할 수 있으며, 로마 건설 공학의 정점입니다.</p><p class="mb-4">원래 구조물의 2/3가 여전히 남아 있으며, 연간 700만 명의 관광객이 방문하는 세계에서 가장 상징적인 기념물이 되었습니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 로마 콜로세움.' },
          zh: { title: '罗马斗兽场 — 罗马的巨型竞技场', desc: '有史以来最大的圆形剧场，可容纳8万名观众观看传奇的角斗士战斗。', content: '<p class="mb-4">斗兽场（弗拉维安圆形剧场）是人类历史上最大的圆形剧场，建于公元70-80年间。可容纳5-8万名观众，是罗马建筑工程的顶峰。</p><p class="mb-4">尽管因地震和掠夺受损，原始结构的2/3仍然矗立。斗兽场现在是世界上最具标志性的纪念碑，每年有700万游客参观。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 罗马斗兽场。' }
        }
      },
      {
        id: 'romawi-augustus',
        langs: {
          id: { title: 'Augustus — Kaisar Pertama Roma', desc: 'Dari keponakan Julius Caesar hingga menjadi kaisar pertama yang memerintah 41 tahun dan membawa Pax Romana.', content: '<p class="mb-4">Gaius Octavius, yang kemudian dikenal sebagai <strong>Augustus</strong>, adalah kaisar pertama Roma dan salah satu pemimpin paling berpengaruh dalam sejarah dunia. Lahir pada 63 SM, ia adalah keponakan dan pewaris adopsi Julius Caesar yang dibunuh pada 44 SM.</p><p class="mb-4">Setelah Caesar wafat, Octavianus berhasil mengalahkan rivalnya — termasuk koalisi <strong>Mark Antony dan Cleopatra</strong> dalam Pertempuran Actium (31 SM) — dan menjadi penguasa tunggal dunia Romawi. Senat menganugerahinya gelar "Augustus" (Yang Mulia) pada 27 SM, menandai berakhirnya Republik dan lahirnya Kekaisaran Romawi.</p><p class="mb-4">Augustus memerintah selama <strong>41 tahun</strong> (27 SM – 14 M), masa terpanjang dalam sejarah kekaisaran. Ia merombak pemerintahan Roma secara fundamental: membangun korp pemadam kebakaran, polisi, angkatan laut tetap, dan sistem pos (<em>cursus publicus</em>) yang menghubungkan seluruh kekaisaran.</p><p class="mb-4">Era Augustus dikenal sebagai <strong>Pax Romana</strong> (Perdamaian Romawi) — 200 tahun relatif damai yang memungkinkan perdagangan, seni, dan arsitektur berkembang. Ia membangun begitu banyak monumen hingga berkata, "Aku mewarisi Roma yang terbuat dari bata, dan meninggalkannya terbuat dari marmer."</p><p class="mb-4">Augustus meninggal pada 14 M dan dideifikasi oleh Senat. Ia meninggalkan catatan biografi tertua yang pernah ditulis seorang pemimpin dunia: <em>Res Gestae Divi Augusti</em> (Perbuatan-Perbuatan Ilahi Augustus), yang terukir di dinding kuil di seluruh kekaisaran.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Encyclopaedia Britannica — Augustus, First Roman Emperor. | History.com — Augustus: Roman Emperor. | Smithsonian Magazine — How Augustus Became the First Emperor of Rome. | Livy — Ab Urbe Condita.' },
          en: { title: 'Augustus — Rome\'s First Emperor', desc: 'From Julius Caesar\'s nephew to the first emperor who ruled 41 years and ushered in the Pax Romana.', content: '<p class="mb-4">Gaius Octavius, known as <strong>Augustus</strong>, was Rome\'s first emperor and one of history\'s most influential leaders. Born in 63 BC, he was Julius Caesar\'s grandnephew and adopted heir.</p><p class="mb-4">After Caesar\'s assassination (44 BC), Octavian defeated all rivals — including <strong>Mark Antony and Cleopatra</strong> at the Battle of Actium (31 BC) — becoming sole ruler of the Roman world. The Senate granted him the title "Augustus" (Revered One) in 27 BC, marking the end of the Republic and birth of the Empire.</p><p class="mb-4">Augustus ruled for <strong>41 years</strong> (27 BC – 14 AD), the longest in imperial history. He created Rome\'s fire brigade, police force, standing navy, and postal system (<em>cursus publicus</em>).</p><p class="mb-4">His era became the <strong>Pax Romana</strong> — 200 years of relative peace enabling trade, arts, and architecture to flourish. He famously said: "I found Rome a city of bricks and left it a city of marble."</p><p class="mb-4">Augustus died in 14 AD and was deified by the Senate. He left the oldest surviving autobiography by a world leader: <em>Res Gestae Divi Augusti</em>, inscribed on temple walls across the empire.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Encyclopaedia Britannica — Augustus. | History.com — Augustus: First Roman Emperor. | Smithsonian Magazine — How Augustus Became the First Emperor. | National Geographic — Pax Romana.' },
          ja: { title: 'アウグストゥス — ローマ初代皇帝', desc: 'ユリウス・カエサルの甥から41年間統治した初代皇帝となり、パクス・ロマーナをもたらした。', content: '<p class="mb-4"><strong>アウグストゥス</strong>（紀元前63年–紀元14年）はローマ初代皇帝で歴史上最も影響力のある指導者の一人です。ユリウス・カエサルの養子として、カエサル暗殺後すべての競争者を打ち破り唯一の支配者となりました。</p><p class="mb-4">紀元前27年に元老院から「アウグストゥス」の称号を与えられ、共和政の終焉と帝政の始まりを告げました。<strong>41年間</strong>の統治は帝政史上最長でした。</p><p class="mb-4">彼の時代は<strong>パクス・ロマーナ</strong>（ローマの平和）として知られ、200年の相対的平和をもたらしました。「煉瓦のローマを受け継ぎ、大理石のローマを残した」という言葉は有名です。</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — アウグストゥス。| History.com — ローマ初代皇帝。| Smithsonian Magazine — アウグストゥス。 | Encyclopaedia Britannica — Britannica — アウグストゥス。| History.com — ローマ初代皇帝。| Smithsonian Magazine — アウグストゥス。 | Smithsonian Magazine — Britannica — アウグストゥス。| History.com — ローマ初代皇帝。| Smithsonian Magazine — アウグストゥス。' },
          ko: { title: '아우구스투스 — 로마 초대 황제', desc: '율리우스 카이사르의 조카에서 41년간 통치한 초대 황제로 팍스 로마나를 가져왔다.', content: '<p class="mb-4"><strong>아우구스투스</strong>(기원전 63년–기원후 14년)는 로마 초대 황제로 역사상 가장 영향력 있는 지도자 중 한 명입니다. 카이사르 암살 후 모든 경쟁자를 물리치고 기원전 27년 원로원으로부터 "아우구스투스" 칭호를 받았습니다.</p><p class="mb-4"><strong>41년간</strong>의 통치는 제정 역사상 가장 긴 기간이었습니다. 소방대, 경찰, 상비 해군, 우편 시스템을 창설했습니다.</p><p class="mb-4">그의 시대는 <strong>팍스 로마나</strong>(로마의 평화)로 알려진 200년의 상대적 평화기였습니다. "벽돌의 로마를 물려받아 대리석의 로마를 남겼다"는 말로 유명합니다.</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 아우구스투스. | History.com — 로마 초대 황제. | Smithsonian Magazine — 아우구스투스.' },
          zh: { title: '奥古斯都 — 罗马第一位皇帝', desc: '从尤利乌斯·凯撒的侄子到统治41年的首位皇帝，带来了罗马和平时代。', content: '<p class="mb-4"><strong>奥古斯都</strong>（公元前63年–公元14年）是罗马第一位皇帝，历史上最有影响力的领袖之一。凯撒被暗杀后，他击败所有对手，于公元前27年获得"奥古斯都"称号，标志着共和国终结和帝国诞生。</p><p class="mb-4">他统治了<strong>41年</strong>，是帝国历史上最长的。创建了消防队、警察、常备海军和邮政系统。</p><p class="mb-4">他的时代被称为<strong>罗马和平</strong>，带来200年的相对和平。他留下名言："我继承了一座砖砌的罗马，留下了一座大理石的罗马。"</p>', sourceDomain: 'britannica.com', sourceSnippet: 'Britannica — 奥古斯都。| History.com — 罗马第一位皇帝。| Smithsonian — 奥古斯都。 | Encyclopaedia Britannica — Britannica — 奥古斯都。| History.com — 罗马第一位皇帝。| Smithsonian — 奥古斯都。 | Smithsonian Magazine — Britannica — 奥古斯都。| History.com — 罗马第一位皇帝。| Smithsonian — 奥古斯都。' }
        }
      },
      {
        id: 'romawi-gladiator',
        langs: {
          id: { title: 'Gladiator — Ksatria Arena Roma', desc: 'Kisah para gladiator yang bertarung demi kehidupan di arena-arena Roma, simbol kekuatan dan hiburan kekaisaran.', content: '<p class="mb-4">Gladiator adalah pejuang terlatih yang bertarung di arena publik untuk hiburan rakyat Roma. Kata "gladiator" berasal dari <em>gladius</em>, pedang pendek khas prajurit Romawi. Pertarungan gladiator pertama kali tercatat pada 264 SM sebagai bagian dari upacara pemakaman, namun berkembang menjadi tontonan massal terbesar dalam sejarah kuno.</p><p class="mb-4">Mayoritas gladiator adalah <strong>budak, tawanan perang, atau penjahat</strong> yang dipaksa bertarung. Namun ada pula warga merdeka bahkan bangsawan yang secara sukarela masuk sekolah gladiator (<em>ludus</em>) karena iming-iming kemasyhuran dan hadiah uang.</p><p class="mb-4">Berbeda dari gambaran populer, tidak semua pertarungan berakhir dengan kematian. Membunuh gladiator yang sudah menyerah sebenarnya merugikan secara ekonomi — melatih seorang gladiator profesional membutuhkan waktu bertahun-tahun dan biaya besar. Pertarungan sering diakhiri ketika salah satu pihak menyerah, dan keputusan akhir nasibnya ada di tangan penyelenggara atau penonton.</p><p class="mb-4"><strong>Spartacus</strong> adalah gladiator paling terkenal dalam sejarah. Bekas budak asal Trakia ini memimpin pemberontakan budak terbesar dalam sejarah Romawi (73–71 SM), mengumpulkan lebih dari 70.000 budak yang menguasai sebagian besar Italia selatan selama hampir dua tahun sebelum akhirnya dikalahkan Jenderal Crassus.</p><p class="mb-4">Pertarungan gladiator secara resmi dilarang oleh Kaisar Honorius pada 399 M setelah seorang biksu bernama Telemachus melompat ke arena untuk menghentikan pertarungan dan tewas dirajam penonton — kematiannya justru menggerakkan Kaisar untuk mengeluarkan larangan permanen.</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — Gladiators: Rome\'s Bloody Sport. | Smithsonian Magazine — The Surprising Truth About Roman Gladiators. | History.com — Gladiators. | Britannica — Spartacus Roman slave.' },
          en: { title: 'Gladiators — Rome\'s Arena Warriors', desc: 'The story of gladiators who fought for their lives in Roman arenas, symbols of imperial power and entertainment.', content: '<p class="mb-4">Gladiators were trained fighters who battled in public arenas for Roman entertainment. The word comes from <em>gladius</em>, the short Roman sword. The first recorded gladiatorial combat was in 264 BC as part of a funeral rite, but it grew into ancient history\'s greatest mass spectacle.</p><p class="mb-4">Most gladiators were <strong>slaves, prisoners of war, or criminals</strong> forced to fight. But free citizens and even nobles sometimes voluntarily entered gladiatorial schools (<em>ludus</em>) for fame and prize money.</p><p class="mb-4">Contrary to popular belief, not all fights ended in death. Killing a surrendered gladiator was economically wasteful — training a professional gladiator took years and was costly. Fights often ended when one combatant yielded, with the final decision resting with the sponsor or crowd.</p><p class="mb-4"><strong>Spartacus</strong> was history\'s most famous gladiator — a Thracian slave who led the largest slave revolt in Roman history (73–71 BC), gathering 70,000+ slaves who controlled most of southern Italy for nearly two years before being defeated by General Crassus.</p><p class="mb-4">Gladiatorial combat was officially banned by Emperor Honorius in 399 AD after a monk named Telemachus jumped into the arena to stop a fight and was stoned to death by the crowd — his death moved the Emperor to issue a permanent ban.</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — Gladiators: Rome\'s Bloody Sport. | Smithsonian Magazine — The Truth About Roman Gladiators. | History.com — Gladiators. | Britannica — Spartacus.' },
          ja: { title: 'グラディエーター — ローマの闘技場の戦士', desc: 'ローマの闘技場で命をかけて戦ったグラディエーターたち、帝国の力と娯楽の象徴。', content: '<p class="mb-4">グラディエーターは公開の闘技場でローマ市民の娯楽のために戦った訓練された戦士です。「グラディエーター」という言葉はローマの短剣<em>グラディウス</em>に由来します。</p><p class="mb-4">ほとんどは<strong>奴隷、捕虜、または犯罪者</strong>でしたが、名声と賞金のために自発的に剣闘士学校（<em>ルドゥス</em>）に入った自由市民もいました。</p><p class="mb-4"><strong>スパルタクス</strong>は歴史上最も有名なグラディエーターで、ローマ史上最大の奴隷反乱（紀元前73–71年）を率い、70,000人以上の奴隷を集めました。</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — グラディエーター。| Smithsonian — ローマの剣闘士の真実。| History.com — グラディエーター。 | Encyclopaedia Britannica — グラディエーター。| Smithsonian — ローマの剣闘士の真実。| History.com — グラディエーター。 | History.com — グラディエーター。| Smithsonian — ローマの剣闘士の真実。| History.com — グラディエーター。' },
          ko: { title: '글래디에이터 — 로마 경기장의 전사들', desc: '로마 경기장에서 목숨을 걸고 싸운 글래디에이터들, 제국의 힘과 오락의 상징.', content: '<p class="mb-4">글래디에이터는 로마 시민의 오락을 위해 공개 경기장에서 싸운 훈련된 전사들입니다. "글래디에이터"라는 단어는 로마 단검 <em>글라디우스</em>에서 유래했습니다.</p><p class="mb-4">대부분은 <strong>노예, 전쟁 포로, 범죄자</strong>였지만 명성과 상금을 위해 자발적으로 검투사 학교에 입학한 자유 시민도 있었습니다.</p><p class="mb-4"><strong>스파르타쿠스</strong>는 역사상 가장 유명한 글래디에이터로, 로마 역사상 최대 노예 반란(기원전 73–71년)을 이끌어 70,000명 이상의 노예를 모았습니다.</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — 글래디에이터. | Smithsonian — 로마 검투사의 진실. | History.com — 글래디에이터.' },
          zh: { title: '角斗士 — 罗马竞技场的战士', desc: '在罗马竞技场为生命而战的角斗士，帝国权力与娱乐的象征。', content: '<p class="mb-4">角斗士是在公开竞技场为罗马市民娱乐而战的训练有素的战士。"角斗士"一词来源于罗马短剑<em>格拉迪乌斯</em>。</p><p class="mb-4">大多数是<strong>奴隶、战俘或罪犯</strong>，但也有为了名声和奖金自愿进入角斗士学校的自由公民。</p><p class="mb-4"><strong>斯巴达克斯</strong>是历史上最著名的角斗士，领导了罗马历史上最大的奴隶起义（公元前73–71年），聚集了7万多名奴隶。</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — 角斗士。| Smithsonian — 罗马角斗士的真相。| History.com — 角斗士。 | Encyclopaedia Britannica — 角斗士。| Smithsonian — 罗马角斗士的真相。| History.com — 角斗士。 | History.com — 角斗士。| Smithsonian — 罗马角斗士的真相。| History.com — 角斗士。' }
        }
      },
      {
        id: 'romawi-vesuvius',
        langs: {
          id: { title: 'Letusan Vesuvius & Pompei (79 M)', desc: 'Letusan gunung berapi yang menguburkan kota Pompei dalam sekejap dan membekukan sebuah kota Romawi untuk selamanya.', content: '<p class="mb-4">Pada 24 Agustus 79 M, Gunung Vesuvius di Italia selatan meletus dengan kekuatan dahsyat, melepaskan awan panas (<em>pyroclastic surge</em>) setinggi 33 km ke udara. Dalam waktu kurang dari 24 jam, kota <strong>Pompei</strong> — populasi sekitar 11.000 jiwa — tertimbun abu vulkanik setinggi 4–6 meter dan lenyap dari ingatan manusia selama hampir 1.700 tahun.</p><p class="mb-4">Saksi mata terkenal dari peristiwa ini adalah <strong>Pliny the Younger</strong>, yang saat itu berusia 17 tahun. Ia menyaksikan letusan dari pantai Misenum dan menuliskan dua surat rinci kepada sejarawan Tacitus — menjadikannya laporan bencana alam pertama yang terdokumentasi dalam sejarah. Pamannya, Pliny the Elder, meninggal saat mencoba menyelamatkan korban.</p><p class="mb-4">Yang membuat Pompei unik adalah cara kematian yang terjadi: abu panas dan gas beracun membunuh sebagian besar penghuni hampir seketika. Tubuh mereka membusuk meninggalkan rongga dalam abu yang mengeras. Ketika arkeolog Giuseppe Fiorelli pada 1863 menuangkan <strong>gips cair</strong> ke dalam rongga-rongga tersebut, terbentuklah cetakan tubuh manusia dengan ekspresi teror yang sempurna.</p><p class="mb-4">Kota Pompei mulai digali secara sistematis sejak abad ke-18. Penggalian mengungkap kota yang membekukan momen — toko roti dengan roti yang masih ada dalam oven, grafiti di dinding, perabot rumah tangga, bahkan makanan di atas meja. Ini memberi gambaran paling jelas tentang kehidupan sehari-hari Romawi kuno.</p><p class="mb-4">Hingga hari ini, hanya sekitar <strong>2/3 dari Pompei telah digali</strong>. UNESCO menetapkannya sebagai Situs Warisan Dunia pada 1997. Vesuvius sendiri masih aktif dan memantau 3 juta penduduk Naples yang tinggal dalam radius bahayanya.</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — Pompeii: Life and Death in a Roman Town. | Smithsonian Magazine — The Dead Do Tell Tales at Vesuvius. | UNESCO World Heritage — Pompeii. | Pliny the Younger — Letters to Tacitus (Book VI).' },
          en: { title: 'Vesuvius Eruption & Pompeii (79 AD)', desc: 'The volcanic eruption that buried Pompeii instantly and froze a Roman city in time forever.', content: '<p class="mb-4">On August 24, 79 AD, Mount Vesuvius in southern Italy erupted with devastating force, sending a pyroclastic cloud 33 km high. Within 24 hours, <strong>Pompeii</strong> — population ~11,000 — was buried under 4–6 meters of volcanic ash, lost to human memory for nearly 1,700 years.</p><p class="mb-4"><strong>Pliny the Younger</strong>, aged 17, witnessed the eruption from the coast and wrote two detailed letters to historian Tacitus — the world\'s first documented eyewitness account of a natural disaster. His uncle, Pliny the Elder, died attempting to rescue survivors.</p><p class="mb-4">The hot ash and toxic gases killed most inhabitants almost instantly. Bodies decayed leaving cavities in hardened ash. When archaeologist Giuseppe Fiorelli in 1863 poured <strong>liquid plaster</strong> into these cavities, he created perfect human casts — faces frozen in terror.</p><p class="mb-4">Systematic excavations since the 18th century revealed a perfectly preserved city: bakeries with bread still in ovens, wall graffiti, household furniture, food on tables — the clearest snapshot of ancient Roman daily life.</p><p class="mb-4">Today only <strong>2/3 of Pompeii has been excavated</strong>. UNESCO declared it World Heritage in 1997. Vesuvius remains active, threatening 3 million Naples residents within its danger zone.</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — Pompeii: Life and Death in a Roman Town. | Smithsonian Magazine — The Dead Do Tell Tales at Vesuvius. | UNESCO — Pompeii World Heritage. | Pliny the Younger — Letters to Tacitus.' },
          ja: { title: 'ヴェスヴィオ噴火とポンペイ（79年）', desc: 'ポンペイを一瞬で埋め、ローマの都市を永遠に凍らせた火山噴火。', content: '<p class="mb-4">79年8月24日、イタリア南部のヴェスヴィオ山が噴火し、高さ33kmの火砕流雲を発生させました。24時間以内に<strong>ポンペイ</strong>（人口約11,000人）は4〜6mの火山灰の下に埋まり、約1,700年間人類の記憶から消えました。</p><p class="mb-4">17歳の<strong>小プリニウス</strong>が目撃し、歴史家タキトゥスへの2通の詳細な手紙に記録しました。これは世界初の自然災害目撃証言文書です。</p><p class="mb-4">1863年に考古学者フィオレッリが硬化した灰の空洞に<strong>石膏</strong>を流し込み、恐怖の表情を浮かべた完璧な人体鋳型を作りました。UNESCO は1997年に世界遺産に登録しました。</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — ポンペイ。| Smithsonian — ヴェスヴィオ火山。| UNESCO — ポンペイ世界遺産。' },
          ko: { title: '베수비오 화산 폭발과 폼페이 (서기 79년)', desc: '폼페이를 순식간에 매몰시켜 로마 도시를 영원히 얼어붙게 한 화산 폭발.', content: '<p class="mb-4">서기 79년 8월 24일, 이탈리아 남부 베수비오 화산이 폭발하여 33km 높이의 화쇄류 구름을 만들었습니다. 24시간 이내에 <strong>폼페이</strong>(인구 약 11,000명)는 4~6미터의 화산재 아래 묻혀 약 1,700년간 잊혀졌습니다.</p><p class="mb-4">17세의 <strong>소 플리니우스</strong>가 목격하고 역사가 타키투스에게 두 통의 상세한 편지를 남겼습니다. 세계 최초의 자연재해 목격 기록입니다.</p><p class="mb-4">1863년 고고학자 피오렐리가 굳은 화산재 공동에 <strong>석고</strong>를 부어 공포의 표정을 간직한 완벽한 인체 주형을 만들었습니다. UNESCO는 1997년 세계유산으로 지정했습니다.</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — 폼페이. | Smithsonian — 베수비오 화산. | UNESCO — 폼페이 세계유산.' },
          zh: { title: '维苏威火山爆发与庞贝城 (公元79年)', desc: '瞬间掩埋庞贝城、将一座罗马城市永远定格的火山喷发。', content: '<p class="mb-4">公元79年8月24日，意大利南部维苏威火山爆发，产生33公里高的火山灰云。24小时内，<strong>庞贝</strong>（约11,000人口）被埋于4-6米厚的火山灰下，从人类记忆中消失了近1,700年。</p><p class="mb-4">17岁的<strong>小普林尼</strong>目睹了这一切，并给历史学家塔西佗写了两封详细的信，成为世界上有记录的第一份自然灾害目击证词。</p><p class="mb-4">1863年，考古学家菲奥雷利将<strong>石膏液</strong>倒入硬化火山灰的空洞中，制造出表情恐惧的完美人体模型。UNESCO于1997年将其列为世界遗产。</p>', sourceDomain: 'nationalgeographic.com', sourceSnippet: 'National Geographic — 庞贝城。| Smithsonian — 维苏威火山。| UNESCO — 庞贝世界遗产。' }
        }
      },
      {
        id: 'romawi-via-appia',
        langs: {
          id: { title: 'Via Appia — Jalan Raya Pertama Dunia', desc: 'Jalan beraspal sepanjang 563 km yang dibangun Roma pada 312 SM dan menjadi fondasi jaringan jalan kekaisaran terbesar sepanjang masa.', content: '<p class="mb-4"><strong>Via Appia</strong> (Jalan Appia) adalah jalan raya besar pertama dalam sejarah, dibangun mulai 312 SM atas perintah sensor Appius Claudius Caecus. Membentang dari Roma ke Capua (awalnya 195 km), kemudian diperpanjang hingga Brindisi di ujung selatan Italia — total 563 km.</p><p class="mb-4">Konstruksinya luar biasa untuk zamannya: lapisan batu besar setebal 1,5 meter yang dipadatkan dengan kerikil dan mortar, dilapisi batu paving yang presisi. Lebar jalannya 4,1 meter — cukup untuk dua kereta melintas bersamaan. Banyak bagian Via Appia masih bisa dilalui kendaraan hingga hari ini, 2.300 tahun kemudian.</p><p class="mb-4">Via Appia adalah arteri militer dan komersial vital. Lewat jalan ini pasukan Roma bergerak cepat ke seluruh penjuru Italia. Setelah pemberontakan Spartacus (71 SM), 6.000 budak yang ditangkap disalibkan <strong>di sepanjang Via Appia</strong> dari Capua ke Roma — satu salib setiap 37 meter — sebagai peringatan mengerikan.</p><p class="mb-4">Di sepanjang jalan, keluarga kaya membangun mausoleum megah. Katakomba Romawi juga banyak ditemukan di sepanjang Via Appia — karena hukum Romawi melarang penguburan di dalam kota. Di sinilah umat Kristen awal bersembunyi dan beribadah selama masa penganiayaan.</p><p class="mb-4">Jaringan jalan Romawi akhirnya mencapai total <strong>400.000 km</strong> — melingkupi seluruh kekaisaran dari Skotlandia hingga Mesopotamia. Pepatah "Semua jalan menuju Roma" benar-benar mencerminkan kenyataan kekaisaran ini. Via Appia kini menjadi Taman Arkeologi dan dilindungi sebagai warisan budaya Italia.</p>', sourceDomain: 'smithsonianmag.com', sourceSnippet: 'Smithsonian Magazine — Via Appia: Rome\'s First Highway. | National Geographic — The Appian Way. | UNESCO — Via Appia nomination for World Heritage. | History.com — Roman Roads.' },
          en: { title: 'Via Appia — The World\'s First Highway', desc: 'The 563 km paved road built by Rome in 312 BC that became the foundation of history\'s greatest road network.', content: '<p class="mb-4">The <strong>Via Appia</strong> (Appian Way) was history\'s first major highway, built from 312 BC on the order of censor Appius Claudius Caecus. It stretched from Rome to Capua (195 km initially), later extended to Brindisi in southern Italy — 563 km total.</p><p class="mb-4">Its construction was extraordinary: 1.5-meter layers of compacted stone and gravel, topped with precision-fitted paving stones. Width of 4.1 meters allowed two chariots to pass. Many sections are still drivable today, 2,300 years later.</p><p class="mb-4">After Spartacus\' revolt (71 BC), 6,000 captured slaves were crucified <strong>along the Via Appia</strong> from Capua to Rome — one cross every 37 meters — as a gruesome warning.</p><p class="mb-4">The road was lined with grand mausoleums and Roman catacombs — where early Christians hid and worshipped during persecutions, since Roman law banned burials inside city walls.</p><p class="mb-4">Rome\'s total road network eventually reached <strong>400,000 km</strong> spanning from Scotland to Mesopotamia. "All roads lead to Rome" was literally true. Via Appia is now an Archaeological Park and protected Italian cultural heritage.</p>', sourceDomain: 'smithsonianmag.com', sourceSnippet: 'Smithsonian Magazine — Via Appia: Rome\'s First Highway. | National Geographic — The Appian Way. | UNESCO — Via Appia World Heritage Nomination. | History.com — Roman Roads.' },
          ja: { title: 'アッピア街道 — 世界初の幹線道路', desc: '紀元前312年にローマが建設した563kmの舗装道路、史上最大の道路網の基盤。', content: '<p class="mb-4"><strong>アッピア街道</strong>は紀元前312年から建設された歴史上初の主要幹線道路です。ローマからブリンディシまで全長563kmに及びます。</p><p class="mb-4">1.5mの圧縮石層の上に精密な舗石を敷いた構造で、現代でも多くの区間が通行可能です。スパルタクスの反乱後（紀元前71年）、6,000人の奴隷がこの街道沿いに磔にされました。</p><p class="mb-4">ローマの道路網は最終的に<strong>40万km</strong>に達し、スコットランドからメソポタミアまで網羅しました。「すべての道はローマに通ず」は文字通り事実でした。</p>', sourceDomain: 'smithsonianmag.com', sourceSnippet: 'Smithsonian — アッピア街道。| National Geographic — アッピア街道。| UNESCO — アッピア街道世界遺産申請。' },
          ko: { title: '아피아 가도 — 세계 최초의 고속도로', desc: '기원전 312년 로마가 건설한 563km 포장도로, 역사상 최대 도로망의 기반.', content: '<p class="mb-4"><strong>아피아 가도</strong>는 기원전 312년부터 건설된 역사상 최초의 주요 간선도로입니다. 로마에서 브린디시까지 전체 길이 563km에 달합니다.</p><p class="mb-4">1.5m 압축 석층 위에 정밀 포장석을 깔아 현재도 많은 구간이 통행 가능합니다. 스파르타쿠스 반란 후(기원전 71년) 6,000명의 노예가 이 도로 변에 십자가형을 당했습니다.</p><p class="mb-4">로마의 도로망은 최종적으로 <strong>40만km</strong>에 달해 스코틀랜드부터 메소포타미아까지 망라했습니다. "모든 길은 로마로 통한다"는 말 그대로 사실이었습니다.</p>', sourceDomain: 'smithsonianmag.com', sourceSnippet: 'Smithsonian — 아피아 가도. | National Geographic — 아피아 가도. | UNESCO — 아피아 가도 세계유산 신청.' },
          zh: { title: '阿比亚大道 — 世界第一条高速公路', desc: '公元前312年罗马建造的563公里铺装道路，史上最大道路网络的基础。', content: '<p class="mb-4"><strong>阿比亚大道</strong>是历史上第一条主要干线公路，从公元前312年开始建造。从罗马延伸到布林迪西，全长563公里。</p><p class="mb-4">1.5米压实石层上铺设精密铺路石，时至今日许多路段仍可通行。斯巴达克斯起义后（公元前71年），6,000名奴隶在这条道路沿线被钉十字架。</p><p class="mb-4">罗马道路网最终达到<strong>40万公里</strong>，从苏格兰延伸到美索不达米亚。"条条大路通罗马"是字面上的事实。</p>', sourceDomain: 'smithsonianmag.com', sourceSnippet: 'Smithsonian — 阿比亚大道。| National Geographic — 阿比亚大道。| UNESCO — 阿比亚大道世界遗产申请。' }
        }
      },
      {
        id: 'romawi-fall',
        langs: {
          id: { title: 'Kejatuhan Kekaisaran Romawi Barat (476 M)', desc: 'Bagaimana salah satu kekaisaran terkuat sepanjang masa runtuh — dan mengapa kejatuhannya masih diperdebatkan sejarawan hingga hari ini.', content: '<p class="mb-4">Pada 4 September 476 M, kaisar Romawi terakhir, <strong>Romulus Augustulus</strong>, digulingkan oleh pemimpin tentara bayaran Germanic bernama Odoacer. Peristiwa ini secara tradisional dianggap sebagai akhir Kekaisaran Romawi Barat dan, bagi banyak sejarawan, penanda berakhirnya Zaman Kuno dan dimulainya Abad Pertengahan.</p><p class="mb-4">Kejatuhan Roma bukan peristiwa tunggal melainkan proses bertahap selama berabad-abad. Sejarawan Edward Gibbon dalam karyanya klasik <em>The History of the Decline and Fall of the Roman Empire</em> (1776) mengidentifikasi beberapa faktor utama: tekanan militer dari bangsa-bangsa barbar di perbatasan, krisis ekonomi akibat inflasi dan pajak tinggi, melemahnya otoritas sipil, dan konflik internal yang terus-menerus.</p><p class="mb-4">Faktor lain yang banyak diperdebatkan adalah peran <strong>Kekristenan</strong>: Gibbon berargumen agama baru ini mengalihkan energi dan sumber daya dari pertahanan militer. Teori modern lain menyebut perubahan iklim, wabah penyakit (<em>Antonine Plague</em> dan <em>Plague of Cyprian</em>), bahkan keracunan timbal dari pipa air Romawi sebagai faktor kontribusi.</p><p class="mb-4">Meski Romawi Barat runtuh, <strong>Kekaisaran Romawi Timur</strong> (Byzantium) terus bertahan hampir 1.000 tahun lagi hingga jatuhnya Konstantinopel ke tangan Ottoman pada 1453 M. Bahasa, hukum, arsitektur, dan sistem pemerintahan Romawi terus hidup dalam peradaban Eropa dan dunia.</p><p class="mb-4">Warisan Roma nyata hingga hari ini: kalender Gregorian, bahasa Latin sebagai basis bahasa Eropa modern, sistem hukum Eropa, konsep republik dan senat, serta arsitektur megah seperti Pantheon dan Colosseum. Pertanyaan mengapa Roma runtuh tetap menjadi salah satu perdebatan terbesar dalam historiografi dunia.</p>', sourceDomain: 'history.com', sourceSnippet: 'History.com — The Fall of Rome. | Britannica — Western Roman Empire. | Edward Gibbon — Decline and Fall of the Roman Empire (1776). | The Guardian — Why did Rome fall? New research.' },
          en: { title: 'Fall of the Western Roman Empire (476 AD)', desc: 'How one of history\'s mightiest empires collapsed — and why its fall is still debated by historians today.', content: '<p class="mb-4">On September 4, 476 AD, the last Roman emperor, <strong>Romulus Augustulus</strong>, was deposed by Germanic mercenary leader Odoacer. This is traditionally considered the end of the Western Roman Empire and the beginning of the Middle Ages.</p><p class="mb-4">Rome\'s fall was not a single event but a gradual process over centuries. Historian Edward Gibbon in his classic <em>The History of the Decline and Fall of the Roman Empire</em> (1776) identified key factors: barbarian military pressure, economic crisis from inflation and taxation, weakening civic authority, and constant internal conflict.</p><p class="mb-4">Other debated factors include the role of <strong>Christianity</strong>, climate change, devastating plagues (Antonine Plague and Plague of Cyprian), and even lead poisoning from Roman water pipes.</p><p class="mb-4">Though the Western Empire fell, the <strong>Eastern Roman Empire</strong> (Byzantium) survived nearly 1,000 more years until Constantinople fell to the Ottomans in 1453 AD.</p><p class="mb-4">Rome\'s legacy endures today: the Gregorian calendar, Latin as the basis of European languages, European legal systems, the concepts of republic and senate, and monumental architecture like the Pantheon and Colosseum.</p>', sourceDomain: 'history.com', sourceSnippet: 'History.com — The Fall of Rome. | Britannica — Western Roman Empire. | Edward Gibbon — Decline and Fall of the Roman Empire (1776). | The Guardian — Why Did Rome Fall?' },
          ja: { title: '西ローマ帝国の崩壊（476年）', desc: '史上最強の帝国の一つがどのように崩壊したか — そしてその崩壊は今日も歴史家たちに議論されている。', content: '<p class="mb-4">476年9月4日、最後のローマ皇帝<strong>ロムルス・アウグストゥルス</strong>がゲルマン系傭兵隊長オドアケルによって廃位されました。これは西ローマ帝国の終焉と中世の始まりとされています。</p><p class="mb-4">ローマの崩壊は単一の出来事ではなく数百年にわたる段階的プロセスでした。エドワード・ギボンの古典的著作（1776年）は蛮族の軍事的圧力、インフレ、内部紛争などを主な要因として挙げています。</p><p class="mb-4"><strong>東ローマ帝国</strong>（ビザンティン）はさらに1,000年近く存続し、1453年にオスマン帝国に征服されました。グレゴリオ暦、ラテン語、ローマ法などの遺産は現代世界に生き続けています。</p>', sourceDomain: 'history.com', sourceSnippet: 'History.com — ローマの崩壊。| Britannica — 西ローマ帝国。| The Guardian — なぜローマは崩壊したのか。 | Encyclopaedia Britannica — ローマの崩壊。| Britannica — 西ローマ帝国。| The Guardian — なぜローマは崩壊したのか。 | Smithsonian Magazine — ローマの崩壊。| Britannica — 西ローマ帝国。| The Guardian — なぜローマは崩壊したのか。' },
          ko: { title: '서로마 제국의 멸망 (476년)', desc: '역사상 가장 강력한 제국 중 하나가 어떻게 붕괴했는가 — 그 몰락은 오늘날에도 역사학자들 사이에서 논쟁 중이다.', content: '<p class="mb-4">476년 9월 4일, 마지막 로마 황제 <strong>로물루스 아우구스툴루스</strong>가 게르만 용병 대장 오도아케르에게 폐위되었습니다. 이는 서로마 제국의 종말이자 중세의 시작으로 여겨집니다.</p><p class="mb-4">로마의 몰락은 단일 사건이 아닌 수백 년에 걸친 점진적 과정이었습니다. 에드워드 기번의 고전(1776년)은 야만족의 군사적 압력, 인플레이션, 내부 분쟁 등을 주요 요인으로 꼽았습니다.</p><p class="mb-4"><strong>동로마 제국</strong>(비잔티움)은 1,000년 가까이 더 존속하다 1453년 오스만 제국에 함락되었습니다. 그레고리력, 라틴어, 로마법 등의 유산은 현대 세계에 살아 있습니다.</p>', sourceDomain: 'history.com', sourceSnippet: 'History.com — 로마의 몰락. | Britannica — 서로마 제국. | The Guardian — 로마는 왜 몰락했는가.' },
          zh: { title: '西罗马帝国的灭亡 (476年)', desc: '史上最强大的帝国之一如何崩溃——其灭亡至今仍是历史学家争论的话题。', content: '<p class="mb-4">476年9月4日，最后一位罗马皇帝<strong>罗慕路斯·奥古斯都路斯</strong>被日耳曼雇佣兵首领奥多亚克废黜。这传统上被认为是西罗马帝国的终结和中世纪的开始。</p><p class="mb-4">罗马的衰落不是单一事件，而是数百年的渐进过程。爱德华·吉本的经典著作（1776年）列举了蛮族军事压力、通货膨胀、内部冲突等主要因素。</p><p class="mb-4"><strong>东罗马帝国</strong>（拜占庭）又存续了近1,000年，直到1453年被奥斯曼帝国征服。公历、拉丁语、罗马法等遗产至今仍存在于现代世界中。</p>', sourceDomain: 'history.com', sourceSnippet: 'History.com — 罗马的崩溃。| Britannica — 西罗马帝国。| The Guardian — 罗马为何灭亡？ | Encyclopaedia Britannica — 罗马的崩溃。| Britannica — 西罗马帝国。| The Guardian — 罗马为何灭亡？ | Smithsonian Magazine — 罗马的崩溃。| Britannica — 西罗马帝国。| The Guardian — 罗马为何灭亡？' }
        }
      }
    ]
  };
