// Wikybook — Data historis: jerman
// File ini di-generate otomatis. Jangan edit manual.

if (typeof window.countryDataFiles === 'undefined') window.countryDataFiles = {};

window.countryDataFiles['jerman'] = {
    names: { id: 'Jerman', en: 'Germany', ja: 'ドイツ', ko: '독일', zh: '德国' },
    flag: '🇩🇪',
    articles: [
      {
        id: 'jerman-holy-roman-empire',
        langs: {
          id: { title: 'Holy Roman Empire', desc: 'Peristiwa penting dalam sejarah Jerman yang membentuk peradaban kawasan.', content: '<p class="mb-4">Holy Roman Empire adalah salah satu momen paling berpengaruh dalam sejarah Jerman. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Holy Roman Empire masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Holy Roman Empire sebagai bagian tak terpisahkan dari identitas kolektif bangsa Jerman.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Holy Roman Empire.' },
          en: { title: 'Holy Roman Empire', desc: 'A defining moment in the history of Germany that shaped its civilization.', content: '<p class="mb-4">Holy Roman Empire stands as one of the most consequential events in the long history of Germany. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Holy Roman Empire from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Holy Roman Empire endures in the cultural memory and national identity of the people of Germany, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Holy Roman Empire.' },
          ja: { title: 'Holy Roman Empire', desc: 'ドイツの歴史を形成した重要な出来事。', content: '<p class="mb-4">Holy Roman Empireはドイツの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはHoly Roman Empireを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Holy Roman Empireの遺産はドイツの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Holy Roman Empire.' },
          ko: { title: 'Holy Roman Empire', desc: '독일의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Holy Roman Empire은(는) 독일의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Holy Roman Empire을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Holy Roman Empire의 유산은 독일 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Holy Roman Empire.' },
          zh: { title: 'Holy Roman Empire', desc: '塑造德国历史的重要事件。', content: '<p class="mb-4">Holy Roman Empire是德国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Holy Roman Empire，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Holy Roman Empire的遗产延续在德国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Holy Roman Empire.' },
        }
      },
      {
        id: 'jerman-martin-luther-reformation',
        langs: {
          id: { title: 'Martin Luther Reformation', desc: 'Peristiwa penting dalam sejarah Jerman yang membentuk peradaban kawasan.', content: '<p class="mb-4">Martin Luther Reformation adalah salah satu momen paling berpengaruh dalam sejarah Jerman. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Martin Luther Reformation masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Martin Luther Reformation sebagai bagian tak terpisahkan dari identitas kolektif bangsa Jerman.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Martin Luther Reformation.' },
          en: { title: 'Martin Luther Reformation', desc: 'A defining moment in the history of Germany that shaped its civilization.', content: '<p class="mb-4">Martin Luther Reformation stands as one of the most consequential events in the long history of Germany. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Martin Luther Reformation from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Martin Luther Reformation endures in the cultural memory and national identity of the people of Germany, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Martin Luther Reformation.' },
          ja: { title: 'Martin Luther Reformation', desc: 'ドイツの歴史を形成した重要な出来事。', content: '<p class="mb-4">Martin Luther Reformationはドイツの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはMartin Luther Reformationを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Martin Luther Reformationの遺産はドイツの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Martin Luther Reformation.' },
          ko: { title: 'Martin Luther Reformation', desc: '독일의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Martin Luther Reformation은(는) 독일의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Martin Luther Reformation을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Martin Luther Reformation의 유산은 독일 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Martin Luther Reformation.' },
          zh: { title: 'Martin Luther Reformation', desc: '塑造德国历史的重要事件。', content: '<p class="mb-4">Martin Luther Reformation是德国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Martin Luther Reformation，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Martin Luther Reformation的遗产延续在德国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Martin Luther Reformation.' },
        }
      },
      {
        id: 'jerman-otto-von-bismarck',
        langs: {
          id: { title: 'Otto von Bismarck', desc: 'Peristiwa penting dalam sejarah Jerman yang membentuk peradaban kawasan.', content: '<p class="mb-4">Otto von Bismarck adalah salah satu momen paling berpengaruh dalam sejarah Jerman. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Otto von Bismarck masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Otto von Bismarck sebagai bagian tak terpisahkan dari identitas kolektif bangsa Jerman.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Otto von Bismarck.' },
          en: { title: 'Otto von Bismarck', desc: 'A defining moment in the history of Germany that shaped its civilization.', content: '<p class="mb-4">Otto von Bismarck stands as one of the most consequential events in the long history of Germany. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Otto von Bismarck from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Otto von Bismarck endures in the cultural memory and national identity of the people of Germany, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Otto von Bismarck.' },
          ja: { title: 'Otto von Bismarck', desc: 'ドイツの歴史を形成した重要な出来事。', content: '<p class="mb-4">Otto von Bismarckはドイツの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはOtto von Bismarckを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Otto von Bismarckの遺産はドイツの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Otto von Bismarck.' },
          ko: { title: 'Otto von Bismarck', desc: '독일의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Otto von Bismarck은(는) 독일의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Otto von Bismarck을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Otto von Bismarck의 유산은 독일 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Otto von Bismarck.' },
          zh: { title: 'Otto von Bismarck', desc: '塑造德国历史的重要事件。', content: '<p class="mb-4">Otto von Bismarck是德国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Otto von Bismarck，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Otto von Bismarck的遗产延续在德国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Otto von Bismarck.' },
        }
      },
      {
        id: 'jerman-weimar-republic',
        langs: {
          id: { title: 'Weimar Republic', desc: 'Peristiwa penting dalam sejarah Jerman yang membentuk peradaban kawasan.', content: '<p class="mb-4">Weimar Republic adalah salah satu momen paling berpengaruh dalam sejarah Jerman. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Weimar Republic masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Weimar Republic sebagai bagian tak terpisahkan dari identitas kolektif bangsa Jerman.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Weimar Republic.' },
          en: { title: 'Weimar Republic', desc: 'A defining moment in the history of Germany that shaped its civilization.', content: '<p class="mb-4">Weimar Republic stands as one of the most consequential events in the long history of Germany. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Weimar Republic from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Weimar Republic endures in the cultural memory and national identity of the people of Germany, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Weimar Republic.' },
          ja: { title: 'Weimar Republic', desc: 'ドイツの歴史を形成した重要な出来事。', content: '<p class="mb-4">Weimar Republicはドイツの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはWeimar Republicを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Weimar Republicの遺産はドイツの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Weimar Republic.' },
          ko: { title: 'Weimar Republic', desc: '독일의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Weimar Republic은(는) 독일의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Weimar Republic을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Weimar Republic의 유산은 독일 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Weimar Republic.' },
          zh: { title: 'Weimar Republic', desc: '塑造德国历史的重要事件。', content: '<p class="mb-4">Weimar Republic是德国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Weimar Republic，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Weimar Republic的遗产延续在德国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Weimar Republic.' },
        }
      },
      {
        id: 'jerman-berlin-wall',
        langs: {
          id: { title: 'Berlin Wall', desc: 'Peristiwa penting dalam sejarah Jerman yang membentuk peradaban kawasan.', content: '<p class="mb-4">Berlin Wall adalah salah satu momen paling berpengaruh dalam sejarah Jerman. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Berlin Wall masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Berlin Wall sebagai bagian tak terpisahkan dari identitas kolektif bangsa Jerman.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Berlin Wall.' },
          en: { title: 'Berlin Wall', desc: 'A defining moment in the history of Germany that shaped its civilization.', content: '<p class="mb-4">Berlin Wall stands as one of the most consequential events in the long history of Germany. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Berlin Wall from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Berlin Wall endures in the cultural memory and national identity of the people of Germany, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Berlin Wall.' },
          ja: { title: 'Berlin Wall', desc: 'ドイツの歴史を形成した重要な出来事。', content: '<p class="mb-4">Berlin Wallはドイツの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはBerlin Wallを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Berlin Wallの遺産はドイツの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Berlin Wall.' },
          ko: { title: 'Berlin Wall', desc: '독일의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Berlin Wall은(는) 독일의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Berlin Wall을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Berlin Wall의 유산은 독일 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Berlin Wall.' },
          zh: { title: 'Berlin Wall', desc: '塑造德国历史的重要事件。', content: '<p class="mb-4">Berlin Wall是德国漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Berlin Wall，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Berlin Wall的遗产延续在德国人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Berlin Wall.' },
        }
      }
    ]
  };
