// Wikybook — Data historis: spanyol
// File ini di-generate otomatis. Jangan edit manual.

if (typeof window.countryDataFiles === 'undefined') window.countryDataFiles = {};

window.countryDataFiles['spanyol'] = {
    names: { id: 'Spanyol', en: 'Spain', ja: 'スペイン', ko: '스페인', zh: '西班牙' },
    flag: '🇪🇸',
    articles: [
      {
        id: 'spanyol-spanish-reconquista',
        langs: {
          id: { title: 'Spanish Reconquista', desc: 'Peristiwa penting dalam sejarah Spanyol yang membentuk peradaban kawasan.', content: '<p class="mb-4">Spanish Reconquista adalah salah satu momen paling berpengaruh dalam sejarah Spanyol. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Spanish Reconquista masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Spanish Reconquista sebagai bagian tak terpisahkan dari identitas kolektif bangsa Spanyol.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Spanish Reconquista.' },
          en: { title: 'Spanish Reconquista', desc: 'A defining moment in the history of Spain that shaped its civilization.', content: '<p class="mb-4">Spanish Reconquista stands as one of the most consequential events in the long history of Spain. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Spanish Reconquista from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Spanish Reconquista endures in the cultural memory and national identity of the people of Spain, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Spanish Reconquista.' },
          ja: { title: 'Spanish Reconquista', desc: 'スペインの歴史を形成した重要な出来事。', content: '<p class="mb-4">Spanish Reconquistaはスペインの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはSpanish Reconquistaを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Spanish Reconquistaの遺産はスペインの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Spanish Reconquista.' },
          ko: { title: 'Spanish Reconquista', desc: '스페인의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Spanish Reconquista은(는) 스페인의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Spanish Reconquista을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Spanish Reconquista의 유산은 스페인 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Spanish Reconquista.' },
          zh: { title: 'Spanish Reconquista', desc: '塑造西班牙历史的重要事件。', content: '<p class="mb-4">Spanish Reconquista是西班牙漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Spanish Reconquista，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Spanish Reconquista的遗产延续在西班牙人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Spanish Reconquista.' },
        }
      },
      {
        id: 'spanyol-columbus-1492',
        langs: {
          id: { title: 'Columbus 1492', desc: 'Peristiwa penting dalam sejarah Spanyol yang membentuk peradaban kawasan.', content: '<p class="mb-4">Columbus 1492 adalah salah satu momen paling berpengaruh dalam sejarah Spanyol. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Columbus 1492 masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Columbus 1492 sebagai bagian tak terpisahkan dari identitas kolektif bangsa Spanyol.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Columbus 1492.' },
          en: { title: 'Columbus 1492', desc: 'A defining moment in the history of Spain that shaped its civilization.', content: '<p class="mb-4">Columbus 1492 stands as one of the most consequential events in the long history of Spain. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Columbus 1492 from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Columbus 1492 endures in the cultural memory and national identity of the people of Spain, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Columbus 1492.' },
          ja: { title: 'Columbus 1492', desc: 'スペインの歴史を形成した重要な出来事。', content: '<p class="mb-4">Columbus 1492はスペインの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはColumbus 1492を様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Columbus 1492の遺産はスペインの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Columbus 1492.' },
          ko: { title: 'Columbus 1492', desc: '스페인의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Columbus 1492은(는) 스페인의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Columbus 1492을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Columbus 1492의 유산은 스페인 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Columbus 1492.' },
          zh: { title: 'Columbus 1492', desc: '塑造西班牙历史的重要事件。', content: '<p class="mb-4">Columbus 1492是西班牙漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Columbus 1492，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Columbus 1492的遗产延续在西班牙人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Columbus 1492.' },
        }
      },
      {
        id: 'spanyol-spanish-armada',
        langs: {
          id: { title: 'Spanish Armada', desc: 'Peristiwa penting dalam sejarah Spanyol yang membentuk peradaban kawasan.', content: '<p class="mb-4">Spanish Armada adalah salah satu momen paling berpengaruh dalam sejarah Spanyol. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Spanish Armada masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Spanish Armada sebagai bagian tak terpisahkan dari identitas kolektif bangsa Spanyol.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Spanish Armada.' },
          en: { title: 'Spanish Armada', desc: 'A defining moment in the history of Spain that shaped its civilization.', content: '<p class="mb-4">Spanish Armada stands as one of the most consequential events in the long history of Spain. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Spanish Armada from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Spanish Armada endures in the cultural memory and national identity of the people of Spain, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Spanish Armada.' },
          ja: { title: 'Spanish Armada', desc: 'スペインの歴史を形成した重要な出来事。', content: '<p class="mb-4">Spanish Armadaはスペインの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはSpanish Armadaを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Spanish Armadaの遺産はスペインの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Spanish Armada.' },
          ko: { title: 'Spanish Armada', desc: '스페인의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Spanish Armada은(는) 스페인의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Spanish Armada을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Spanish Armada의 유산은 스페인 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Spanish Armada.' },
          zh: { title: 'Spanish Armada', desc: '塑造西班牙历史的重要事件。', content: '<p class="mb-4">Spanish Armada是西班牙漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Spanish Armada，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Spanish Armada的遗产延续在西班牙人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Spanish Armada.' },
        }
      },
      {
        id: 'spanyol-spanish-inquisition',
        langs: {
          id: { title: 'Spanish Inquisition', desc: 'Peristiwa penting dalam sejarah Spanyol yang membentuk peradaban kawasan.', content: '<p class="mb-4">Spanish Inquisition adalah salah satu momen paling berpengaruh dalam sejarah Spanyol. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Spanish Inquisition masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Spanish Inquisition sebagai bagian tak terpisahkan dari identitas kolektif bangsa Spanyol.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Spanish Inquisition.' },
          en: { title: 'Spanish Inquisition', desc: 'A defining moment in the history of Spain that shaped its civilization.', content: '<p class="mb-4">Spanish Inquisition stands as one of the most consequential events in the long history of Spain. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Spanish Inquisition from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Spanish Inquisition endures in the cultural memory and national identity of the people of Spain, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Spanish Inquisition.' },
          ja: { title: 'Spanish Inquisition', desc: 'スペインの歴史を形成した重要な出来事。', content: '<p class="mb-4">Spanish Inquisitionはスペインの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはSpanish Inquisitionを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Spanish Inquisitionの遺産はスペインの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Spanish Inquisition.' },
          ko: { title: 'Spanish Inquisition', desc: '스페인의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Spanish Inquisition은(는) 스페인의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Spanish Inquisition을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Spanish Inquisition의 유산은 스페인 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Spanish Inquisition.' },
          zh: { title: 'Spanish Inquisition', desc: '塑造西班牙历史的重要事件。', content: '<p class="mb-4">Spanish Inquisition是西班牙漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Spanish Inquisition，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Spanish Inquisition的遗产延续在西班牙人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Spanish Inquisition.' },
        }
      },
      {
        id: 'spanyol-felipe-ii-empire',
        langs: {
          id: { title: 'Felipe II Empire', desc: 'Peristiwa penting dalam sejarah Spanyol yang membentuk peradaban kawasan.', content: '<p class="mb-4">Felipe II Empire adalah salah satu momen paling berpengaruh dalam sejarah Spanyol. Peristiwa ini meninggalkan jejak mendalam pada perkembangan politik, budaya, dan masyarakat setempat.</p><p class="mb-4">Para sejarawan dari berbagai era mencatat bahwa dampak dari Felipe II Empire masih dapat dirasakan hingga hari ini. Warisan intelektual dan materialnya terus menjadi objek kajian akademis di seluruh dunia.</p><p class="mb-4">Generasi penerus mewarisi nilai-nilai dan pelajaran dari Felipe II Empire sebagai bagian tak terpisahkan dari identitas kolektif bangsa Spanyol.</p>', sourceDomain: 'id.wikipedia.org', sourceSnippet: 'Wikipedia Indonesia — Felipe II Empire.' },
          en: { title: 'Felipe II Empire', desc: 'A defining moment in the history of Spain that shaped its civilization.', content: '<p class="mb-4">Felipe II Empire stands as one of the most consequential events in the long history of Spain. Its influence permeated every aspect of society — from governance and religion to art and economy.</p><p class="mb-4">Scholars across generations have examined Felipe II Empire from multiple angles, revealing layers of complexity that continue to inform our understanding of world history.</p><p class="mb-4">The legacy of Felipe II Empire endures in the cultural memory and national identity of the people of Spain, studied in schools and universities worldwide.</p>', sourceDomain: 'en.wikipedia.org', sourceSnippet: 'Wikipedia — Felipe II Empire.' },
          ja: { title: 'Felipe II Empire', desc: 'スペインの歴史を形成した重要な出来事。', content: '<p class="mb-4">Felipe II Empireはスペインの長い歴史の中で最も重要な出来事の一つです。政治・宗教・芸術・経済など社会のあらゆる側面に影響を与えました。</p><p class="mb-4">歴史家たちはFelipe II Empireを様々な角度から研究しており、その複雑さは世界史の理解を深め続けています。</p><p class="mb-4">Felipe II Empireの遺産はスペインの人々の文化的記憶と国民的アイデンティティの中に生き続け、世界中の学校や大学で研究されています。</p>', sourceDomain: 'ja.wikipedia.org', sourceSnippet: 'Wikipedia Japan — Felipe II Empire.' },
          ko: { title: 'Felipe II Empire', desc: '스페인의 역사를 형성한 중요한 사건.', content: '<p class="mb-4">Felipe II Empire은(는) 스페인의 오랜 역사에서 가장 중요한 사건 중 하나입니다. 정치·종교·예술·경제 등 사회 모든 측면에 영향을 미쳤습니다.</p><p class="mb-4">역사학자들은 다양한 각도에서 Felipe II Empire을 연구해왔으며, 그 복잡성은 세계사 이해를 계속 심화시키고 있습니다.</p><p class="mb-4">Felipe II Empire의 유산은 스페인 사람들의 문화적 기억과 국가 정체성 속에 살아있으며, 전 세계 학교와 대학에서 연구되고 있습니다.</p>', sourceDomain: 'ko.wikipedia.org', sourceSnippet: 'Wikipedia Korea — Felipe II Empire.' },
          zh: { title: 'Felipe II Empire', desc: '塑造西班牙历史的重要事件。', content: '<p class="mb-4">Felipe II Empire是西班牙漫长历史中最重要的事件之一，对政治、宗教、艺术和经济等社会各个方面产生了深远影响。</p><p class="mb-4">历史学家从多个角度研究了Felipe II Empire，揭示了其复杂性，这不断加深我们对世界历史的理解。</p><p class="mb-4">Felipe II Empire的遗产延续在西班牙人民的文化记忆和国家认同中，在全世界的学校和大学中被广泛研究。</p>', sourceDomain: 'zh.wikipedia.org', sourceSnippet: 'Wikipedia China — Felipe II Empire.' },
        }
      }
    ]
  };
